/** Reviewed Korean copy for the Australia major catalogue. */
const MAJOR_DESCRIPTIONS_KO: Record<string, string> = {
  "computer-science": "컴퓨팅, 알고리즘, 시스템과 소프트웨어의 기초를 다룹니다.",
  "data-analytics": "데이터 분석, 통계, 머신러닝과 실무형 AI를 다룹니다.",
  cybersecurity: "보안 운영, 시스템 방어와 정보보호를 다룹니다.",
  nursing: "간호 교육과 임상 실무를 통해 등록간호사 진로를 준비합니다.",
  "aged-care": "노인과 지역사회 환경에서 필요한 돌봄 자격과 실무를 다룹니다.",
  "allied-health": "재활, 치료와 보건의료 연계 직종으로 이어지는 학업을 다룹니다.",
  engineering: "토목·기계·전기 등 다양한 공학 진로의 기초를 다룹니다.",
  "civil-engineering": "인프라, 구조물, 교통과 건설 시스템을 다룹니다.",
  "mechanical-engineering": "기계 시스템, 설계, 제조와 에너지 분야를 다룹니다.",
  "business-analytics": "데이터, 운영과 정보시스템을 활용해 비즈니스 의사결정을 다룹니다.",
  accounting: "재무보고, 감사, 세무와 전문 회계 진로를 다룹니다.",
  "early-childhood": "규제된 교육·돌봄 환경에서 어린이의 성장과 학습을 다룹니다.",
  carpentry: "건설 목공, 가구·내장 목공과 목재 구조물을 다룹니다.",
  "wall-floor-tiling": "벽·바닥과 특수 타일의 시공 기술을 다룹니다.",
  "electrical-trade": "전기 설치, 유지보수와 규제된 전기 기술 훈련을 다룹니다.",
  plumbing: "급수, 배수, 가스와 규제된 배관 시스템을 다룹니다.",
  welding: "용접, 금속 제작과 구조용 금속 작업을 다룹니다.",
  automotive: "차량 진단, 정비와 수리 자격을 다룹니다.",
  "hospitality-management": "호텔, 관광, 외식과 서비스 운영을 다룹니다.",
  architecture: "건축, 공간 설계와 건축 환경을 다룹니다.",
  "design-media": "시각·인터랙션·디지털 미디어 디자인을 다룹니다.",
  "environmental-science": "환경 시스템, 보전과 지속가능성을 다룹니다.",
  agriculture: "농업, 식품 생산과 농업 비즈니스를 다룹니다.",
  aviation: "비행, 공항 운영과 항공기 정비 진로를 다룹니다.",
  "culinary-arts": "상업 조리, 제빵과 식음료 조리 기술을 다룹니다.",
  "beauty-wellness": "뷰티 테라피, 피부관리, 헤어와 퍼스널 케어 자격을 다룹니다.",
  "social-work": "사회복지, 커뮤니티 서비스, 청소년 지원과 상담 진로를 다룹니다.",
  dental: "치과, 치위생, 구강건강 치료와 치과기공 진로를 다룹니다.",
  law: "법학 교육, 변호사·법무사 훈련과 법률 실무를 다룹니다.",
  "sport-fitness": "스포츠과학, 운동생리학, 피트니스와 야외활동 리더십을 다룹니다.",
  bricklaying: "벽돌·블록 쌓기, 석공과 미장 마감 기술을 다룹니다.",
  hvac: "냉난방공조와 냉동 시스템의 설치·정비·수리를 다룹니다.",
  maritime: "해양 항해, 선박 기관, 항만 운영과 해운 자격을 다룹니다.",
  "mining-resources": "광업, 석유, 자원 개발과 지반공학 진로를 다룹니다.",
  psychology: "심리과학, 임상 실무, 상담과 정신건강 개입을 다룹니다.",
  "paramedic-emergency": "병원 전 응급처치, 구급과 응급의료 운영을 다룹니다.",
  veterinary: "수의학, 동물 건강과 수의 간호를 다룹니다.",
  "primary-secondary-education": "초등·중등 교사 양성과 교육학 진로를 다룹니다.",
  "photography-film": "사진, 영화·TV 제작, 촬영과 후반작업을 다룹니다.",
}

const COST_NOTES_KO: Record<string, string> = {
  "computer-science": "컴퓨터과학 학사는 보통 3년이며, 일부 대학은 4년 우등과정을 운영합니다. IT 졸업생은 졸업 후 485 비자를 검토할 수 있습니다.",
  "data-analytics": "데이터 분석은 석사 과정으로 많이 공부하며, 데이터과학 또는 IT 학사에서 세부전공으로 선택할 수도 있습니다.",
  cybersecurity: "대학원 세부전공으로 많이 제공되며, 사이버보안 단독 학사과정을 운영하는 대학도 있습니다.",
  nursing: "간호학 학사는 보통 3년이며 AHPRA 등록이 필요합니다. 일부 대학은 2년 속성 과정을 제공합니다.",
  "aged-care": "개인지원 Certificate III는 약 12개월 과정으로, 노인돌봄 취업으로 이어지는 빠르고 비용 부담이 낮은 경로입니다.",
  "allied-health": "물리치료·작업치료·언어병리학은 보통 4년 이상이며, 대부분 등록 또는 인증 요건을 확인해야 합니다.",
  dental: "치과 과정은 보통 4~5년이며 입학 경쟁이 높습니다. 국제학생 학비가 높지만 영주권 신호는 강한 편입니다.",
  psychology: "3년 학사, 1년 우등과정과 2년 석사를 합친 등록 경로가 일반적입니다. 임상심리학은 박사과정이 필요할 수 있습니다.",
  "paramedic-emergency": "구급·응급의료 학사는 보통 3년이며 정원이 제한적입니다. 전국적인 인력 부족 신호가 확인됩니다.",
  engineering: "공학 학사는 보통 4년 우등과정이며 Engineers Australia 인증 여부를 확인해야 합니다.",
  "civil-engineering": "공학 우등과정 안에서 세부전공으로 선택하는 경우가 많으며, 인프라 투자로 수요가 이어지고 있습니다.",
  "mechanical-engineering": "공학 우등과정 안에서 기계공학 세부전공으로 선택하는 경로가 일반적입니다.",
  "mining-resources": "서호주와 퀸즐랜드에 광업 수요가 집중되어 있으며, 공학 분야 중 높은 초봉 신호가 확인됩니다.",
  "business-analytics": "비즈니스 애널리틱스 석사로 많이 공부하며, 상경계열 또는 IT 학사에서 분석 전공을 선택할 수도 있습니다.",
  accounting: "CPA·CA 인증 경로가 있으며, 비회계 전공자를 위한 전문회계 석사과정도 제공됩니다.",
  law: "LLB는 보통 4년, 비법학 전공자의 JD는 3년입니다. 학위 후 실무법률교육(PLT)이 필요합니다.",
  "primary-secondary-education": "초등 또는 중등 교육학 학사는 보통 4년이며 교생실습을 포함합니다. 주별 교사 등록 요건을 확인해야 합니다.",
  "early-childhood": "유아교육 학사는 보통 3년, TAFE 디플로마는 약 2년이며 ACECQA 요건을 확인해야 합니다.",
  "social-work": "사회복지학 학사는 보통 4년이며 AASW 인증과 현장실습이 포함됩니다.",
  "sport-fitness": "스포츠·운동과학 학사는 보통 3년이며, 운동생리학은 우등과정이 필요할 수 있습니다.",
  carpentry: "목공 Certificate III는 견습을 포함해 약 3.5~4년이며, 기술직 중 영주권 경로가 강한 편입니다.",
  "wall-floor-tiling": "벽·바닥 타일 Certificate III는 견습을 포함해 약 3년입니다.",
  "electrical-trade": "전기기술 Certificate III는 견습을 포함해 약 4년이며, 호주에서 수요가 높은 기술직 중 하나입니다.",
  plumbing: "배관 Certificate III는 견습을 포함해 약 4년이며, 인력 부족도가 높은 직종입니다.",
  welding: "금속·용접 기술 Certificate III는 약 3년이며 광업 부문의 수요가 영향을 줍니다.",
  bricklaying: "조적·블록쌓기 Certificate III는 견습을 포함해 약 3년입니다.",
  hvac: "냉동·냉난방 Certificate III는 견습을 포함해 약 4년이며 기후 변화와 함께 수요가 커지고 있습니다.",
  architecture: "건축학 학사는 보통 5년이며 AACA 인증과 실무 등록 요건을 확인해야 합니다.",
  "design-media": "디자인·미디어·커뮤니케이션 디자인 과정은 포트폴리오를 요구할 수 있습니다.",
  "photography-film": "영화·스크린 제작 학사는 포트폴리오와 면접을 요구할 수 있으며 직접적인 영주권 경로는 제한적입니다.",
  "environmental-science": "환경과학 학사는 보통 3년이며 기후정책과 환경 규제로 수요가 커지고 있습니다.",
  agriculture: "농업과학 학사는 지역 수요가 강하며 491 비자 경로를 함께 검토할 수 있습니다.",
  veterinary: "수의학 과정은 보통 5년이며 입학 경쟁이 높고 전국적인 인력 부족이 확인됩니다.",
  "hospitality-management": "호텔경영·관광 과정 중에는 유급 산업체 실습을 포함하는 경우가 있습니다.",
  "culinary-arts": "상업조리 Certificate III는 약 12~18개월, 조리학 학사는 약 3년이며 요리·제빵 인력 부족이 있습니다.",
  "beauty-wellness": "뷰티 테라피 Certificate III는 약 12~18개월이며 뷰티·헤어 직종의 인력 부족 신호가 있습니다.",
  automotive: "자동차 정비 Certificate III는 견습을 포함해 약 4년이며 수요가 안정적입니다.",
  aviation: "항공 학사는 보통 3년이며, 비행훈련 비용으로 학비 외 약 A$80,000~120,000가 추가될 수 있습니다.",
  maritime: "Australian Maritime College가 주요 교육기관이며 Certificate와 학사 경로를 모두 제공합니다.",
}

const OCCUPATION_LABELS_KO: Record<string, string> = {
  "Data Architect": "데이터 아키텍트",
  "Data Engineer": "데이터 엔지니어",
  "Cloud Engineer": "클라우드 엔지니어",
  "DevOps Engineer": "DevOps 엔지니어",
  "Cyber Security Engineer": "사이버보안 엔지니어",
  "Database Administrator": "데이터베이스 관리자",
  "Cost Controller": "원가 관리사",
  "Information and Organisation Professionals nec": "정보·조직 전문가",
  "Cyber Security Advice and Assessment Specialist": "사이버보안 자문·평가 전문가",
  "Cyber Governance Risk and Compliance Specialist": "사이버 거버넌스·위험·컴플라이언스 전문가",
  "Cyber Security Operations Coordinator": "사이버보안 운영 코디네이터",
  "Registered Nurse (Acute Care)": "급성기 간호사",
  "Registered Nurses nec": "기타 등록간호사",
  Midwife: "조산사",
  "Registered Nurse (Aged Care)": "노인돌봄 간호사",
  "Registered Nurse (Mental Health)": "정신건강 간호사",
  "Registered Nurse (Primary Health Care)": "일차보건 간호사",
  "Community Support Worker": "지역사회 지원원",
  "Community Aged Care Support Worker": "지역사회 노인돌봄 지원원",
  "Disability Support Worker": "장애인 지원원",
  "Occupational Therapist": "작업치료사",
  Physiotherapist: "물리치료사",
  "Dental Specialist": "치과 전문의",
  Psychologist: "심리학자",
  "Allied Health Counsellors, Psychologists, Social Workers and Creative Therapy Professionals nec": "보건의료·상담·사회복지 전문가",
  "Paramedic Manager": "구급대 관리자",
  "Critical Care Paramedic": "중환자 구급대원",
  "Fire Safety Engineer": "소방안전 엔지니어",
  "Mechatronics Engineer": "메카트로닉스 엔지니어",
  "Engineering Professionals nec": "기타 공학 전문가",
  "Acoustic Engineer": "음향 엔지니어",
  "Aerospace Engineer": "항공우주 엔지니어",
  "Engineering Manager": "공학 관리자",
  "Construction Project Manager": "건설 프로젝트 관리자",
  "Quantity Surveyor": "공사비 산정사",
  "Civil Engineer": "토목 엔지니어",
  "Mechanical Engineer": "기계 엔지니어",
  "Production or Plant Engineer": "생산·플랜트 엔지니어",
  "Engineering Technologist": "공학 기술자",
  Driller: "시추공",
  "Accountant (General)": "회계사",
  "Forensic Accountant": "포렌식 회계사",
  "Management Accountant": "관리 회계사",
  "Taxation Accountant": "세무 회계사",
  "External Auditor": "외부 감사인",
  Barrister: "법정 변호사",
  "Early Childhood (Pre-primary School) Teacher": "유아·취학 전 교사",
  "Primary School Teacher": "초등학교 교사",
  "Secondary School Teacher": "중등학교 교사",
  "Alcohol and Other Drugs Counsellor": "알코올·약물 상담사",
  "Rehabilitation Counsellor": "재활 상담사",
  "School Counsellor": "학교 상담사",
  "Social Worker": "사회복지사",
  "Outdoor Adventure Leader or Guide": "야외 모험활동 리더·가이드",
  "Carpenter and Joiner": "목수·가구 목공",
  "Automotive Electrician": "자동차 전기 기술자",
  "Electrical Distribution Trades Worker": "전기 배전 기술자",
  "Industrial Electrician": "산업 전기 기술자",
  "Plumber (General)": "일반 배관공",
  "Roof Plumber": "지붕 배관공",
  "Fire Protection Plumber": "소방 배관공",
  "Mechanical Services Plumber": "기계설비 배관공",
  "Metal Fabricator": "금속 제작 기술자",
  "Pressure Welder": "압력 용접공",
  "Welder (First Class)": "1급 용접공",
  "Fitter-Welder": "기계조립·용접공",
  "Multimedia Designer": "멀티미디어 디자이너",
  "Web Designer": "웹 디자이너",
  "Film and Video Editor": "영화·영상 편집자",
  "Environmental Research Scientist": "환경 연구 과학자",
  "Environmental Consultants and Scientists nec": "환경 컨설턴트·과학자",
  "Agricultural Research Scientist": "농업 연구 과학자",
  Agronomist: "농업학자",
  "Veterinary Nurse": "수의 간호사",
  "Cafe or Restaurant Manager": "카페·레스토랑 관리자",
  "Hotel or Motel Manager": "호텔·모텔 관리자",
  "Licensed Club Manager": "회원제 클럽 관리자",
  Barber: "이발사",
  "Air Transport Professionals nec": "항공 운송 전문가",
  "Marine Pilot": "해상 도선사",
}

export function getLocalizedMajorDescription(id: string, isKo: boolean, fallback: string) {
  return isKo ? MAJOR_DESCRIPTIONS_KO[id] ?? fallback : fallback
}

export function getLocalizedMajorCostNote(id: string, isKo: boolean, fallback: string) {
  return isKo ? COST_NOTES_KO[id] ?? fallback : fallback
}

export function getLocalizedOccupationLabel(label: string, labelKo: string, isKo: boolean) {
  if (!isKo) return label
  return labelKo !== label ? labelKo : OCCUPATION_LABELS_KO[label] ?? labelKo
}
