export const LOGIN_COPY = {
  welcome: "Sign in to CampCareer",
  welcomeSupporting: "Save careers and keep your progress. Core career information stays available without an account.",
  signup: "Create your CampCareer account",
  signupSupporting: "Create an account to save decisions and return to them later.",
  saveTitle: "Save this career",
  saveSupporting: "Sign in to keep this career and come back to it anytime.",
  saveSignupSupporting: "Create an account to save this career and return to it anytime.",
  google: "Continue with Google",
  divider: "or continue with email",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  createAccount: "Create an account",
  forgotPassword: "Forgot password?",
  newAccount: "New to CampCareer?",
  existingAccount: "Already have an account?",
  back: "Back to CampCareer",
  backToCareer: "Back to career",
} as const
