"use client"

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react"
import { Award, Banknote, BookOpenCheck, Check, ChevronRight, Circle, CircleCheck, ClipboardCheck, FileCheck2, GraduationCap, Landmark, Languages, Plus, Send, Target, Trash2 } from "lucide-react"
import { cn } from "@/lib/utils"
import { useRouteLocale } from "@/lib/i18n/locale-provider"

export type ExecutionApplication = { id: string; goal_option_id: string | null; provider_name: string; programme_name: string; status: "planning" | "preparing" | "submitted" | "offer" | "declined"; deadline_date: string | null; offer_date: string | null; notes: string }
export type ExecutionDocument = { id: string; application_id: string | null; label: string; status: "todo" | "ready" | "submitted" }
export type ExecutionBudget = { currency: string; current_savings: number; monthly_saving: number; target_amount: number | null; target_date: string | null }
export type ExecutionMoneyScenario = { scholarship_amount: number; conservative_cost_lift: number }
export type ExecutionLanguage = { exam_name: string; current_score: number | null; target_score: number | null; weekly_hours: number | null; test_date: string | null }
export type ExecutionEnglishBlock = { id: string; day_of_week: number; focus: string; minutes: number }
export type ExecutionResearchSource = { source_type: "university" | "course" | "field" | "career"; source_reference: string; title: string; provider_name: string; field_name: string }
export type ExecutionResearchItem = ExecutionResearchSource & { id: string; status: "shortlist" | "watching" | "ruled_out" }
export type ExecutionGoalOption = { id: string; position: number; title: string; provider_name: string; field_name: string; source_type: "saved_university" | "saved_course" }
export type ExecutionPathwayDecision = { leading_option_id: string | null; rationale: string }

const inputClass = "mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-100"

export function ApplicationsSpace({ applications, documents, legacyDeadlines, goalOptions, onCreateApplication, onUpdateApplication, onCreateDocument, onUpdateDocument, onDeleteDocument }: {
  applications: ExecutionApplication[]
  documents: ExecutionDocument[]
  legacyDeadlines: { id: string; title: string; due_date: string | null; status: "todo" | "done" }[]
  goalOptions: ExecutionGoalOption[]
  onCreateApplication: (input: Omit<ExecutionApplication, "id">) => Promise<boolean>
  onUpdateApplication: (id: string, patch: Partial<ExecutionApplication>) => Promise<void>
  onCreateDocument: (input: Omit<ExecutionDocument, "id">) => Promise<boolean>
  onUpdateDocument: (id: string, patch: Partial<ExecutionDocument>) => Promise<void>
  onDeleteDocument: (id: string) => Promise<void>
}) {
  const { isKo } = usePlanLocale()
  const [providerName, setProviderName] = useState("")
  const [programmeName, setProgrammeName] = useState("")
  const [deadline, setDeadline] = useState("")
  const [optionId, setOptionId] = useState("")
  const [documentLabel, setDocumentLabel] = useState("")
  const [documentApplicationId, setDocumentApplicationId] = useState("")
  const [saving, setSaving] = useState(false)
  const offers = applications.filter((item) => item.status === "offer").length
  const submitted = applications.filter((item) => item.status === "submitted").length
  const upcoming = [...applications].filter((item) => item.deadline_date).sort((a, b) => a.deadline_date!.localeCompare(b.deadline_date!))

  async function submitApplication(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!providerName.trim() && !programmeName.trim()) return
    setSaving(true)
    const option = goalOptions.find((item) => item.id === optionId)
    const success = await onCreateApplication({ goal_option_id: optionId || null, provider_name: providerName.trim() || option?.provider_name || "", programme_name: programmeName.trim() || option?.title || "", status: "preparing", deadline_date: deadline || null, offer_date: null, notes: "" })
    if (success) { setProviderName(""); setProgrammeName(""); setDeadline(""); setOptionId("") }
    setSaving(false)
  }

  async function submitDocument(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    if (!documentLabel.trim()) return
    const success = await onCreateDocument({ application_id: documentApplicationId || null, label: documentLabel.trim(), status: "todo" })
    if (success) setDocumentLabel("")
  }

  return <SpaceShell eyebrow="APPLICATIONS" title={isKo ? "지원은 감이 아니라, 마감과 서류로 관리합니다." : "Applications move when deadlines and documents are visible."} description={isKo ? "과정별 지원 상태와 서류를 한곳에서 관리하고, 오퍼가 왔을 때 비교할 근거를 남겨두세요." : "Track each application and its documents in one place so you can compare offers with context."} icon={Send} tone="blue">
    <div className="grid gap-3 sm:grid-cols-3"><Stat label={isKo ? "지원 준비 중" : "Preparing"} value={String(applications.filter((item) => item.status === "preparing" || item.status === "planning").length)} tone="blue" /><Stat label={isKo ? "제출 완료" : "Submitted"} value={String(submitted)} tone="violet" /><Stat label={isKo ? "오퍼" : "Offers"} value={String(offers)} tone="emerald" /></div>

    <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_19rem]"><Panel title={isKo ? "지원 추가" : "Add an application"} description={isKo ? "후보에서 시작하거나 직접 과정과 마감일을 적으세요." : "Start from a saved option or enter the programme and deadline directly."}><form onSubmit={submitApplication} className="grid gap-3 sm:grid-cols-2"><Field label={isKo ? "저장한 후보" : "Saved option"}><select value={optionId} onChange={(event) => { const value = event.target.value; setOptionId(value); const option = goalOptions.find((item) => item.id === value); if (option) { setProviderName(option.provider_name); setProgrammeName(option.title) } }} className={inputClass}><option value="">{isKo ? "직접 입력" : "Enter manually"}</option>{goalOptions.map((option) => <option key={option.id} value={option.id}>{option.title}</option>)}</select></Field><Field label={isKo ? "마감일" : "Deadline"}><input type="date" value={deadline} onChange={(event) => setDeadline(event.target.value)} className={inputClass} /></Field><Field label={isKo ? "교육기관" : "Provider"}><input value={providerName} onChange={(event) => setProviderName(event.target.value)} maxLength={240} placeholder="e.g. University of Melbourne" className={inputClass} /></Field><Field label={isKo ? "과정" : "Programme"}><input value={programmeName} onChange={(event) => setProgrammeName(event.target.value)} maxLength={240} placeholder="e.g. Master of Nursing" className={inputClass} /></Field><div className="sm:col-span-2"><button disabled={saving || (!providerName.trim() && !programmeName.trim())} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><Plus className="size-4" />{isKo ? "지원 추가" : "Add application"}</button></div></form></Panel>
      <Panel title={isKo ? "다가오는 마감" : "Upcoming deadlines"}>{upcoming.length ? <div className="space-y-3">{upcoming.slice(0, 4).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 last:border-0 last:pb-0"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{item.programme_name || item.provider_name || (isKo ? "지원 항목" : "Application")}</p><p className="mt-1 text-xs text-slate-500">{item.provider_name}</p></div><span className="shrink-0 text-xs font-semibold text-blue-700">{formatDate(item.deadline_date!, isKo)}</span></div>)}</div> : <EmptyLine text={isKo ? "지원 마감일을 추가하면 여기에 표시됩니다." : "Add an application deadline to see it here."} />}{legacyDeadlines.filter((item) => item.due_date && item.status === "todo").slice(0, 2).map((item) => <p key={item.id} className="mt-3 border-t border-slate-100 pt-3 text-xs leading-5 text-slate-500">{formatDate(item.due_date!, isKo)} · {item.title}</p>)}</Panel></section>

    <Panel title={isKo ? "지원 상태" : "Application status"} description={isKo ? "오퍼 상태까지 업데이트하면 의사결정 시점에 비교가 쉬워집니다." : "Keep the status current so offers are ready to compare when they arrive."}>{applications.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{applications.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{item.programme_name || item.provider_name || (isKo ? "지원 항목" : "Application")}</p><p className="mt-1 truncate text-xs text-slate-500">{item.provider_name || "—"}</p></div><StatusPill status={item.status} isKo={isKo} /></div><label className="mt-4 block text-xs font-semibold text-slate-500">{isKo ? "상태" : "Status"}<select value={item.status} onChange={(event) => void onUpdateApplication(item.id, { status: event.target.value as ExecutionApplication["status"] })} className={inputClass}>{(["planning", "preparing", "submitted", "offer", "declined"] as const).map((status) => <option key={status} value={status}>{applicationStatus(status, isKo)}</option>)}</select></label>{item.deadline_date && <p className="mt-3 text-xs text-slate-500">{isKo ? "마감" : "Deadline"} · {formatDate(item.deadline_date, isKo)}</p>}</article>)}</div> : <EmptyLine text={isKo ? "첫 지원을 추가하면 진행 상태를 여기서 추적할 수 있어요." : "Add your first application to start tracking progress."} />}</Panel>

    <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_19rem]"><Panel title={isKo ? "서류 체크리스트" : "Document checklist"} description={isKo ? "성적표, 여권, 추천서처럼 준비해야 할 문서를 하나씩 완료하세요." : "Keep transcripts, passports and references visible until they are ready."}>{documents.length ? <div className="space-y-2">{documents.map((item) => <div key={item.id} className="group flex items-center gap-3 rounded-xl px-2 py-2 hover:bg-slate-50"><button type="button" onClick={() => void onUpdateDocument(item.id, { status: nextDocumentStatus(item.status) })} aria-label={isKo ? "서류 상태 변경" : "Change document status"}>{item.status === "submitted" ? <CircleCheck className="size-5 text-emerald-600" /> : item.status === "ready" ? <Check className="size-5 rounded-full bg-blue-600 p-0.5 text-white" /> : <Circle className="size-5 text-slate-300" />}</button><div className="min-w-0 flex-1"><p className={cn("text-sm font-medium", item.status === "submitted" ? "text-slate-400 line-through" : "text-slate-800")}>{item.label}</p><p className="mt-0.5 text-xs text-slate-500">{documentStatus(item.status, isKo)}</p></div><button type="button" onClick={() => void onDeleteDocument(item.id)} className="opacity-0 transition group-hover:opacity-100 text-slate-300 hover:text-red-600" aria-label={isKo ? `${item.label} 삭제` : `Delete ${item.label}`}><Trash2 className="size-4" /></button></div>)}</div> : <EmptyLine text={isKo ? "필요한 서류를 추가해 체크리스트를 시작하세요." : "Add the documents you need to start your checklist."} />}</Panel>
      <Panel title={isKo ? "서류 추가" : "Add a document"}><form onSubmit={submitDocument} className="space-y-3"><Field label={isKo ? "연결할 지원" : "Application"}><select value={documentApplicationId} onChange={(event) => setDocumentApplicationId(event.target.value)} className={inputClass}><option value="">{isKo ? "공통 서류" : "Shared document"}</option>{applications.map((item) => <option key={item.id} value={item.id}>{item.programme_name || item.provider_name}</option>)}</select></Field><Field label={isKo ? "서류 이름" : "Document name"}><input value={documentLabel} onChange={(event) => setDocumentLabel(event.target.value)} maxLength={180} placeholder={isKo ? "예: 학부 성적표" : "e.g. Academic transcript"} className={inputClass} /></Field><button disabled={!documentLabel.trim()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700 hover:border-blue-300 hover:text-blue-700 disabled:opacity-50"><FileCheck2 className="size-4" />{isKo ? "체크리스트에 추가" : "Add to checklist"}</button></form></Panel></section>
  </SpaceShell>
}

export function MoneyRunwaySpace({ budget, scenario, onSaveBudget, onSaveScenario }: { budget: ExecutionBudget; scenario: ExecutionMoneyScenario; onSaveBudget: (next: ExecutionBudget) => Promise<boolean>; onSaveScenario: (next: ExecutionMoneyScenario) => Promise<boolean> }) {
  const { isKo, locale } = usePlanLocale()
  const [draft, setDraft] = useState(budget)
  const [scenarioDraft, setScenarioDraft] = useState(scenario)
  const [saving, setSaving] = useState(false)
  useEffect(() => setDraft(budget), [budget])
  useEffect(() => setScenarioDraft(scenario), [scenario])
  const grossTarget = draft.target_amount ?? 0
  const basicNeed = Math.max(grossTarget - scenarioDraft.scholarship_amount - draft.current_savings, 0)
  const conservativeNeed = Math.max(grossTarget * (1 + scenarioDraft.conservative_cost_lift / 100) - scenarioDraft.scholarship_amount - draft.current_savings, 0)
  const monthlyForBasic = draft.monthly_saving > 0 ? Math.ceil(basicNeed / draft.monthly_saving) : null
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); const [budgetSaved, scenarioSaved] = await Promise.all([onSaveBudget(draft), onSaveScenario(scenarioDraft)]); setSaving(false); return budgetSaved && scenarioSaved }

  return <SpaceShell eyebrow="MONEY RUNWAY" title={isKo ? "비용은 한 숫자가 아니라, 감당 가능한 시나리오입니다." : "Funding is not one number. It is a scenario you can sustain."} description={isKo ? "총 필요 자금에서 장학금과 현재 저축을 빼고, 보수적 비용 상승까지 고려해 런웨이를 확인하세요." : "Start with your total need, subtract scholarships and savings, then test a more conservative cost scenario."} icon={Banknote} tone="emerald">
    <div className="grid gap-4 lg:grid-cols-2"><ScenarioCard title={isKo ? "기본 시나리오" : "Base scenario"} total={basicNeed} currency={draft.currency} locale={locale} detail={monthlyForBasic ? (isKo ? `현재 월 저축으로 약 ${monthlyForBasic}개월` : `About ${monthlyForBasic} months at your current saving rate`) : (isKo ? "월 저축 계획을 입력해 보세요." : "Add a monthly saving plan.")} tone="emerald" /><ScenarioCard title={isKo ? "보수적 시나리오" : "Conservative scenario"} total={conservativeNeed} currency={draft.currency} locale={locale} detail={isKo ? `총 비용이 ${scenarioDraft.conservative_cost_lift}% 늘어난 경우` : `With a ${scenarioDraft.conservative_cost_lift}% total-cost lift`} tone="amber" /></div>
    <Panel title={isKo ? "런웨이 설정" : "Set your runway"} description={isKo ? "숫자는 추정값이어도 됩니다. 기준을 기록하면 다음 판단이 훨씬 빨라집니다." : "Estimates are useful. Once the baseline is written down, the next decision becomes faster."}><form onSubmit={save} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label={isKo ? "통화" : "Currency"}><input value={draft.currency} onChange={(event) => setDraft({ ...draft, currency: event.target.value.toUpperCase().slice(0, 3) })} maxLength={3} className={inputClass} /></Field><Field label={isKo ? "총 필요 자금" : "Total needed"}><NumberInput value={draft.target_amount} onChange={(value) => setDraft({ ...draft, target_amount: value })} placeholder="e.g. 45000" /></Field><Field label={isKo ? "현재 저축" : "Saved now"}><NumberInput value={draft.current_savings} onChange={(value) => setDraft({ ...draft, current_savings: value ?? 0 })} placeholder="0" /></Field><Field label={isKo ? "월 저축" : "Monthly saving"}><NumberInput value={draft.monthly_saving} onChange={(value) => setDraft({ ...draft, monthly_saving: value ?? 0 })} placeholder="0" /></Field><Field label={isKo ? "장학금 예상액" : "Expected scholarship"}><NumberInput value={scenarioDraft.scholarship_amount} onChange={(value) => setScenarioDraft({ ...scenarioDraft, scholarship_amount: value ?? 0 })} placeholder="0" /></Field><Field label={isKo ? "보수적 비용 상승률" : "Conservative cost lift"}><div className="relative"><NumberInput value={scenarioDraft.conservative_cost_lift} onChange={(value) => setScenarioDraft({ ...scenarioDraft, conservative_cost_lift: Math.min(50, value ?? 0) })} placeholder="15" /><span className="absolute right-3 top-[2.15rem] text-xs font-semibold text-slate-400">%</span></div></Field><Field label={isKo ? "목표일" : "Target date"}><input type="date" value={draft.target_date ?? ""} onChange={(event) => setDraft({ ...draft, target_date: event.target.value || null })} className={inputClass} /></Field><div className="flex items-end"><button disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-600 px-4 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50"><Landmark className="size-4" />{isKo ? "런웨이 저장" : "Save runway"}</button></div></form></Panel>
  </SpaceShell>
}

export function EnglishTargetSpace({ language, blocks, onSaveLanguage, onSaveBlock, onDeleteBlock }: { language: ExecutionLanguage; blocks: ExecutionEnglishBlock[]; onSaveLanguage: (next: ExecutionLanguage) => Promise<boolean>; onSaveBlock: (next: Omit<ExecutionEnglishBlock, "id">) => Promise<boolean>; onDeleteBlock: (id: string) => Promise<void> }) {
  const { isKo } = usePlanLocale()
  const [draft, setDraft] = useState(language)
  const [day, setDay] = useState(1)
  const [focus, setFocus] = useState("")
  const [minutes, setMinutes] = useState(60)
  useEffect(() => setDraft(language), [language])
  const gap = draft.current_score != null && draft.target_score != null ? Math.max(draft.target_score - draft.current_score, 0) : null
  const weeklyMinutes = blocks.reduce((sum, block) => sum + block.minutes, 0)
  async function saveBlock(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!focus.trim()) return; const success = await onSaveBlock({ day_of_week: day, focus: focus.trim(), minutes }); if (success) setFocus("") }
  return <SpaceShell eyebrow="ENGLISH TARGET" title={isKo ? "점수 목표를 주간 행동으로 바꾸세요." : "Turn the score target into a weekly rhythm."} description={isKo ? "현재 점수와 목표, 시험일을 정하고 실제 학습 시간을 요일별로 배치하세요." : "Set your current score, target and test date, then make the study time real by assigning it to days."} icon={Languages} tone="violet">
    <div className="grid gap-3 sm:grid-cols-3"><Stat label={isKo ? "점수 차이" : "Score gap"} value={gap == null ? "—" : gap === 0 ? (isKo ? "달성" : "Met") : `+${gap.toFixed(1)}`} tone="violet" /><Stat label={isKo ? "시험일" : "Test date"} value={draft.test_date ? formatDate(draft.test_date, isKo) : "—"} tone="blue" /><Stat label={isKo ? "주간 학습" : "Weekly study"} value={weeklyMinutes ? `${Math.round(weeklyMinutes / 60 * 10) / 10}h` : "—"} tone="emerald" /></div>
    <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><Panel title={isKo ? "영어 목표" : "English target"}><form onSubmit={(event) => { event.preventDefault(); void onSaveLanguage(draft) }} className="grid gap-3 sm:grid-cols-2"><Field label={isKo ? "시험" : "Exam"}><input value={draft.exam_name} onChange={(event) => setDraft({ ...draft, exam_name: event.target.value.slice(0, 80) })} className={inputClass} /></Field><Field label={isKo ? "시험일" : "Test date"}><input type="date" value={draft.test_date ?? ""} onChange={(event) => setDraft({ ...draft, test_date: event.target.value || null })} className={inputClass} /></Field><Field label={isKo ? "현재 점수" : "Current score"}><NumberInput value={draft.current_score} onChange={(value) => setDraft({ ...draft, current_score: value })} placeholder="e.g. 6.0" /></Field><Field label={isKo ? "목표 점수" : "Target score"}><NumberInput value={draft.target_score} onChange={(value) => setDraft({ ...draft, target_score: value })} placeholder="e.g. 7.0" /></Field><Field label={isKo ? "주당 목표 시간" : "Target hours / week"}><NumberInput value={draft.weekly_hours} onChange={(value) => setDraft({ ...draft, weekly_hours: value })} placeholder="e.g. 8" /></Field><div className="flex items-end"><button className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-600 px-4 text-sm font-semibold text-white hover:bg-violet-700"><Languages className="size-4" />{isKo ? "목표 저장" : "Save target"}</button></div></form></Panel>
      <Panel title={isKo ? "다음 판단" : "Next decision"}>{gap == null ? <EmptyLine text={isKo ? "현재 점수와 목표 점수를 입력하면 필요한 준비 정도를 볼 수 있어요." : "Add both scores to see how much preparation you need."} /> : gap === 0 ? <p className="text-sm leading-6 text-emerald-700">{isKo ? "현재 목표 점수에 도달했습니다. 유효기간과 과정별 최소 점수를 확인해 보세요." : "You are at your target. Check score validity and course-specific requirements next."}</p> : <p className="text-sm leading-6 text-violet-800">{isKo ? `${draft.exam_name || "IELTS"}에서 +${gap.toFixed(1)}이 필요합니다. 시험일에서 거꾸로 계산해 주간 학습 블록을 채우세요.` : `You need +${gap.toFixed(1)} in ${draft.exam_name || "IELTS"}. Work backwards from the test date and fill the weekly blocks.`}</p>}</Panel></section>
    <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_19rem]"><Panel title={isKo ? "주간 학습 계획" : "Weekly study plan"} description={isKo ? "각 요일에 한 가지 학습 초점을 둬서 실행 가능한 계획으로 만드세요." : "Give each day one focus so the plan is actually usable."}>{blocks.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[...blocks].sort((a, b) => a.day_of_week - b.day_of_week).map((block) => <article key={block.id} className="group rounded-2xl bg-violet-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-violet-500">{dayLabel(block.day_of_week, isKo)}</p><p className="mt-2 text-sm font-semibold text-violet-950">{block.focus}</p><p className="mt-1 text-xs text-violet-700">{block.minutes} min</p></div><button type="button" onClick={() => void onDeleteBlock(block.id)} className="opacity-0 transition group-hover:opacity-100 text-violet-300 hover:text-red-600" aria-label={isKo ? `${block.focus} 삭제` : `Delete ${block.focus}`}><Trash2 className="size-4" /></button></div></article>)}</div> : <EmptyLine text={isKo ? "첫 학습 블록을 추가해 계획을 시작하세요." : "Add your first study block to start the plan."} />}</Panel>
      <Panel title={isKo ? "학습 블록 추가" : "Add a study block"}><form onSubmit={saveBlock} className="space-y-3"><Field label={isKo ? "요일" : "Day"}><select value={day} onChange={(event) => setDay(Number(event.target.value))} className={inputClass}>{[0, 1, 2, 3, 4, 5, 6].map((value) => <option key={value} value={value}>{dayLabel(value, isKo)}</option>)}</select></Field><Field label={isKo ? "학습 초점" : "Focus"}><input value={focus} onChange={(event) => setFocus(event.target.value)} maxLength={180} placeholder={isKo ? "예: Writing task 2" : "e.g. Writing task 2"} className={inputClass} /></Field><Field label={isKo ? "시간(분)" : "Minutes"}><NumberInput value={minutes} onChange={(value) => setMinutes(Math.max(5, Math.min(600, value ?? 60)))} placeholder="60" /></Field><button disabled={!focus.trim()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-violet-200 px-4 text-sm font-semibold text-violet-700 hover:bg-violet-50 disabled:opacity-50"><Plus className="size-4" />{isKo ? "주간 계획에 추가" : "Add to weekly plan"}</button></form></Panel></section>
  </SpaceShell>
}

export function ResearchDeskSpace({ sources, researchItems, onSetStatus }: { sources: ExecutionResearchSource[]; researchItems: ExecutionResearchItem[]; onSetStatus: (source: ExecutionResearchSource, status: ExecutionResearchItem["status"]) => Promise<void> }) {
  const { isKo } = usePlanLocale()
  const statusByKey = new Map(researchItems.map((item) => [`${item.source_type}:${item.source_reference}`, item.status]))
  const grouped = (status: ExecutionResearchItem["status"]) => sources.filter((source) => (statusByKey.get(`${source.source_type}:${source.source_reference}`) ?? "watching") === status)
  const columns: { status: ExecutionResearchItem["status"]; title: string; note: string; tone: string }[] = [{ status: "shortlist", title: isKo ? "Shortlist" : "Shortlist", note: isKo ? "더 깊게 비교할 후보" : "Compare these in depth", tone: "border-emerald-200 bg-emerald-50/60" }, { status: "watching", title: isKo ? "Watching" : "Watching", note: isKo ? "정보를 더 확인할 후보" : "Need more information", tone: "border-blue-200 bg-blue-50/60" }, { status: "ruled_out", title: isKo ? "Ruled out" : "Ruled out", note: isKo ? "현재 조건에서는 제외" : "Not right for now", tone: "border-slate-200 bg-slate-50" }]
  return <SpaceShell eyebrow="RESEARCH DESK" title={isKo ? "후보를 저장하는 것에서 끝내지 말고, 판단 가능한 상태로 만드세요." : "Do not stop at saving options. Bring them to a decision-ready state."} description={isKo ? "저장한 전공·대학·과정을 Shortlist, Watching, Ruled out으로 나누면 다음 비교가 훨씬 선명해집니다." : "Sort saved fields, universities and courses into Shortlist, Watching and Ruled out to make your next comparison clearer."} icon={BookOpenCheck} tone="blue">
    {sources.length ? <div className="grid gap-5 xl:grid-cols-3">{columns.map((column) => <section key={column.status} className={cn("min-h-80 rounded-[1.5rem] border p-4", column.tone)}><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold text-slate-950">{column.title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{column.note}</p></div><span className="rounded-full bg-white/80 px-2.5 py-1 text-xs font-semibold text-slate-600">{grouped(column.status).length}</span></div><div className="mt-4 space-y-3">{grouped(column.status).map((source) => <article key={`${source.source_type}:${source.source_reference}`} className="rounded-2xl border border-white/80 bg-white p-4 shadow-sm"><p className="text-sm font-semibold text-slate-900">{source.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{source.field_name || source.provider_name || source.source_type}</p><select value={column.status} onChange={(event) => void onSetStatus(source, event.target.value as ExecutionResearchItem["status"])} className="mt-4 h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-2 text-xs font-semibold text-slate-700 outline-none focus:border-blue-500"><option value="shortlist">Shortlist</option><option value="watching">Watching</option><option value="ruled_out">Ruled out</option></select></article>)}</div></section>)}</div> : <Panel title={isKo ? "저장한 후보가 없습니다" : "No saved options yet"}><EmptyLine text={isKo ? "전공 탐색과 학교 비교에서 마음에 드는 항목을 저장하면 리서치 데스크에서 분류할 수 있어요." : "Save options while you explore fields and compare study providers, then classify them here."} /></Panel>}
  </SpaceShell>
}

export function MyPathwaySpace({ goalTitle, studyTitle, options, decision, evidenceCount, onSaveDecision }: { goalTitle: string; studyTitle: string; options: ExecutionGoalOption[]; decision: ExecutionPathwayDecision; evidenceCount: number; onSaveDecision: (next: ExecutionPathwayDecision) => Promise<boolean> }) {
  const { isKo } = usePlanLocale()
  const [leadingId, setLeadingId] = useState(decision.leading_option_id ?? options[0]?.id ?? "")
  const [rationale, setRationale] = useState(decision.rationale)
  const [saving, setSaving] = useState(false)
  useEffect(() => { setLeadingId(decision.leading_option_id ?? options[0]?.id ?? ""); setRationale(decision.rationale) }, [decision, options])
  const leader = options.find((option) => option.id === leadingId) ?? options[0] ?? null
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); await onSaveDecision({ leading_option_id: leadingId || null, rationale: rationale.trim() }); setSaving(false) }
  return <SpaceShell eyebrow="MY PATHWAY" title={isKo ? "세 개의 경로를 같은 기준에서 보고, 지금의 1순위를 정하세요." : "Compare up to three routes on the same terms and name the current first choice."} description={isKo ? "1순위는 영구적인 약속이 아닙니다. 현재 정보에서 가장 합리적인 선택과 그 근거를 기록하는 자리입니다." : "A first choice is not permanent. It is the most sensible option with the information you have now, plus the reason why."} icon={Target} tone="blue">
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_19rem]"><Panel title={isKo ? "현재 목표" : "Current direction"}><div className="flex flex-wrap gap-2"><Tag icon={GraduationCap} label={studyTitle || (isKo ? "전공 방향 미정" : "Study direction to confirm")} /><Tag icon={Target} label={goalTitle || (isKo ? "직업 목표 미정" : "Career direction to confirm")} /><Tag icon={ClipboardCheck} label={isKo ? `공식 근거 ${evidenceCount}개` : `${evidenceCount} evidence links`} /></div></Panel><Panel title={isKo ? "현재 1순위" : "Current first choice"}>{leader ? <div><p className="text-lg font-semibold tracking-tight text-slate-950">{leader.title}</p><p className="mt-1 text-sm text-slate-500">{leader.field_name || leader.provider_name || "—"}</p></div> : <EmptyLine text={isKo ? "후보를 최대 3개까지 선택하면 비교할 수 있어요." : "Choose up to three options to compare them here."} />}</Panel></div>
    <Panel title={isKo ? "경로 비교" : "Route comparison"} description={isKo ? "현재 저장한 후보만 보여줍니다. 확인하지 않은 비용·입학 조건·결과는 리서치 데스크에서 채워주세요." : "This uses your saved options only. Confirm costs, requirements and outcomes in the Research desk before making a final decision."}>{options.length ? <div className="overflow-x-auto"><table className="min-w-[640px] w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs font-semibold uppercase tracking-[.1em] text-slate-400"><th className="px-3 py-3">{isKo ? "후보" : "Route"}</th><th className="px-3 py-3">{isKo ? "교육기관" : "Provider"}</th><th className="px-3 py-3">{isKo ? "학업 방향" : "Study focus"}</th><th className="px-3 py-3">{isKo ? "현재 판단" : "Current decision"}</th></tr></thead><tbody>{options.map((option, index) => <tr key={option.id} className="border-b border-slate-100 last:border-0"><td className="px-3 py-4 font-semibold text-slate-900">{option.title}</td><td className="px-3 py-4 text-slate-600">{option.provider_name || "—"}</td><td className="px-3 py-4 text-slate-600">{option.field_name || "—"}</td><td className="px-3 py-4"><label className="inline-flex items-center gap-2 text-sm font-medium text-slate-700"><input type="radio" name="leading-pathway" checked={leadingId === option.id} onChange={() => setLeadingId(option.id)} className="size-4 accent-blue-600" />{leadingId === option.id ? (isKo ? "1순위" : "First choice") : `${isKo ? "후보" : "Option"} ${index + 1}`}</label></td></tr>)}</tbody></table></div> : <EmptyLine text={isKo ? "저장한 대학 또는 과정을 목표 설정에서 후보로 가져오세요." : "Bring saved universities or courses into your shortlist during goal setup."} />}</Panel>
    <Panel title={isKo ? "왜 이 경로가 1순위인가요?" : "Why is this the current first choice?"} description={isKo ? "비용, 취업 가능성, 입학 조건, 도시 선호 등 지금의 판단 근거를 남기세요." : "Write the reasons that matter now: cost, employment outlook, entry requirements or city preference."}><form onSubmit={save}><textarea value={rationale} onChange={(event) => setRationale(event.target.value.slice(0, 1200))} rows={5} placeholder={isKo ? "예: Option B는 총 비용이 더 낮고, 목표 직업과의 연결이 가장 명확하다." : "Example: Option B has a lower total cost and the clearest connection to my target career."} className="w-full resize-y rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm leading-6 text-slate-800 outline-none focus:border-blue-500 focus:bg-white focus:ring-4 focus:ring-blue-100" /><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-slate-400">{rationale.length}/1200</p><button disabled={saving || !leadingId} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><Check className="size-4" />{isKo ? "1순위 판단 저장" : "Save first-choice rationale"}</button></div></form></Panel>
  </SpaceShell>
}

function SpaceShell({ eyebrow, title, description, icon: Icon, tone, children }: { eyebrow: string; title: string; description: string; icon: typeof Target; tone: "blue" | "emerald" | "violet"; children: ReactNode }) {
  const toneClasses = { blue: "bg-blue-600", emerald: "bg-emerald-600", violet: "bg-violet-600" }
  return <section className="mx-auto max-w-6xl space-y-6 px-6 py-8 sm:px-10 sm:py-10"><header className="rounded-[2rem] border border-white/70 bg-white/80 p-6 shadow-[0_18px_45px_rgba(15,23,42,.07)] backdrop-blur sm:p-8"><div className="flex items-start gap-4"><span className={cn("grid size-12 shrink-0 place-items-center rounded-2xl text-white shadow-lg", toneClasses[tone])}><Icon className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-slate-400">{eyebrow}</p><h1 className="mt-2 max-w-3xl text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{title}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{description}</p></div></div></header>{children}</section>
}

function Panel({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <section className="rounded-[1.75rem] border border-slate-200 bg-white p-5 shadow-[0_10px_28px_rgba(15,23,42,.045)] sm:p-6"><h2 className="text-lg font-semibold tracking-tight text-slate-950">{title}</h2>{description && <p className="mt-1 text-sm leading-6 text-slate-500">{description}</p>}<div className="mt-5">{children}</div></section> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block text-xs font-semibold text-slate-500">{label}{children}</label> }
function NumberInput({ value, onChange, placeholder }: { value: number | null; onChange: (value: number | null) => void; placeholder: string }) { return <input inputMode="decimal" value={value ?? ""} onChange={(event) => { const raw = event.target.value.replace(/,/g, ""); onChange(raw === "" ? null : Number.isFinite(Number(raw)) && Number(raw) >= 0 ? Number(raw) : value) }} placeholder={placeholder} className={inputClass} /> }
function EmptyLine({ text }: { text: string }) { return <p className="rounded-2xl bg-slate-50 px-4 py-5 text-sm leading-6 text-slate-500">{text}</p> }
function Stat({ label, value, tone }: { label: string; value: string; tone: "blue" | "violet" | "emerald" }) { const styles = { blue: "border-blue-100 bg-blue-50 text-blue-950", violet: "border-violet-100 bg-violet-50 text-violet-950", emerald: "border-emerald-100 bg-emerald-50 text-emerald-950" }; return <article className={cn("rounded-2xl border p-4", styles[tone])}><p className="text-xs font-semibold uppercase tracking-[.12em] opacity-60">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight">{value}</p></article> }
function ScenarioCard({ title, total, currency, locale, detail, tone }: { title: string; total: number; currency: string; locale: string; detail: string; tone: "emerald" | "amber" }) { return <article className={cn("rounded-[1.75rem] border p-6", tone === "emerald" ? "border-emerald-100 bg-emerald-50" : "border-amber-100 bg-amber-50")}><p className="text-sm font-semibold text-slate-700">{title}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{formatMoney(total, currency, locale)}</p><p className="mt-2 text-sm leading-6 text-slate-600">{detail}</p></article> }
function Tag({ icon: Icon, label }: { icon: typeof Target; label: string }) { return <span className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-3 py-2 text-sm font-medium text-slate-700"><Icon className="size-4 text-blue-600" />{label}</span> }
function StatusPill({ status, isKo }: { status: ExecutionApplication["status"]; isKo: boolean }) { const styles = { planning: "bg-slate-100 text-slate-600", preparing: "bg-blue-100 text-blue-700", submitted: "bg-violet-100 text-violet-700", offer: "bg-emerald-100 text-emerald-700", declined: "bg-rose-100 text-rose-700" }; return <span className={cn("rounded-full px-2.5 py-1 text-xs font-semibold", styles[status])}>{applicationStatus(status, isKo)}</span> }
function applicationStatus(status: ExecutionApplication["status"], isKo: boolean) { const ko = { planning: "계획", preparing: "준비 중", submitted: "제출 완료", offer: "오퍼", declined: "불합격" }; const en = { planning: "Planning", preparing: "Preparing", submitted: "Submitted", offer: "Offer", declined: "Declined" }; return (isKo ? ko : en)[status] }
function documentStatus(status: ExecutionDocument["status"], isKo: boolean) { return isKo ? ({ todo: "준비 전", ready: "준비 완료", submitted: "제출 완료" }[status]) : ({ todo: "To prepare", ready: "Ready", submitted: "Submitted" }[status]) }
function nextDocumentStatus(status: ExecutionDocument["status"]): ExecutionDocument["status"] { return status === "todo" ? "ready" : status === "ready" ? "submitted" : "todo" }
function dayLabel(day: number, isKo: boolean) { return (isKo ? ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"] : ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"])[day] }
function formatDate(value: string, isKo: boolean) { return new Intl.DateTimeFormat(isKo ? "ko-KR" : "en-AU", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value.slice(0, 10)}T00:00:00`)) }
function formatMoney(value: number, currency: string, locale: string) { try { return new Intl.NumberFormat(locale === "ko" ? "ko-KR" : "en-AU", { style: "currency", currency: currency || "AUD", maximumFractionDigits: 0 }).format(value) } catch { return `${currency || "AUD"} ${Math.round(value).toLocaleString()}` } }
function usePlanLocale() { const locale = useRouteLocale(); return { locale, isKo: locale === "ko" } }
