/**
 * Loads the reviewed Home Affairs CSOL snapshot into the historical visa
 * status table. The source snapshot is generated by
 * `scripts/import-au-csol-priority-occupations.py`; do not substitute a
 * scraped search-result page for that source.
 *
 * Preview: npx tsx --env-file=.env.local scripts/import-au-visa-status.ts
 * Apply:   npx tsx --env-file=.env.local scripts/import-au-visa-status.ts --apply
 */
import { readFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { createClient } from "@supabase/supabase-js"

type CsolSnapshot = {
  source: { csolUrl: string; retrievedAt: string; csolContentHash: string }
  occupations: Array<{ oscaCode: string; anzscoV13Codes: string[] }>
}

const apply = process.argv.includes("--apply")
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const snapshotPath = path.join(root, "src/data/au-csol-priority-occupations.json")

async function main() {
  const snapshot = JSON.parse(await readFile(snapshotPath, "utf8")) as CsolSnapshot
  const rows = snapshot.occupations.flatMap((occupation) => {
    const anzscoCodes = occupation.anzscoV13Codes.length ? occupation.anzscoV13Codes : [null]
    return anzscoCodes.map((anzscoCode) => ({
      osca_code: occupation.oscaCode,
      anzsco_v13_code: anzscoCode,
      list_name: "Core Skills Occupation List (CSOL)",
      visa_stream: "Check current Home Affairs visa instrument",
      status: "eligible",
      source_url: snapshot.source.csolUrl,
      source_content_hash: snapshot.source.csolContentHash,
      retrieved_at: snapshot.source.retrievedAt,
      reviewer_note: "Loaded from the reviewed official Home Affairs CSOL snapshot",
    }))
  })
  console.log(`${apply ? "IMPORT" : "CHECK "} ${rows.length} CSOL occupation status rows from ${snapshot.source.retrievedAt}`)
  if (!apply) return

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY")
  const supabase = createClient(url, key, { auth: { persistSession: false } })
  const { error: removeError } = await supabase
    .from("visa_occupation_status_au")
    .delete()
    .eq("list_name", "Core Skills Occupation List (CSOL)")
  if (removeError) throw removeError
  for (let start = 0; start < rows.length; start += 250) {
    const { error } = await supabase.from("visa_occupation_status_au").insert(rows.slice(start, start + 250))
    if (error) throw error
  }
  console.log(`Imported ${rows.length} current CSOL rows.`)
}

void main().catch((error) => {
  console.error("[au-visa-status] failed:", error)
  process.exitCode = 1
})
