"use client"

import { useEffect, useRef, useState, type ReactNode } from "react"
import { ChevronDown, Plus, X } from "lucide-react"
import { useRouter, useSearchParams } from "next/navigation"
import { localizePath } from "@/lib/i18n/config"
import { useRouteLocale } from "@/lib/i18n/locale-provider"
import { formatProgramCompareValue, type ProgramCompareItem } from "@/lib/data-foundation/program-compare-contract"

type Props = { availablePrograms: readonly ProgramCompareItem[] }
type ProgramComparisonRow = { key:string; label:string; values:readonly ReactNode[] }
type ProgramComparisonSection = { title:string; rows:readonly ProgramComparisonRow[] }

function normalizeIds(raw:string|null,available:readonly ProgramCompareItem[]){const allowed=new Set(available.map((program)=>program.productProgramId));const result:string[]=[];for(const value of(raw??"").split(",")){const id=value.trim();if(!id||!allowed.has(id)||result.includes(id))continue;result.push(id);if(result.length===3)break}return result}
function hrefFor(ids:readonly string[]){const items=ids.length?`&items=${encodeURIComponent(ids.join(","))}`:"";return `/compare?type=program&country=AU&field=nursing${items}`}
function displayProgramName(program:ProgramCompareItem,ko:boolean){return program.programme?.name??(ko?"과정 정보 없음":"Programme data unavailable")}
function displayInstitution(program:ProgramCompareItem,ko:boolean){return program.institution?.name??(ko?"교육기관 정보 없음":"Institution data unavailable")}
function displayLocation(program:ProgramCompareItem){const location=program.locations[0];if(!location)return"—";return[location.campusName,location.cityName,location.regionName].filter(Boolean).join(", ")||"—"}
function localizeValue(value:ReactNode,ko:boolean):ReactNode{if(!ko||typeof value!=="string")return value;if(value==="Australia")return"오스트레일리아";if(value==="Available")return"확인됨";if(value==="Not confirmed")return"미확인";if(value==="Verified")return"검증 완료";return value.replace(/\b(years?)\b/gi,"년").replace(/\b(months?)\b/gi,"개월")}

export default function ProgramsCompareMatrix({availablePrograms}:Props){
  const router=useRouter();const searchParams=useSearchParams();const locale=useRouteLocale();const ko=locale==="ko"
  const selectedIds=normalizeIds(searchParams.get("items"),availablePrograms)
  const selectedPrograms=selectedIds.map((id)=>availablePrograms.find((program)=>program.productProgramId===id)).filter((program):program is ProgramCompareItem=>Boolean(program))
  const[thirdOpen,setThirdOpen]=useState(selectedIds.length>=3);const[chooserSlot,setChooserSlot]=useState<number|null>(null);const triggerRefs=useRef<Array<HTMLButtonElement|null>>([])
  useEffect(()=>{if(selectedIds.length>=3)setThirdOpen(true);if(selectedIds.length<2)setThirdOpen(false)},[selectedIds.length])
  const slots=Array.from({length:selectedIds.length>=3||thirdOpen?3:2},(_,index)=>index);const showAdd=selectedIds.length===2&&!thirdOpen;const canCompare=selectedPrograms.length>=2;const sections=comparisonSections(selectedPrograms,ko)
  function update(ids:readonly string[]){router.replace(localizePath(hrefFor(ids),locale),{scroll:false})}
  function closeChooser(){const slot=chooserSlot;setChooserSlot(null);if(slot!==null)window.requestAnimationFrame(()=>triggerRefs.current[slot]?.focus())}
  function choose(slot:number,id:string){const next=[...selectedIds];if(slot<next.length)next[slot]=id;else next.push(id);update(next.filter((value,index)=>next.indexOf(value)===index).slice(0,3));setChooserSlot(null);window.requestAnimationFrame(()=>triggerRefs.current[slot]?.focus())}
  function remove(slot:number){update(selectedIds.filter((_,index)=>index!==slot));if(selectedIds.length<=3)setThirdOpen(false)}
  return <section className="mt-1" aria-label={ko?"과정 비교":"Program comparison"}>
    {!canCompare?<p className="mb-3 text-sm font-medium text-[#5f5d57]" role="status">{selectedPrograms.length===1?(ko?"비교할 과정을 하나 더 선택하세요.":"Select one more program to compare."):(ko?"비교를 시작하려면 과정 두 개를 선택하세요.":"Select two programs to start comparing.")}</p>:null}
    <DesktopMatrix ko={ko} slots={slots} selectedPrograms={selectedPrograms} chooserSlot={chooserSlot} showAdd={showAdd} sections={sections} triggerRefs={triggerRefs} onOpen={setChooserSlot} onRemove={remove} onAdd={()=>setThirdOpen(true)} onCancelThird={()=>{setThirdOpen(false);setChooserSlot(null)}}/>
    <MobileMatrix ko={ko} slots={slots} selectedPrograms={selectedPrograms} chooserSlot={chooserSlot} showAdd={showAdd} sections={sections} triggerRefs={triggerRefs} onOpen={setChooserSlot} onRemove={remove} onAdd={()=>setThirdOpen(true)} onCancelThird={()=>{setThirdOpen(false);setChooserSlot(null)}}/>
    {chooserSlot!==null?<ProgramChooser ko={ko} slot={chooserSlot} selectedIds={selectedIds} programs={availablePrograms} onChoose={choose} onClose={closeChooser}/>:null}
    <p className="mt-5 text-xs leading-5 text-[#77746e]">{ko?"검증된 표준 필드만 표시합니다. 확인되지 않은 값은 —로 표시됩니다.":"Verified canonical fields only. Missing values are shown as —."}</p>
  </section>
}

function comparisonSections(programs:readonly ProgramCompareItem[],ko:boolean):readonly ProgramComparisonSection[]{
  const source=(program:ProgramCompareItem)=>program.sources[0]?<a key={program.productProgramId} className="font-semibold text-blue-700 underline-offset-2 hover:underline" href={program.sources[0].url} target="_blank" rel="noreferrer">{program.sources[0].title}</a>:"—"
  const value=(input:unknown)=>localizeValue(formatProgramCompareValue(input as never,"—"),ko)
  return[
    {title:ko?"핵심 지표":"Key metrics",rows:[
      {key:"qualification",label:ko?"학위·자격":"Qualification",values:programs.map((program)=>value(program.qualification))},
      {key:"duration",label:ko?"기간":"Duration",values:programs.map((program)=>value(program.duration))},
      {key:"tuition",label:ko?"국제학생 학비":"International tuition",values:programs.map((program)=>value(program.tuition))},
      {key:"availability",label:ko?"국제학생 관련 상태":"International availability",values:programs.map((program)=>value(program.internationalAvailability))},
    ]},
    {title:ko?"학업·지역":"Study & location",rows:[
      {key:"institution",label:ko?"교육기관":"Institution",values:programs.map((program)=>displayInstitution(program,ko))},
      {key:"program",label:ko?"과정":"Programme",values:programs.map((program)=>displayProgramName(program,ko))},
      {key:"country",label:ko?"국가":"Country",values:programs.map((program)=>localizeValue(program.countryDisplayName??"—",ko))},
      {key:"location",label:ko?"캠퍼스·도시·지역":"Campus / city / region",values:programs.map(displayLocation)},
    ]},
    {title:ko?"기타 정보":"Other details",rows:[
      {key:"reviewed",label:ko?"검토일":"Reviewed",values:programs.map((program)=>program.reviewedAt??"—")},
      {key:"source",label:ko?"공식 출처":"Official source",values:programs.map(source)},
    ]},
  ]
}

type MatrixProps={ko:boolean;slots:readonly number[];selectedPrograms:readonly ProgramCompareItem[];chooserSlot:number|null;showAdd:boolean;sections:readonly ProgramComparisonSection[];triggerRefs:React.MutableRefObject<Array<HTMLButtonElement|null>>;onOpen:(slot:number)=>void;onRemove:(slot:number)=>void;onAdd:()=>void;onCancelThird:()=>void}
function DesktopMatrix({ko,slots,selectedPrograms,chooserSlot,showAdd,sections,triggerRefs,onOpen,onRemove,onAdd,onCancelThird}:MatrixProps){return <div className="hidden border-y border-[#e7e6e3] bg-white md:block"><table className="w-full table-fixed border-collapse text-left text-sm"><thead><tr><th scope="col" className="sticky top-14 z-20 w-36 border-b border-[#e7e6e3] bg-white/95 px-4 py-3 backdrop-blur-md xl:w-44"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold uppercase tracking-[0.08em] text-[#77746e]">{ko?"비교":"Compare"}</span>{showAdd?<AddButton label={ko?"세 번째 과정 추가":"Add a third program"} onClick={onAdd}/>:null}</div></th>{slots.map((slot)=><DesktopHeader ko={ko} key={slot} slot={slot} program={selectedPrograms[slot]??null} chooserOpen={chooserSlot===slot} triggerRef={(element)=>{triggerRefs.current[slot]=element}} onOpen={onOpen} onRemove={onRemove} onCancel={slot===2&&!selectedPrograms[slot]?onCancelThird:undefined}/>)}</tr></thead>{selectedPrograms.length>=2?<tbody>{sections.map((section)=><ProgramSectionRows key={section.title} section={section} slots={slots}/>)}</tbody>:null}</table></div>}
function ProgramSectionRows({section,slots}:{section:ProgramComparisonSection;slots:readonly number[]}){return <><tr><th colSpan={slots.length+1} className="border-b border-[#e7e6e3] bg-[#f7f7f5] px-4 py-2.5 text-left text-xs font-semibold uppercase tracking-[0.1em] text-[#6f6d68]">{section.title}</th></tr>{section.rows.map((row)=><tr key={row.key}><th scope="row" className="border-b border-[#ecebe7] bg-white px-4 py-4 align-top text-sm font-medium text-[#5f5d57]">{row.label}</th>{slots.map((slot)=><td key={`${row.key}-${slot}`} className="border-b border-l border-[#ecebe7] px-5 py-4 align-top text-sm font-semibold leading-6 text-[#1b1b1b]">{row.values[slot]??null}</td>)}</tr>)}</>}
function DesktopHeader({ko,slot,program,chooserOpen,triggerRef,onOpen,onRemove,onCancel}:{ko:boolean;slot:number;program:ProgramCompareItem|null;chooserOpen:boolean;triggerRef:(element:HTMLButtonElement|null)=>void;onOpen:(slot:number)=>void;onRemove:(slot:number)=>void;onCancel?:()=>void}){return <th scope="col" className="sticky top-14 z-20 border-b border-l border-[#e7e6e3] bg-white/95 px-2 py-2 align-top backdrop-blur-md"><div className="relative"><ProgramTrigger ko={ko} slot={slot} program={program} chooserOpen={chooserOpen} triggerRef={triggerRef} onOpen={onOpen}/><HeaderAction ko={ko} program={program} slot={slot} onRemove={onRemove} onCancel={onCancel}/></div></th>}
function MobileMatrix({ko,slots,selectedPrograms,chooserSlot,showAdd,sections,triggerRefs,onOpen,onRemove,onAdd,onCancelThird}:MatrixProps){return <div className="md:hidden"><div className="sticky top-14 z-20 -mx-1 border-y border-[#e7e6e3] bg-white/95 px-1 py-2 backdrop-blur-md" aria-label={ko?"과정 비교 열":"Program comparison columns"}><div className="grid grid-cols-2 gap-2">{slots.map((slot)=><MobileHeader ko={ko} key={slot} slot={slot} program={selectedPrograms[slot]??null} chooserOpen={chooserSlot===slot} triggerRef={(element)=>{triggerRefs.current[slot]=element}} onOpen={onOpen} onRemove={onRemove} onCancel={slot===2&&!selectedPrograms[slot]?onCancelThird:undefined} className={slot===2?"col-span-2":""}/>)}</div>{showAdd?<button type="button" onClick={onAdd} className="mt-2 inline-flex min-h-10 items-center rounded-lg px-2 text-sm font-semibold text-blue-700 hover:bg-blue-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35"><Plus aria-hidden="true" className="mr-1.5 size-4"/>{ko?"과정 추가":"Add program"}</button>:null}</div>{selectedPrograms.length>=2?<div className="mt-5 space-y-7">{sections.map((section)=><section key={section.title}><h3 className="text-xs font-semibold uppercase tracking-[0.1em] text-[#6f6d68]">{section.title}</h3><div className="mt-2 divide-y divide-[#ecebe7] border-y border-[#ecebe7]">{section.rows.map((row)=><div key={row.key} className="py-4"><p className="text-sm font-medium text-[#5f5d57]">{row.label}</p><div className="mt-2 grid grid-cols-2 gap-2">{selectedPrograms.map((program,index)=><div key={`${row.key}-${program.productProgramId}`} className="min-w-0 rounded-xl bg-[#fafaf9] p-3"><p className="truncate text-[11px] font-semibold text-[#77746e]">{displayInstitution(program,ko)}</p><div className="mt-1 break-words text-sm font-semibold leading-5 text-[#1b1b1b]">{row.values[index]}</div></div>)}</div></div>)}</div></section>)}</div>:null}</div>}
function MobileHeader({ko,slot,program,chooserOpen,triggerRef,onOpen,onRemove,onCancel,className}:{ko:boolean;slot:number;program:ProgramCompareItem|null;chooserOpen:boolean;triggerRef:(element:HTMLButtonElement|null)=>void;onOpen:(slot:number)=>void;onRemove:(slot:number)=>void;onCancel?:()=>void;className?:string}){return <div className={`relative min-w-0 rounded-xl border border-[#e7e6e3] bg-white p-1 ${className??""}`}><ProgramTrigger ko={ko} slot={slot} program={program} chooserOpen={chooserOpen} triggerRef={triggerRef} onOpen={onOpen}/><HeaderAction ko={ko} program={program} slot={slot} onRemove={onRemove} onCancel={onCancel} mobile/></div>}
function ProgramTrigger({ko,slot,program,chooserOpen,triggerRef,onOpen}:{ko:boolean;slot:number;program:ProgramCompareItem|null;chooserOpen:boolean;triggerRef:(element:HTMLButtonElement|null)=>void;onOpen:(slot:number)=>void}){const institution=program?displayInstitution(program,ko):"";const name=program?displayProgramName(program,ko):"";return <button ref={triggerRef} type="button" aria-haspopup="dialog" aria-expanded={chooserOpen} aria-label={program?(ko?`${institution} ${name} 변경`:`Change ${institution} ${name}`):(ko?`과정 ${slot+1} 선택`:`Select program ${slot+1}`)} onClick={()=>onOpen(slot)} className="relative min-h-16 w-full rounded-lg px-3 py-2.5 pr-10 text-left hover:bg-[#fafaf9] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35"><span className="block pr-5 text-[11px] font-semibold uppercase tracking-[0.08em] text-[#77746e]">{program?institution:(ko?`과정 ${slot+1}`:`Program ${slot+1}`)}</span><span className="mt-1 block break-words pr-5 text-sm font-semibold leading-5 text-[#1b1b1b]">{program?name:(ko?"과정을 선택하세요":"Choose a programme")}</span><ChevronDown aria-hidden="true" className="absolute right-3 top-5 size-4 text-[#77746e]"/></button>}
function HeaderAction({ko,program,slot,onRemove,onCancel,mobile=false}:{ko:boolean;program:ProgramCompareItem|null;slot:number;onRemove:(slot:number)=>void;onCancel?:()=>void;mobile?:boolean}){if(onCancel)return <button type="button" onClick={onCancel} aria-label={ko?"세 번째 과정 선택 취소":"Cancel third program"} className={`absolute ${mobile?"right-1 top-1":"right-1 top-1"} z-10 min-h-9 rounded-lg px-2 text-xs font-semibold text-[#5f5d57] hover:bg-[#f0efeb] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35`}>{ko?"취소":"Cancel"}</button>;if(!program)return null;return <button type="button" onClick={()=>onRemove(slot)} aria-label={ko?`${displayInstitution(program,true)} ${displayProgramName(program,true)} 비교에서 제거`:`Remove ${displayInstitution(program,false)} ${displayProgramName(program,false)} from comparison`} className={`absolute ${mobile?"right-1 top-1":"right-1 top-1"} z-10 inline-flex size-9 items-center justify-center rounded-lg text-[#77746e] hover:bg-[#f0efeb] hover:text-[#1b1b1b] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35`}><X aria-hidden="true" className="size-4"/></button>}
function AddButton({label,onClick}:{label:string;onClick:()=>void}){return <button type="button" aria-label={label} onClick={onClick} className="inline-flex size-9 items-center justify-center rounded-lg text-blue-700 hover:bg-blue-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35"><Plus aria-hidden="true" className="size-4"/></button>}
function ProgramChooser({ko,slot,selectedIds,programs,onChoose,onClose}:{ko:boolean;slot:number;selectedIds:readonly string[];programs:readonly ProgramCompareItem[];onChoose:(slot:number,id:string)=>void;onClose:()=>void}){useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};window.addEventListener("keydown",onKeyDown);return()=>window.removeEventListener("keydown",onKeyDown)},[onClose]);return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/20 p-3 sm:items-center" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose()}}><div role="dialog" aria-modal="true" aria-labelledby="program-chooser-heading" className="w-full max-w-lg rounded-2xl border border-[#e7e6e3] bg-white p-5 shadow-xl"><div className="flex items-start justify-between gap-4"><div><h2 id="program-chooser-heading" className="text-base font-semibold text-[#1b1b1b]">{ko?"과정 선택":"Choose a programme"}</h2><p className="mt-1 text-sm text-[#6f6d68]">{ko?`${slot+1}번째 열에 넣을 검증된 과정을 선택하세요.`:`Select a verified option for column ${slot+1}.`}</p></div><button type="button" onClick={onClose} aria-label={ko?"과정 선택 닫기":"Close programme chooser"} className="inline-flex size-10 items-center justify-center rounded-lg text-[#6f6d68] hover:bg-[#f0efeb] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35"><X aria-hidden="true" className="size-4"/></button></div><div className="mt-4 max-h-[60vh] space-y-2 overflow-y-auto pr-1">{programs.map((program)=>{const disabled=selectedIds.includes(program.productProgramId)&&selectedIds[slot]!==program.productProgramId;return <button key={program.productProgramId} type="button" disabled={disabled} onClick={()=>onChoose(slot,program.productProgramId)} className="w-full rounded-xl border border-[#e7e6e3] px-3 py-3 text-left text-sm hover:bg-[#fafaf9] disabled:cursor-not-allowed disabled:opacity-45 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600/35"><span className="block font-semibold text-[#1b1b1b]">{displayInstitution(program,ko)}</span><span className="mt-1 block text-[#6f6d68]">{displayProgramName(program,ko)}</span>{disabled?<span className="mt-1 block text-xs text-[#6f6d68]">{ko?"이미 선택됨":"Already selected"}</span>:null}</button>})}</div></div></div>}
