import Link from "next/link"
import { ArrowRight, BriefcaseBusiness, Building2, Info, MapPin, TrainFront, Users, Wallet } from "lucide-react"
import type { EsCityProfile } from "@/lib/cities/es-city-profile.server"
import { localizePath } from "@/lib/i18n/config"
import { CityCompareSelector, type CityCompareOption } from "./city-compare-selector"

type Props = { left: EsCityProfile; right: EsCityProfile; options: readonly CityCompareOption[] }

function money(value:number,currency="EUR"){return new Intl.NumberFormat("ko-KR",{style:"currency",currency,maximumFractionDigits:value%1===0?0:2}).format(value)}
function compact(value:number){return new Intl.NumberFormat("ko-KR",{notation:"compact",maximumFractionDigits:2}).format(value)}
function period(value:string){if(value==="month")return"월";if(value==="week")return"주";if(value==="semester")return"학기";return value.replaceAll("_"," ")}
function living(profile:EsCityProfile){if(!profile.livingCost)return"—";const scope=profile.livingCost.fullBudget?"전체 예산 참고값":"부분 비용 참고값";return`${money(profile.livingCost.low,profile.livingCost.currency)}–${money(profile.livingCost.high,profile.livingCost.currency)} / ${period(profile.livingCost.period)} · ${scope}`}
function transport(profile:EsCityProfile){if(!profile.transport)return"—";return`${money(profile.transport.amount,profile.transport.currency)} / ${period(profile.transport.period)}`}
function programmes(profile:EsCityProfile){return profile.programmeCoverage.status==="verified_partial"?`${profile.linkedProgramCount}개 부분 검증 과정`:"검증 진행 중"}
function Row({icon,label,note,left,right,leftName,rightName}:{icon:React.ReactNode;label:string;note?:string;left:string;right:string;leftName:string;rightName:string}){return <div className="grid grid-cols-2 border-t border-[#ecebe7] md:grid-cols-[220px_minmax(0,1fr)_minmax(0,1fr)]"><div className="col-span-2 flex items-start gap-2 px-4 py-3.5 text-[12px] font-semibold text-[#5f5d57] md:col-span-1 md:px-5 md:py-4"><span className="mt-0.5 text-[#8f8c85]">{icon}</span><div><p>{label}</p>{note?<p className="mt-1 text-[10px] font-normal leading-4 text-[#9a978f]">{note}</p>:null}</div></div><div className="min-w-0 border-t border-[#f0efec] px-3 py-3.5 text-[13px] font-semibold leading-5 text-[#1b1b1b] md:border-l md:border-t-0 md:px-5 md:py-4 md:text-[14px]"><span className="mb-1 block text-[9.5px] uppercase tracking-[0.08em] text-[#9a978f] md:hidden">{leftName}</span>{left}</div><div className="min-w-0 border-l border-t border-[#f0efec] px-3 py-3.5 text-[13px] font-semibold leading-5 text-[#1b1b1b] md:px-5 md:py-4 md:text-[14px]"><span className="mb-1 block text-[9.5px] uppercase tracking-[0.08em] text-[#9a978f] md:hidden">{rightName}</span>{right}</div></div>}
function Header({city}:{city:EsCityProfile}){return <div className="min-w-0 px-3 py-4 sm:px-4 md:px-5 md:py-5"><p className="text-[10px] font-semibold uppercase tracking-[0.1em] text-[#8f8c85]">{city.regionName}</p><h2 className="mt-1 text-[20px] font-semibold tracking-[-0.03em] text-[#1b1b1b] md:text-[24px]">{city.name}</h2><p className="mt-1 text-[10.5px] text-[#77746e]">INE 지자체 코드 {city.municipalityCode}</p><Link href={localizePath(`/cities/es/${city.slug}`,"ko")} className="mt-2 inline-flex items-center gap-1 text-[11px] font-semibold text-[#9b4a24] hover:underline">도시 프로필 <ArrowRight className="size-3"/></Link></div>}

export function SpainCitiesCompareMatrixKo({left,right,options}:Props){return <div className="w-full"><CityCompareSelector options={options} leftSlug={left.slug} rightSlug={right.slug} countryCode="ES"/><header className="mt-4 rounded-2xl border border-[#eaded7] bg-gradient-to-br from-[#fff7f2] via-white to-[#f8f4ee] p-5 sm:p-8"><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[#9b4a24]">스페인 도시 비교</p><h2 className="mt-2 text-[30px] font-semibold leading-tight tracking-[-0.035em] text-[#1b1b1b] sm:text-[40px]">{left.name} vs {right.name}</h2><p className="mt-3 max-w-3xl text-[13px] leading-6 text-[#6f6d68]">동일한 INE 지자체 인구 경계, 검증된 교육 장소 근거와 검토된 도시 지표를 비교합니다. 생활비와 교통비는 출처별 산정 방식을 유지하므로 단순 최저가 순위로 해석하지 않습니다.</p></header><div className="mt-4 overflow-hidden rounded-2xl border border-[#e7e6e3] bg-white"><div className="grid grid-cols-2 md:grid-cols-[220px_minmax(0,1fr)_minmax(0,1fr)]"><div className="hidden md:block"/><Header city={left}/><div className="border-l border-[#ecebe7]"><Header city={right}/></div></div><Row icon={<MapPin className="size-3.5"/>} label="지자체 인구" note="동일한 INE 지자체 기준과 2025년 참조일" left={left.population?compact(left.population.amount):"—"} right={right.population?compact(right.population.amount):"—"} leftName={left.name} rightName={right.name}/><Row icon={<Wallet className="size-3.5"/>} label="학생 생활비 참고값" note="공식 출처별 산정 방식이 달라 최저가 도시를 단정하지 않습니다." left={living(left)} right={living(right)} leftName={left.name} rightName={right.name}/><Row icon={<TrainFront className="size-3.5"/>} label="지역 교통비 참고값" note="출처의 원래 승차권·유효기간을 유지합니다." left={transport(left)} right={transport(right)} leftName={left.name} rightName={right.name}/><Row icon={<Building2 className="size-3.5"/>} label="검증된 교육 장소" note="선정된 교육기관 기반 자료이며 스페인 전체 고등교육기관 목록은 아닙니다." left={`${left.linkedInstitutionCount}개 기관 · ${left.linkedCampusCount}개 장소`} right={`${right.linkedInstitutionCount}개 기관 · ${right.linkedCampusCount}개 장소`} leftName={left.name} rightName={right.name}/><Row icon={<Users className="size-3.5"/>} label="과정 근거" note="정확한 출처-도시 연결만 사용하며 0은 검증 대기일 수 있습니다." left={programmes(left)} right={programmes(right)} leftName={left.name} rightName={right.name}/><Row icon={<BriefcaseBusiness className="size-3.5"/>} label="취업 환경" note="공식 지역 경제 맥락이며 인력부족 순위나 취업 보장이 아닙니다." left={`${left.employmentSectors.length}개 주요 분야`} right={`${right.employmentSectors.length}개 주요 분야`} leftName={left.name} rightName={right.name}/></div><div className="mt-4 rounded-xl border border-[#e4e3df] bg-[#fafaf8] p-4 text-[11px] leading-5 text-[#74716b]"><div className="flex items-start gap-2"><Info className="mt-0.5 size-3.5 shrink-0"/><p>스페인 비교는 의도적으로 승자를 점수화하지 않습니다. 생활비와 교통비는 서로 다른 출처 기준을 유지하고, 과정 수는 정확한 과정-도시 근거가 검증된 경우에만 표시합니다.</p></div></div></div>}
