import { institutionDetailPath } from "./institution-search"

export const INDEXABLE_INSTITUTION_ROUTES = [
  ["AU", "australian-catholic-university"],
  ["AU", "australian-national-university"],
  ["AU", "avondale-university"],
  ["AU", "bond-university"],
  ["AU", "central-queensland-university"],
  ["AU", "charles-darwin-university"],
  ["AU", "charles-sturt-university"],
  ["AU", "curtin-university"],
  ["AU", "deakin-university"],
  ["AU", "edith-cowan-university"],
  ["AU", "federation-university-australia"],
  ["AU", "flinders-university"],
  ["AU", "griffith-university"],
  ["AU", "james-cook-university"],
  ["AU", "la-trobe-university"],
  ["AU", "macquarie-university"],
  ["AU", "monash-university"],
  ["AU", "murdoch-university"],
  ["AU", "queensland-university-of-technology"],
  ["AU", "rmit-university"],
  ["AU", "southern-cross-university"],
  ["AU", "swinburne-university-of-technology"],
  ["AU", "tafe-nsw"],
  ["AU", "tafe-sa"],
  ["AU", "torrens-university"],
  ["AU", "university-of-adelaide"],
  ["AU", "university-of-canberra"],
  ["AU", "university-of-divinity"],
  ["AU", "university-of-melbourne"],
  ["AU", "university-of-new-england"],
  ["AU", "university-of-new-south-wales"],
  ["AU", "university-of-newcastle"],
  ["AU", "university-of-notre-dame-australia"],
  ["AU", "university-of-queensland"],
  ["AU", "university-of-south-australia"],
  ["AU", "university-of-southern-queensland"],
  ["AU", "university-of-sydney"],
  ["AU", "university-of-tasmania"],
  ["AU", "university-of-technology-sydney"],
  ["AU", "university-of-the-sunshine-coast"],
  ["AU", "university-of-western-australia"],
  ["AU", "university-of-wollongong"],
  ["AU", "victoria-university"],
  ["AU", "western-sydney-university"],
  ["CA", "brock-university"],
  ["CA", "carleton-university"],
  ["CA", "concordia-university"],
  ["CA", "dalhousie-university"],
  ["CA", "macewan-university"],
  ["CA", "mcgill-university"],
  ["CA", "mcmaster-university"],
  ["CA", "memorial-university-of-newfoundland"],
  ["CA", "ontario-tech-university"],
  ["CA", "queen-s-university"],
  ["CA", "simon-fraser-university"],
  ["CA", "toronto-metropolitan-university"],
  ["CA", "universit-de-montr-al"],
  ["CA", "universit-du-qu-bec-montr-al"],
  ["CA", "universit-laval"],
  ["CA", "university-of-alberta"],
  ["CA", "university-of-british-columbia"],
  ["CA", "university-of-calgary"],
  ["CA", "university-of-guelph"],
  ["CA", "university-of-manitoba"],
  ["CA", "university-of-new-brunswick"],
  ["CA", "university-of-northern-british-columbia"],
  ["CA", "university-of-ottawa"],
  ["CA", "university-of-saskatchewan"],
  ["CA", "university-of-toronto"],
  ["CA", "university-of-victoria"],
  ["CA", "university-of-waterloo"],
  ["CA", "western-university"],
  ["CA", "wilfrid-laurier-university"],
  ["CA", "york-university"],
] as const

export const INDEXABLE_INSTITUTION_PATHS = INDEXABLE_INSTITUTION_ROUTES.map(
  ([countryCode, slug]) => institutionDetailPath(countryCode, slug),
)
