import { institutionDetailPath } from "./institution-search"

export const INDEXABLE_UK_INSTITUTION_ROUTES = [
  ["UK", "aston-university"],
  ["UK", "brunel-university-of-london"],
  ["UK", "cardiff-university"],
  ["UK", "city-st-georges-university-of-london"],
  ["UK", "coventry-university"],
  ["UK", "durham-university"],
  ["UK", "heriot-watt-university"],
  ["UK", "imperial-college-london"],
  ["UK", "king-s-college-london"],
  ["UK", "lancaster-university"],
  ["UK", "london-school-of-economics-and-political-science"],
  ["UK", "loughborough-university"],
  ["UK", "newcastle-university"],
  ["UK", "nottingham-trent-university"],
  ["UK", "queen-mary-university-of-london"],
  ["UK", "queen-s-university-belfast"],
  ["UK", "royal-holloway-university-of-london"],
  ["UK", "swansea-university"],
  ["UK", "ulster-university"],
  ["UK", "university-college-london"],
  ["UK", "university-of-aberdeen"],
  ["UK", "university-of-bath"],
  ["UK", "university-of-birmingham"],
  ["UK", "university-of-bradford"],
  ["UK", "university-of-bristol"],
  ["UK", "university-of-cambridge"],
  ["UK", "university-of-east-anglia"],
  ["UK", "university-of-edinburgh"],
  ["UK", "university-of-essex"],
  ["UK", "university-of-exeter"],
  ["UK", "university-of-glasgow"],
  ["UK", "university-of-hertfordshire"],
  ["UK", "university-of-kent"],
  ["UK", "university-of-leeds"],
  ["UK", "university-of-leicester"],
  ["UK", "university-of-liverpool"],
  ["UK", "university-of-manchester"],
  ["UK", "university-of-nottingham"],
  ["UK", "university-of-oxford"],
  ["UK", "university-of-plymouth"],
  ["UK", "university-of-reading"],
  ["UK", "university-of-salford"],
  ["UK", "university-of-sheffield"],
  ["UK", "university-of-southampton"],
  ["UK", "university-of-st-andrews"],
  ["UK", "university-of-strathclyde"],
  ["UK", "university-of-surrey"],
  ["UK", "university-of-sussex"],
  ["UK", "university-of-warwick"],
  ["UK", "university-of-york"],
] as const

export const INDEXABLE_UK_INSTITUTION_PATHS = INDEXABLE_UK_INSTITUTION_ROUTES.map(
  ([countryCode, slug]) => institutionDetailPath(countryCode, slug),
)
