import { institutionDetailPath } from "./institution-search"

export const INDEXABLE_AUTHORITY_FASTPATH_INSTITUTION_ROUTES = [
  ["FI", "aalto-university"],
  ["FI", "abo-akademi-university"],
  ["FI", "hanken-school-of-economics"],
  ["FI", "lut-university"],
  ["FI", "tampere-university"],
  ["FI", "university-of-eastern-finland"],
  ["FI", "university-of-helsinki"],
  ["FI", "university-of-jyvaskyla"],
  ["FI", "university-of-oulu"],
  ["FI", "university-of-turku"],
  ["NO", "nord-university"],
  ["NO", "norwegian-university-of-life-sciences"],
  ["NO", "norwegian-university-of-science-and-technology"],
  ["NO", "oslomet-oslo-metropolitan-university"],
  ["NO", "uit-the-arctic-university-of-norway"],
  ["NO", "university-of-agder"],
  ["NO", "university-of-bergen"],
  ["NO", "university-of-inland-norway"],
  ["NO", "university-of-oslo"],
  ["NO", "university-of-south-eastern-norway"],
  ["NO", "university-of-stavanger"],
  ["JP", "hitotsubashi-university"],
  ["JP", "institute-of-science-tokyo"],
  ["JP", "kyoto-university"],
  ["JP", "kyushu-university"],
  ["JP", "nagoya-university"],
  ["JP", "the-university-of-osaka"],
  ["JP", "the-university-of-tokyo"],
  ["JP", "tohoku-university"],
  ["JP", "university-of-tsukuba"],
  ["KR", "ewha-womans-university"],
  ["KR", "hanyang-university"],
  ["KR", "kaist"],
  ["KR", "korea-university"],
  ["KR", "kyung-hee-university"],
  ["KR", "postech"],
  ["KR", "pusan-national-university"],
  ["KR", "seoul-national-university"],
  ["KR", "sungkyunkwan-university"],
  ["KR", "yonsei-university"],
] as const

export const INDEXABLE_AUTHORITY_FASTPATH_INSTITUTION_PATHS = INDEXABLE_AUTHORITY_FASTPATH_INSTITUTION_ROUTES.map(
  ([countryCode, slug]) => institutionDetailPath(countryCode, slug),
)
