import { institutionDetailPath } from "./institution-search"

export const INDEXABLE_EU_FASTPATH_INSTITUTION_ROUTES = [
  ["BE", "ku-leuven"],
  ["BE", "universiteit-gent"],
  ["BE", "universiteit-antwerpen"],
  ["BE", "vrije-universiteit-brussel"],
  ["BE", "universite-catholique-de-louvain"],
  ["BE", "universite-libre-de-bruxelles"],
  ["BE", "universite-de-liege"],
  ["BE", "universite-de-namur"],
  ["CH", "ecole-polytechnique-federale-de-lausanne-epfl"],
  ["CH", "eidgenossische-technische-hochschule-zurich-eth"],
  ["CH", "universitat-basel"],
  ["CH", "universitat-bern-unibe"],
  ["CH", "universite-de-fribourg-unifr"],
  ["CH", "universite-de-geneve-unige"],
  ["CH", "universite-de-lausanne-unil"],
  ["CH", "universitat-luzern-unilu"],
  ["CH", "universite-de-neuchatel-unine"],
  ["CH", "universitat-st-gallen-hsg"],
  ["CH", "universita-della-svizzera-italiana-usi"],
  ["CH", "universitat-zurich-uzh"],
  ["SE", "uppsala-university"],
  ["SE", "lund-university"],
  ["SE", "university-of-gothenburg"],
  ["SE", "stockholm-university"],
  ["SE", "umea-university"],
  ["SE", "linkoping-university"],
  ["SE", "karolinska-institutet"],
  ["SE", "kth-royal-institute-of-technology"],
  ["SE", "chalmers-university-of-technology"],
  ["SE", "swedish-university-of-agricultural-sciences"],
  ["DK", "aalborg-universitet"],
  ["DK", "aarhus-universitet"],
  ["DK", "copenhagen-business-school"],
  ["DK", "danmarks-tekniske-universitet"],
  ["DK", "it-universitetet-i-kobenhavn"],
  ["DK", "kobenhavns-universitet"],
  ["DK", "roskilde-universitet"],
  ["DK", "syddansk-universitet"],
] as const

export const INDEXABLE_EU_FASTPATH_INSTITUTION_PATHS = INDEXABLE_EU_FASTPATH_INSTITUTION_ROUTES.map(
  ([countryCode, slug]) => institutionDetailPath(countryCode, slug),
)
