insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:accountant','IE','accountant','Chartered and certified accountants — accountant scope','SOC','SOC 2010','2421','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:financial-analyst','IE','financial-analyst','Finance and investment analysts and advisers','SOC','SOC 2010','3534','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:business-analyst','IE','business-analyst','Management consultants and business analysts','SOC','SOC 2010','2423','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:supply-chain-analyst','IE','supply-chain-analyst','Buyers and procurement officers — supply-chain / procurement analysis scope','SOC','SOC 2010','3541','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:human-resources-specialist','IE','human-resources-specialist','Human resources and industrial relations officers','SOC','SOC 2010','3562','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:marketing-specialist','IE','marketing-specialist','Marketing associate professionals','SOC','SOC 2010','3543','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:auditor','IE','auditor','Chartered and certified accountants — statutory financial-audit scope','SOC','SOC 2010','2421','EUR',true,'Recognised Accountancy Body / statutory auditor register','https://iaasa.ie/faqs/how-can-i-satisfy-myself-that-a-person-and-or-firm-is-properly-qualified-to-provide-auditing-services-to-the-public/','profile_ready','2026-08-11',now()),
  ('IE:project-manager','IE','project-manager','Business and financial project management professionals — business project-management scope','SOC','SOC 2010','2424','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:accountant','2026-08-11',null,null,null,0,0,0,0,8,0,0,8,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2421 Chartered and certified accountants, accountant scope.','shortage_note','SOLAS 2025 describes continuing business/financial technical demand but the reviewed public summary does not publish an accountant-specific current shortage finding; 0/20.','visa_basis','Current CSEP treatment under SOC 2421 is conditional on chartered/certified status and specified tax, compliance, regulation, solvency, financial-management or related specialist skills; conditional 8/10 rather than universal credit.','permit_recognition_boundary','For employment-permit purposes, foreign accountants generally need registration with or qualification recognition by one of the bodies specified in the Employment Permit Regulations. This is not promoted into a universal legal licence for every accountant job.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Professional accountancy qualifications and degree/apprenticeship progression routes exist; no single universal route is assumed; 8/15.','entry_burden_basis','Generic accountancy is not modelled as a single universally licensed profession; 5/5.'),'2026-08-11'),
  ('IE:financial-analyst','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3534 Finance and investment analysts and advisers.','shortage_note','SOLAS 2025 reports persistent demand for sophisticated technical skills in financial services but does not publish an exact Financial Analyst shortage finding in the reviewed summary; 0/20.','visa_basis','SOC 3534 is not explicitly listed on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP accessibility may apply subject to employer and permit conditions; 6/10.','csep_boundary','Finance/investment analytics on the CSEP list sits under SOC 2424 business and financial project-management specialist employments and is not borrowed by generic SOC 3534 Financial Analyst.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree-level finance/economics/business or equivalent analytical experience is common; 8/15.','entry_burden_basis','No universal statutory professional registration is required for the generic occupation; 5/5.'),'2026-08-11'),
  ('IE:business-analyst','2026-08-11',null,null,null,0,0,0,0,8,0,0,8,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2423 Management consultants and business analysts.','shortage_note','SOLAS 2025 reports business/finance technical-skill demand but no exact generic Business Analyst shortage in the reviewed public summary; 0/20.','visa_basis','Current CSEP treatment for SOC 2423 is limited to management consultants/business analysts specialising in big-data analytics with IT, data-mining, modelling and advanced-maths skills or related relevant specialisms; conditional 8/10.','scope_boundary','Generic process, operations or change-analysis roles must not be labelled Critical Skills solely because they carry the Business Analyst title.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree, conversion and experience-based business-analysis routes exist; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-11'),
  ('IE:supply-chain-analyst','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3541 Buyers and procurement officers, constrained to supply-chain/procurement analysis.','shortage_note','No exact Supply Chain Analyst shortage is published in the reviewed SOLAS 2025 business/financial summary; 0/20.','visa_basis','SOC 3541 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP accessibility may apply subject to conditions; 6/10.','scope_boundary','The profile does not roll logistics managers, warehouse managers or generic data analysts into the same occupation.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Ireland has structured work-based supply-chain apprenticeships, including Supply Chain Specialist, supporting a comparatively accessible pathway; 12/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-11'),
  ('IE:human-resources-specialist','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3562 Human resources and industrial relations officers.','shortage_note','No exact HR Specialist shortage is published in the reviewed SOLAS 2025 business/financial summary; 0/20.','visa_basis','SOC 3562 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP accessibility may apply subject to conditions; 6/10.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree, professional HR qualification and experience-based routes are common; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-11'),
  ('IE:marketing-specialist','2026-08-11',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3543 Marketing associate professionals.','shortage_note','No exact Marketing Specialist shortage is published in the reviewed SOLAS 2025 business/financial summary; 0/20.','visa_basis','SOC 3543 is not explicitly on the current Critical Skills list and was not identified on the current Ineligible list; ordinary GEP accessibility may apply subject to conditions; 6/10.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','The national Digital Marketing Level 6 apprenticeship provides a verified structured work-based route; 12/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-11'),
  ('IE:auditor','2026-08-11',null,null,null,0,0,0,0,6,0,0,8,2,16,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2421 Chartered and certified accountants, constrained here to statutory financial-audit scope.','shortage_note','No separate auditor-specific SOLAS 2025 shortage finding is used; 0/20.','visa_basis','CSEP can apply to specified SOC 2421 qualified-accountant/audit specialist employments, including defined MNC global-audit cases; conditional 8/10.','registration_basis','For statutory company audit, the auditor must be appropriately qualified and registered/authorised through a recognised accountancy body; this legal scope is why the profile is registration-required.','scope_boundary','Internal audit, operational audit and non-statutory assurance roles can have different qualification requirements and must not be assumed to require statutory-auditor registration.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Statutory audit requires recognised professional accountancy formation, supervised experience and audit authorisation; 6/15.','entry_burden_basis','Statutory-audit authorisation creates a material regulated-entry burden; 2/5.'),'2026-08-11'),
  ('IE:project-manager','2026-08-11',null,null,null,0,0,0,0,8,0,0,8,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2424 Business and financial project management professionals, constrained to business/financial project-management work.','shortage_note','The reviewed SOLAS 2025 public business/finance summary does not publish a generic Project Manager shortage; 0/20.','visa_basis','Current CSEP treatment under SOC 2424 is specialist-dependent, covering finance/investment analytics, risk analytics, credit, fraud analytics or related relevant specialist skills; conditional 8/10.','scope_boundary','IT project managers (2134) and construction project managers (2436) have separate SOC/CSEP treatment and are not rolled into this Business-category profile.','salary_method','No exact comparable current Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree, professional project-management and experience-based routes exist; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (
  profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at
) values
  ('IE:accountant','2421','Chartered and certified accountants — conditional Critical Skills specialist scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:financial-analyst','3534','Finance and investment analysts and advisers',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:business-analyst','2423','Management consultants and business analysts — big-data analytics specialist employment',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:supply-chain-analyst','3541','Buyers and procurement officers — supply-chain / procurement analysis scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:human-resources-specialist','3562','Human resources and industrial relations officers',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:marketing-specialist','3543','Marketing associate professionals',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:auditor','2421','Chartered and certified accountants — statutory audit scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:project-manager','2424','Business and financial project management professionals — specialist analytics scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (
  profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at
) values
  ('IE:accountant','source','SOLAS — Business and Financial labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:accountant','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11'),
  ('IE:accountant','source','DETE — accountant qualification recognition for employment permits','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/accountants/','government',null,3,'2026-08-11'),
  ('IE:accountant','entry_program','Generation Apprenticeship — Accounting Technician','https://apprenticeship.ie/career-seekers/get-started/learn-more/finance/Accounting-Technician','government',null,4,'2026-08-11'),
  ('IE:financial-analyst','source','SOLAS — Business and Financial labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:financial-analyst','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:business-analyst','source','SOLAS — Business and Financial labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:business-analyst','source','DETE — Critical Skills big-data business-analysis scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11'),
  ('IE:supply-chain-analyst','source','SOLAS — Business and Financial labour-market context','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:supply-chain-analyst','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:supply-chain-analyst','entry_program','Generation Apprenticeship — Supply Chain Specialist','https://apprenticeship.ie/career-seekers/get-started/learn-more/logistics/supply-chain-specialist','government',null,3,'2026-08-11'),
  ('IE:human-resources-specialist','source','SOLAS — Business and Financial labour-market context','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:human-resources-specialist','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:marketing-specialist','source','SOLAS — Business and Financial labour-market context','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:marketing-specialist','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:marketing-specialist','entry_program','Generation Apprenticeship — Digital Marketing L6','https://apprenticeship.ie/career-seekers/get-started/next-steps/sales/digital-marketing-l6','government',null,3,'2026-08-11'),
  ('IE:auditor','source','SOLAS — Business and Financial labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:auditor','source','DETE — Critical Skills qualified-accountant / audit specialist scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11'),
  ('IE:auditor','source','IAASA — statutory auditor qualification and registration','https://iaasa.ie/faqs/how-can-i-satisfy-myself-that-a-person-and-or-firm-is-properly-qualified-to-provide-auditing-services-to-the-public/','regulator',null,3,'2026-08-11'),
  ('IE:project-manager','source','SOLAS — Business and Financial labour-market context','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/business-and-financial/','government',null,1,'2026-08-11'),
  ('IE:project-manager','source','DETE — Critical Skills specialist SOC 2424 scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
