-- United States Programs Phase 2 staging foundation.
-- Deliberately bounded to programmes that map to CampCareer canonical target occupations.
-- Phase 2 does not canonicalize or publish programmes.

CREATE TABLE public.program_catalog_us_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name text NOT NULL,
  source_program_key text NOT NULL,
  institution_id uuid NOT NULL REFERENCES catalog.institutions(id),
  institution_name text NOT NULL,
  unitid text NOT NULL,
  source_program_name text NOT NULL,
  title text NOT NULL,
  credential_name text NOT NULL,
  award_level text NOT NULL CHECK (award_level IN ('CERTIFICATE','ASSOCIATE','BACHELOR','BACHELOR_PROFESSIONAL','MASTER','DOCTORAL','OTHER')),
  cip_code text,
  cip_evidence_status text NOT NULL DEFAULT 'unresolved' CHECK (cip_evidence_status IN ('verified','corroborated','unresolved')),
  cip_source_url text,
  credit_units numeric CHECK (credit_units IS NULL OR credit_units > 0),
  credit_unit_type text,
  default_duration_months integer CHECK (default_duration_months IS NULL OR default_duration_months > 0),
  study_mode text,
  field_category text,
  institutional_accreditation_context text,
  programmatic_accreditation_context text,
  accreditation_source_url text,
  official_program_url text NOT NULL,
  official_catalog_url text,
  international_source_url text,
  programme_delivery_verified boolean NOT NULL DEFAULT false,
  programme_delivery_source_url text,
  source_as_of date NOT NULL,
  collection_status text NOT NULL DEFAULT 'official_current_program_collected',
  verification_tier text NOT NULL DEFAULT 'A' CHECK (verification_tier IN ('A','B','C')),
  collected_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_name, source_program_key),
  CHECK ((cip_code IS NULL AND cip_evidence_status = 'unresolved') OR cip_code IS NOT NULL),
  CHECK (programme_delivery_verified OR programme_delivery_source_url IS NULL)
);

CREATE TABLE public.program_occupation_us_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_catalog_id bigint NOT NULL REFERENCES public.program_catalog_us_staging(id) ON DELETE CASCADE,
  canonical_career_id text NOT NULL,
  rule_version text NOT NULL DEFAULT 'us-program-occupation-v1',
  match_basis text NOT NULL,
  match_pattern text,
  review_status text NOT NULL DEFAULT 'approved' CHECK (review_status IN ('candidate','approved','rejected')),
  relation_type text NOT NULL CHECK (relation_type IN ('direct','common_pathway','related')),
  source_checked_at date NOT NULL,
  reviewed_at timestamptz NOT NULL DEFAULT now(),
  reviewer_note text,
  UNIQUE (program_catalog_id, canonical_career_id, rule_version)
);

CREATE TABLE public.program_international_us_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_catalog_id bigint NOT NULL UNIQUE REFERENCES public.program_catalog_us_staging(id) ON DELETE CASCADE,
  international_students_eligible boolean,
  international_admission_status text NOT NULL DEFAULT 'eligible_schedule_unknown' CHECK (international_admission_status IN ('open','closed','not_yet_open','restricted','eligible_schedule_unknown','unknown')),
  sevp_status text NOT NULL DEFAULT 'unresolved' CHECK (sevp_status IN ('confirmed','not_confirmed','unresolved')),
  sevp_school_name text,
  sevp_campus_context text,
  sevp_source_url text,
  student_visa_category_context text,
  student_visa_context text,
  visa_source_url text,
  exact_cip_verified_for_stem boolean,
  stem_designated_cip boolean,
  stem_list_version text,
  stem_list_source_url text,
  stem_list_checked_at date,
  opt_context text,
  stem_opt_context text,
  intake_label text,
  intake_start_date date,
  application_deadline date,
  admission_source_url text,
  international_source_url text,
  verification_status text NOT NULL DEFAULT 'programme_identity_verified_context_pending' CHECK (verification_status IN ('verified','programme_identity_verified_context_pending','review_required','rejected')),
  source_checked_at date NOT NULL,
  verified_at timestamptz,
  reviewer_note text,
  CHECK (stem_designated_cip IS NULL OR exact_cip_verified_for_stem = true)
);

COMMENT ON TABLE public.program_catalog_us_staging IS 'Server-only US Phase 2 bounded programme collection. Exact current programme identity is required; broad IPEDS/Scorecard field rows are discovery-only.';
COMMENT ON TABLE public.program_occupation_us_staging IS 'Server-only reviewed US programme-to-CampCareer-career staging relations. Direct/common_pathway/related do not imply professional licensure.';
COMMENT ON TABLE public.program_international_us_staging IS 'Server-only US programme international/SEVP/OPT context. Programme existence, SEVP, F/M visa, OPT and STEM OPT remain separate evidence layers.';

ALTER TABLE public.program_catalog_us_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_occupation_us_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_international_us_staging ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.program_catalog_us_staging FROM public, anon, authenticated;
REVOKE ALL ON public.program_occupation_us_staging FROM public, anon, authenticated;
REVOKE ALL ON public.program_international_us_staging FROM public, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_catalog_us_staging TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_occupation_us_staging TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_international_us_staging TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
