-- New Zealand Programs Phase 2 staging foundation.
-- Scope is deliberately bounded to programmes that map to CampCareer target occupations.
-- These tables are server-only collection surfaces; Phase 2 does not canonicalize or publish programmes.

CREATE TABLE public.program_catalog_nz_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name text NOT NULL,
  source_program_key text NOT NULL,
  institution_id uuid NOT NULL REFERENCES catalog.institutions(id),
  institution_name text NOT NULL,
  provider_number text NOT NULL,
  source_program_name text NOT NULL,
  title text NOT NULL,
  qualification_name text,
  degree_level text NOT NULL CHECK (degree_level IN ('BACHELOR','BACHELOR_HONOURS','MASTER','GRADUATE','POSTGRADUATE','OTHER')),
  nzqcf_level integer CHECK (nzqcf_level BETWEEN 1 AND 10),
  nzqcf_credits integer CHECK (nzqcf_credits IS NULL OR nzqcf_credits > 0),
  study_mode text,
  field_category text,
  programme_authority text NOT NULL DEFAULT 'CUAP' CHECK (programme_authority IN ('CUAP','NZQA','unknown')),
  programme_authority_url text,
  official_program_url text NOT NULL,
  international_source_url text,
  programme_delivery_verified boolean NOT NULL DEFAULT false,
  programme_delivery_source_url text,
  source_as_of date NOT NULL,
  collection_status text NOT NULL DEFAULT 'official_current_program_collected',
  verification_tier text NOT NULL DEFAULT 'A' CHECK (verification_tier IN ('A','B','C')),
  collected_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_name, source_program_key),
  CHECK (programme_delivery_verified OR programme_delivery_source_url IS NULL)
);

CREATE TABLE public.program_occupation_nz_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_catalog_id bigint NOT NULL REFERENCES public.program_catalog_nz_staging(id) ON DELETE CASCADE,
  canonical_career_id text NOT NULL,
  rule_version text NOT NULL DEFAULT 'nz-program-occupation-v1',
  match_basis text NOT NULL,
  match_pattern text,
  review_status text NOT NULL DEFAULT 'approved' CHECK (review_status IN ('candidate','approved','rejected')),
  relation_type text NOT NULL CHECK (relation_type IN ('direct','common_pathway','related')),
  source_checked_at date NOT NULL,
  reviewed_at timestamptz NOT NULL DEFAULT now(),
  reviewer_note text,
  UNIQUE (program_catalog_id, canonical_career_id, rule_version)
);

CREATE TABLE public.program_international_nz_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_catalog_id bigint NOT NULL UNIQUE REFERENCES public.program_catalog_nz_staging(id) ON DELETE CASCADE,
  international_students_eligible boolean,
  international_admission_status text NOT NULL DEFAULT 'eligible_schedule_unknown' CHECK (international_admission_status IN ('open','closed','not_yet_open','restricted','eligible_schedule_unknown','unknown')),
  code_signatory_status text NOT NULL DEFAULT 'not_programme_verified' CHECK (code_signatory_status IN ('confirmed','not_confirmed','not_programme_verified','unknown')),
  code_signatory_source_url text,
  student_visa_context text,
  post_study_work_context text,
  post_study_work_rule_effective_date date,
  intake_label text,
  intake_start_date date,
  application_deadline date,
  admission_source_url text,
  international_source_url text,
  visa_source_url text,
  verification_status text NOT NULL DEFAULT 'programme_identity_verified_context_pending' CHECK (verification_status IN ('verified','programme_identity_verified_context_pending','review_required','rejected')),
  source_checked_at date NOT NULL,
  verified_at timestamptz,
  reviewer_note text
);

COMMENT ON TABLE public.program_catalog_nz_staging IS 'Server-only NZ Phase 2 bounded programme collection. Rows must be relevant to CampCareer target occupations; no canonical publication occurs in Phase 2.';
COMMENT ON TABLE public.program_occupation_nz_staging IS 'Server-only reviewed NZ programme-to-CampCareer-career staging relations.';
COMMENT ON TABLE public.program_international_nz_staging IS 'Server-only NZ programme international-study context. Programme existence, Code signatory context, admission state and post-study work context remain separate.';

ALTER TABLE public.program_catalog_nz_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_occupation_nz_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_international_nz_staging ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.program_catalog_nz_staging FROM public, anon, authenticated;
REVOKE ALL ON public.program_occupation_nz_staging FROM public, anon, authenticated;
REVOKE ALL ON public.program_international_nz_staging FROM public, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_catalog_nz_staging TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_occupation_nz_staging TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_international_nz_staging TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
