-- Singapore Engineering / Manufacturing occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:civil-engineer','SG','civil-engineer','Civil engineer','SSOC','2024','21421','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:mechanical-engineer','SG','mechanical-engineer','Mechanical engineer','SSOC','2024','21441','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:electrical-engineer','SG','electrical-engineer','Electrical engineer','SSOC','2024','21511','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:manufacturing-engineer','SG','manufacturing-engineer','Manufacturing engineer','SSOC','2024','21411','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:industrial-engineer','SG','industrial-engineer','Industrial engineer — industrial/production engineering umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:chemical-engineer','SG','chemical-engineer','Chemical engineer — general chemical-process scope','SSOC','2024','21451','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:environmental-engineer','SG','environmental-engineer','Environmental engineer','SSOC','2024','21430','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:engineering-technician','SG','engineering-technician','Engineering technician — multidisciplinary technician umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:civil-engineer','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the canonical role directly to 21421 Civil engineer; 21422 Building construction engineer remains separate.','entry_level_basis','Professional civil-engineering degrees provide direct preparation and four approved Singapore programmes are retained as direct study pathways.','qualification_note','The broad employee occupation is not universally limited to individually registered Professional Engineers. Under the Professional Engineers Act, prescribed professional engineering work in civil engineering must be performed by a registered PE with a practising certificate or by a person working under such a PE''s direction or supervision.','market_scope','No exact shortage, vacancy, earnings or growth series is scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:mechanical-engineer','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the canonical general role directly to 21441 Mechanical engineer, distinct from industrial machinery/tools, HVAC and transport engineering occupations.','entry_level_basis','Professional mechanical-engineering degrees provide direct preparation and four approved programmes are direct study pathways.','qualification_note','Mechanical engineering is a prescribed branch under the Professional Engineers Act for regulated professional engineering work, but employees may work under the direction or supervision of a registered PE; therefore the broad occupation is not treated as universally requiring each worker to hold PE registration.','market_scope','No market components are inferred from registration or programme availability.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:electrical-engineer','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the canonical general role directly to 21511 Electrical engineer; power generation/distribution engineer 21512 and lift engineer 21513 remain separate occupations.','entry_level_basis','Electrical and electronic engineering study provides direct preparation; five approved programmes are retained as direct study pathways.','qualification_note','Electrical engineering is a prescribed PE branch for regulated professional engineering work, while Energy Market Authority Licensed Electrical Worker requirements apply to defined electrical-work scopes. These rules do not mean every person employed under SSOC 21511 must personally hold both registrations.','market_scope','No demand or earnings credit is inferred from regulatory status.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:manufacturing-engineer','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 directly identifies 21411 Manufacturing engineer within Industrial and Production Engineers. Production, automation, quality and process engineering remain separate five-digit occupations.','entry_level_basis','Manufacturing, mechanical, materials and industrial-systems engineering study provide relevant preparation; five approved programmes are related academic pathways.','qualification_note','Manufacturing engineering is not itself one of the prescribed PE registration branches. Particular work may cross into regulated mechanical, electrical, chemical or civil professional engineering scopes, but that does not create universal personal registration for all manufacturing engineers.','market_scope','No exact current labour-market series has yet been normalised into SG v1.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:industrial-engineer','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 has the 2141 Industrial and Production Engineers unit group but no single five-digit occupation titled Industrial engineer. CampCareer preserves representative manufacturing 21411, production 21412, quality 21414 and process 21415 scopes rather than inventing an exact code.','entry_level_basis','Industrial and systems engineering, engineering systems and operations-oriented study provide relevant preparation; three approved programmes are related pathways.','qualification_note','Industrial engineering is not a standalone prescribed PE registration branch. Regulated work that substantively falls within civil, electrical, mechanical or chemical professional engineering remains subject to those legal boundaries.','market_scope','The four reference occupations are not merged into a fabricated exact Industrial Engineer market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:chemical-engineer','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The primary general chemical-engineering anchor is SSOC 21451 Chemical engineer excluding petroleum and petrochemical. 21452 petroleum and 21453 petrochemical are retained as related classification references, not silently rolled into the primary general code.','entry_level_basis','Chemical and biomolecular engineering degrees provide the core pathway; four approved programmes are related academic pathways because programme completion alone does not confer PE practice rights.','qualification_note','Chemical engineering is a prescribed branch of professional engineering work. A person independently engaging in prescribed professional engineering work must satisfy the Professional Engineers Act, while employees may perform such work under the direction or supervision of a registered PE with a practising certificate.','market_scope','General and petroleum/petrochemical codes are kept distinct and market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:environmental-engineer','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Environmental engineer directly to 21430.','entry_level_basis','Environmental and sustainability engineering study provides direct subject preparation; three approved programmes are related academic pathways under the reviewed staging relationship.','qualification_note','Environmental engineering is not itself listed as a prescribed PE registration branch. Specific designs or professional engineering services may fall within civil, chemical, electrical or mechanical prescribed work and must then comply with the relevant PE requirements.','market_scope','Environmental compliance obligations are not converted into occupation demand evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:engineering-technician','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Engineering Technician is intentionally a multidisciplinary umbrella. SSOC 2024 separates civil 31121, electrical 31131, electronics 31141, mechanical 31151, chemical 31161 and manufacturing 31171 technician occupations.','entry_level_basis','Diploma, polytechnic, technical and applied engineering pathways commonly prepare technicians; the seven reviewed university engineering programmes are kept only as related pathways rather than direct technician credentials.','qualification_note','There is no single universal Engineering Technician registration. Specific electrical, building, lift, safety, site or regulated engineering duties can impose role-specific competency or supervision requirements.','market_scope','Discipline technician codes are not aggregated into one exact salary, vacancy or shortage series in SG v1.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:civil-engineer','21421','Civil engineer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:mechanical-engineer','21441','Mechanical engineer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:electrical-engineer','21511','Electrical engineer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:manufacturing-engineer','21411','Manufacturing engineer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:industrial-engineer','21411','Manufacturing engineer — industrial engineering reference',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:industrial-engineer','21412','Production engineer — industrial engineering reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:industrial-engineer','21414','Quality control/assurance engineer — industrial engineering reference',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:industrial-engineer','21415','Process engineer — industrial engineering reference',null,null,false,4,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:chemical-engineer','21451','Chemical engineer (excluding petroleum and petrochemical)',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:chemical-engineer','21452','Chemical engineer (petroleum) — related scope',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:chemical-engineer','21453','Chemical engineer (petrochemical) — related scope',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:environmental-engineer','21430','Environmental engineer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:engineering-technician','31121','Civil engineering technician',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:engineering-technician','31131','Electrical engineering technician',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:engineering-technician','31141','Electronics engineering technician',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:engineering-technician','31151','Mechanical engineering technician',null,null,false,4,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:engineering-technician','31161','Chemical engineering technician (excluding petroleum, natural gas and petrochemical)',null,null,false,5,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:engineering-technician','31171','Manufacturing engineering technician',null,null,false,6,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','manufacturing-engineer','industrial-engineer','chemical-engineer','environmental-engineer','engineering-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','manufacturing-engineer','industrial-engineer','chemical-engineer','environmental-engineer','engineering-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','Professional Engineers Board — registration requirements','https://www1.peb.gov.sg/peregistration/requirements/','government',30,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','chemical-engineer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('civil-engineer','mechanical-engineer','electrical-engineer','manufacturing-engineer','industrial-engineer','chemical-engineer','environmental-engineer','engineering-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
