-- Canada Midwife occupation profile; canonical scope is narrower than NOC 31303.
insert into public.country_occupation_profiles(profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values('CA:midwife','CA','midwife','Physician assistants, midwives and allied health professionals','NOC','2021 Version 1.0','31303','CAD',true,'Provincial and territorial midwifery regulators','https://cmrc-ccosf.ca/registration','profile_ready','2026-08-09',now())
on conflict(profile_key) do update set official_title=excluded.official_title,official_unit_group_code=excluded.official_unit_group_code,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots(profile_key,as_of_date,employment_total,median_hourly_earnings,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values('CA:midwife','2025-11-19',null,46.81,15,0,0,0,13,10,0,10,2,50,'career-opportunity-ca-v1','provisional',jsonb_build_object('classification_scope','Midwife is a narrower occupation within NOC 31303; broader-group employment is not used.','shortage_note','COPS reports strong shortage risk for broader NOC 31303, so canonical shortage credit is capped at 15/20.','visa_basis','Current IRCC healthcare and social services category includes NOC 31303.','program_gap','Verified direct UBC and University of Manitoba midwifery programmes are currently restricted to Canadian citizens or permanent residents; no international programme link is published.'),'2026-08-09')
on conflict(profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,shortage_component=excluded.shortage_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations(profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at)
values('CA:midwife','31303','Physician assistants, midwives and allied health professionals',null,true,true,1,'https://noc.esdc.gc.ca/Structure/NOCProfile?GocTemplateCulture=en-CA&code=31303&version=2021.0','2026-08-09')
on conflict(profile_key,official_code) do update set official_title=excluded.official_title,visa_eligible=excluded.visa_eligible,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links(profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('CA:midwife','job_search','Job Bank — Midwife in Canada','https://www.jobbank.gc.ca/marketreport/wages-occupation/25500/ca','official_job_board',null,1,'2026-08-09'),
('CA:midwife','source','CMRC — Registration','https://cmrc-ccosf.ca/registration','official_regulator_network',null,1,'2026-08-09'),
('CA:midwife','source','CMRC — Canadian Midwifery Registration Exam','https://www.cmrc-ccosf.ca/registration-exam','official_regulator_network',null,2,'2026-08-09'),
('CA:midwife','source','IRCC — Express Entry category-based selection','https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/rounds-invitations/category-based-selection.html','official_immigration',null,3,'2026-08-09')
on conflict(profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,source_checked_at=excluded.source_checked_at;
