-- Canada Electrician occupation profile.
-- Exact NOC 2021 72200 Electricians (except industrial and power system).

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values ('CA:electrician','CA','electrician','Electricians (except industrial and power system)','NOC','2021 Version 1.0','72200','CAD',true,'Provincial and territorial electrical apprenticeship and certification authorities','https://red-seal.ca/eng/trades/const-elect.shtml','profile_ready','2026-08-09',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_weekly_earnings,median_hourly_earnings,annualised_median_salary,all_occupations_median_weekly,part_time_share_pct,female_share_pct,median_age,average_full_time_hours,vacancies_three_month_avg,vacancy_period,vacancy_yoy_pct,employment_growth_5y_pct,employment_growth_10y_pct,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values ('CA:electrician','2025-11-19',119300,null,35.00,null,null,null,null,null,null,null,null,null,null,null,15,0,0,0,15,8,0,10,2,50,'career-opportunity-ca-v1','provisional',jsonb_build_object('classification_scope','Exact NOC 2021 unit group 72200 Electricians (except industrial and power system).','labour_scope','COPS reports about 119,300 workers in 2023; Job Bank national median wage is CAD 35.00/hour.','shortage_note','COPS classifies NOC 72200 as MODERATE RISK OF SHORTAGE nationally for 2024-2033.','visa_basis','NOC 72200 is in the current Express Entry trade occupations category.','entry_level_basis','Construction Electrician is a Red Seal trade with a structured apprenticeship route.','entry_burden_basis','Electrical certification/licensing is jurisdictional and regulated; burden receives 2/5 rather than an unregulated-trade score.','salary_method','Exact CAD 35.00/hour earns 8/10 under Canada v1 wage bands.','vacancy_scope','Point-in-time Job Bank posting counts are not scored as a three-month vacancy series.','program_gap','courses_ca currently has no verified electrician programme record, so no programme link is fabricated.'),'2026-08-09')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,legacy_code_system,legacy_code_version,legacy_code,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at)
values ('CA:electrician','72200','Electricians (except industrial and power system)',null,null,null,null,true,true,1,'https://noc.esdc.gc.ca/Structure/NOCProfile?GocTemplateCulture=en-CA&code=72200&version=2021.0','2026-08-09')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('CA:electrician','source','NOC 2021 — Electricians 72200','https://noc.esdc.gc.ca/Structure/NOCProfile?GocTemplateCulture=en-CA&code=72200&version=2021.0','official_classification',null,1,'2026-08-09'),
('CA:electrician','source','Red Seal — Construction Electrician','https://red-seal.ca/eng/trades/const-elect.shtml','official_trade_standard',null,2,'2026-08-09'),
('CA:electrician','source','IRCC — Express Entry category-based selection','https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/rounds-invitations/category-based-selection.html','official_immigration',null,3,'2026-08-09')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
