-- Sweden Construction / Trades occupation cohort.
-- Classification basis: Standard för svensk yrkesklassificering (SSYK) 2012.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SE:carpenter','SE','carpenter','Träarbetare, snickare m.fl.','SSYK','2012','7111','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:electrician','SE','electrician','Installations- och serviceelektriker','SSYK','2012','7411','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:plumber','SE','plumber','VVS-montörer m.fl.','SSYK','2012','7125','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:wall-floor-tiler','SE','wall-floor-tiler','Murare m.fl. — plattsättare scope','SSYK','2012','7112','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:welder','SE','welder','Svetsare och gasskärare','SSYK','2012','7212','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:bricklayer','SE','bricklayer','Murare m.fl. — murare scope','SSYK','2012','7112','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:hvac-technician','SE','hvac-technician','Kyl- och värmepumpstekniker m.fl.','SSYK','2012','7126','SEK',false,null,null,'profile_ready','2026-08-12',now()),
('SE:construction-manager','SE','construction-manager','Driftchefer inom bygg, anläggning och gruva, nivå 2','SSYK','2012','1362','SEK',false,null,null,'profile_ready','2026-08-12',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SE:carpenter','2026-08-12',0,0,0,0,15,0,0,0,5,20,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 maps building carpentry directly to 7111 Träarbetare, snickare m.fl.','entry_level_basis','Carpentry is primarily a vocational and practical trade entered through construction training, workplace learning and supervised experience.','qualification_note','No universal Swedish state personal occupational licence is required for the broad carpenter role.','market_scope','No recurring carpenter shortage, vacancy, salary or growth series has yet been normalised into the common CampCareer scoring framework.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:electrician','2026-08-12',0,0,0,0,12,0,0,0,3,15,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 maps installation and service electricians directly to 7411.','entry_level_basis','Vocational electrical education, workplace learning and employer-assessed competence are common preparation routes.','qualification_note','Commercial electrical installation work must be performed by an authorised electrician or by a person covered by an electrical installation company self-audit scheme. Personal authorisation is not required for every employed electrician, while each company must have an authorised compliance electrician.','market_scope','The statutory competence framework is not converted into shortage or demand credit; recurring market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:plumber','2026-08-12',0,0,0,0,12,0,0,0,4,16,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 maps VVS installers and plumbers directly to 7125 VVS-montörer m.fl.','entry_level_basis','VVS is a vocational technical trade developed through formal training, workplace learning and trade experience.','qualification_note','There is no universal Swedish state personal plumber licence. Säker Vatten operates an industry authorisation and branch-credential framework for work delivered under its authorised-company rules.','market_scope','Arbetsförmedlingen occupation outlooks are not yet converted into the recurring common scoring components in SE v1.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:wall-floor-tiler','2026-08-12',0,0,0,0,15,0,0,0,5,20,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 code 7112 Murare m.fl. explicitly includes Kakelsättare, Klinkerläggare, Mosaikläggare and Plattsättare and covers tile setting on walls and floors.','entry_level_basis','Entry is strongly practical through construction training and supervised site work.','qualification_note','There is no universal Swedish state personal occupational licence for the broad wall and floor tiler role.','market_scope','No exact recurring tiler shortage, vacancy, salary or growth series is scored in SE v1.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:welder','2026-08-12',0,0,0,0,15,0,0,0,4,19,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 maps welders and gas cutters directly to 7212.','entry_level_basis','Welding is entered through practical process training and supervised industrial or construction experience.','qualification_note','There is no one universal Swedish state Welder licence; project, process and quality systems can require narrower welder qualifications or certifications.','market_scope','Industrial and construction welding demand is not merged into an unsupported exact occupation market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:bricklayer','2026-08-12',0,0,0,0,15,0,0,0,5,20,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 code 7112 Murare m.fl. explicitly includes Murare and Murarmästare.','entry_level_basis','Bricklaying is principally learned through vocational construction training and supervised site experience.','qualification_note','There is no universal Swedish state personal Bricklayer licence for ordinary employment.','market_scope','No exact recurring bricklayer-only market series is scored at foundation stage.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:hvac-technician','2026-08-12',0,0,0,0,12,0,0,0,2,14,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','SSYK 2012 maps refrigeration and heat-pump technicians directly to 7126 Kyl- och värmepumpstekniker m.fl.','entry_level_basis','Technical VVS and refrigeration education plus supervised installation and service experience are common preparation routes.','qualification_note','The broad occupation is not one universally licensed profession, but person certification is legally required for covered installation, leak checking, refrigerant recovery, service and maintenance on equipment containing F-gases; covered companies also require certification.','market_scope','Certification is not treated as demand evidence and recurring market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12'),
('SE:construction-manager','2026-08-12',0,0,0,0,10,0,0,0,3,13,'career-opportunity-se-v1','provisional',jsonb_build_object('classification_scope','The canonical Construction Manager is scoped to SSYK 1362 operational construction management, including Byggplatschef, Platschef and Produktionschef titles.','entry_level_basis','Built-environment or technical study can support entry, but construction-management responsibility normally requires substantial project, site, contractor and people-management experience.','qualification_note','There is no single Swedish state occupational licence that universally authorises construction managers.','market_scope','The profile does not combine 1362 with middle managers, supervisors or construction project engineers to fabricate a broader market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-12')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SE:carpenter','7111','Träarbetare, snickare m.fl.',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7111','2026-08-12'),
('SE:electrician','7411','Installations- och serviceelektriker',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7411','2026-08-12'),
('SE:plumber','7125','VVS-montörer m.fl.',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7125','2026-08-12'),
('SE:wall-floor-tiler','7112','Murare m.fl. — plattsättare scope',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7112','2026-08-12'),
('SE:welder','7212','Svetsare och gasskärare',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7212','2026-08-12'),
('SE:bricklayer','7112','Murare m.fl. — murare scope',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7112','2026-08-12'),
('SE:hvac-technician','7126','Kyl- och värmepumpstekniker m.fl.',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/7126','2026-08-12'),
('SE:construction-manager','1362','Driftchefer inom bygg, anläggning och gruva, nivå 2',null,null,true,1,'https://ssyksok.scb.se/SsykSok/SSYK2012/1362','2026-08-12')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Arbetsförmedlingen Platsbanken','https://arbetsformedlingen.se/platsbanken/','government',10,'2026-08-12' from public.country_occupation_profiles p where p.country_code='SE' and p.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SCB SSYK 2012','https://ssyksok.scb.se/SsykSok/SSYK2012','government',20,'2026-08-12' from public.country_occupation_profiles p where p.country_code='SE' and p.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SE:electrician','source','Elsäkerhetsverket — Working with electrical installations','https://www.elsakerhetsverket.se/en/professionals/authorised-electricians/working-with-electrical-installations/','government',30,'2026-08-12'),
('SE:plumber','source','Säker Vatten — Branschregler 2026:1','https://sakervatten.se/branschregler2026/','industry',30,'2026-08-12'),
('SE:hvac-technician','source','Naturvårdsverket — F-gas requirements for stationary refrigeration, air-conditioning and heat pumps','https://www.naturvardsverket.se/vagledning-och-stod/kemikalier/fluorerade-vaxthusgaser/stationar-kyl--luftkonditionerings--och-varmepumpsutrustning/','government',30,'2026-08-12')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
