-- Singapore Construction / Trades occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:carpenter','SG','carpenter','Carpenter','SSOC','2024','71151','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:electrician','SG','electrician','Electrician','SSOC','2024','74110','SGD',true,'Energy Market Authority (EMA)','https://www.ema.gov.sg/regulations-licences/licences/worker-licences/electricians-licence','profile_ready','2026-08-11',now()),
('SG:plumber','SG','plumber','Plumber','SSOC','2024','71261','SGD',true,'PUB, Singapore''s National Water Agency','https://www.pub.gov.sg/Professionals/Requirements/Licensed-Plumbers/Plumbing-Works','profile_ready','2026-08-11',now()),
('SG:wall-floor-tiler','SG','wall-floor-tiler','Floor/Wall tiler','SSOC','2024','71220','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:welder','SG','welder','Welder/Flame cutter','SSOC','2024','72120','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:bricklayer','SG','bricklayer','Bricklayer/Blocklayer','SSOC','2024','71120','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:hvac-technician','SG','hvac-technician','Air-conditioning/Refrigeration technician — mechanic/installer umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:construction-manager','SG','construction-manager','Construction manager','SSOC','2024','13230','SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:carpenter','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 provides the direct five-digit occupation 71151 Carpenter, distinct from 71152 Joiner.','entry_level_basis','Carpentry is primarily a practical trade entered through vocational or employer-based skills development and supervised work experience.','qualification_note','No universal personal occupational licence is required for the broad Carpenter role; construction-site safety and project-specific competency requirements apply separately.','market_scope','No exact current shortage, vacancy, earnings or growth series has yet been normalised into the common CampCareer scoring framework.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:electrician','2026-08-11',0,0,0,0,12,0,0,0,1,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Electrician directly to 74110.','entry_level_basis','Relevant ITE electrical training plus Singapore practical experience is a recognised route into EMA electrician licensing; experience-only pathways also exist under EMA rules.','qualification_note','EMA states that electrical works must be undertaken or carried out by a Licensed Electrical Worker of the appropriate class. The Electrician Licence has defined voltage and approved-load limits and requires the applicable experience and assessments.','market_scope','Licensing evidence is not treated as labour-demand evidence; shortage, vacancy, earnings and growth remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:plumber','2026-08-11',0,0,0,0,12,0,0,0,1,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Plumber directly to 71261 and keeps Pipe fitter at 71262 and Pipe/Drain layer at 71263.','entry_level_basis','Plumbing is a practical technical trade; the regulated professional route requires PUB Licensed Plumber competence for regulated water-service and sanitary plumbing works.','qualification_note','PUB requires all regulated water-service and sanitary plumbing works to be carried out by Licensed Plumbers, with a limited exception for simple plumbing works that handymen may perform.','market_scope','The legal requirement is not converted into shortage or demand credit; market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:wall-floor-tiler','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the canonical role directly to 71220 Floor/Wall tiler.','entry_level_basis','Entry is strongly practical and commonly developed through construction skills training and supervised site work.','qualification_note','There is no universal personal occupational licence for the broad Floor/Wall Tiler role; site and employer competency requirements remain separate.','market_scope','No exact comparable tiler shortage, vacancy, salary or growth series is scored in SG v1.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:welder','2026-08-11',0,0,0,0,15,0,0,0,3,18,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Welder/Flame cutter directly to 72120.','entry_level_basis','Welding is entered through practical process training, trade competency and supervised industrial or construction experience.','qualification_note','There is no one universal personal Welder licence covering every welding job. Process, employer, project, safety and certification requirements can differ by material and work environment.','market_scope','Construction and manufacturing welding demand is not merged into a fabricated exact occupation market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:bricklayer','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Bricklayer/Blocklayer directly to 71120.','entry_level_basis','The occupation is principally learned through practical construction skills training and supervised site experience.','qualification_note','There is no universal personal Bricklayer licence for ordinary employment; worksite safety and contractor competency requirements are separate.','market_scope','No exact comparable bricklayer market series is scored at foundation stage.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:hvac-technician','2026-08-11',0,0,0,0,12,0,0,0,4,16,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The canonical HVAC Technician spans SSOC 71271 Air-conditioning/Refrigeration equipment mechanic and 71272 Air-conditioning/Refrigeration plant installer rather than one exact five-digit code.','entry_level_basis','Mechanical, refrigeration and air-conditioning technical training plus hands-on installation and maintenance experience are common preparation routes.','qualification_note','There is no single universal personal HVAC Technician licence covering the full mechanic/installer umbrella. Electrical, pressure, refrigerant, workplace-safety or project responsibilities can impose narrower requirements.','market_scope','Mechanic and installer classifications are preserved separately rather than combined into an unsupported aggregate market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:construction-manager','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 provides the direct five-digit occupation 13230 Construction manager.','entry_level_basis','Built-environment, civil engineering and project-management study can support entry, but construction-management responsibility normally requires substantial project and site experience. Three approved Singapore programmes are retained as related study pathways.','qualification_note','The broad Construction Manager occupation is not licensed as one universal personal profession. BCA Builder Licensing applies to builders undertaking prescribed works and requires designated Approved Person and Technical Controller personnel; those statutory roles are not attributed to every construction manager.','market_scope','Builder licensing and programme availability are not treated as demand evidence; market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:carpenter','71151','Carpenter',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:electrician','74110','Electrician',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:plumber','71261','Plumber',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:wall-floor-tiler','71220','Floor/Wall tiler',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:welder','72120','Welder/Flame cutter',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:bricklayer','71120','Bricklayer/Blocklayer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hvac-technician','71271','Air-conditioning/Refrigeration equipment mechanic',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hvac-technician','71272','Air-conditioning/Refrigeration plant installer',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:construction-manager','13230','Construction manager',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:electrician','source','EMA Electrician Licence','https://www.ema.gov.sg/regulations-licences/licences/worker-licences/electricians-licence','government',30,'2026-08-11'),
('SG:plumber','source','PUB Plumbing Works and Licensed Plumbers','https://www.pub.gov.sg/Professionals/Requirements/Licensed-Plumbers/Plumbing-Works','government',30,'2026-08-11'),
('SG:construction-manager','source','BCA Builders Licensing Scheme','https://www1.bca.gov.sg/safety-and-standards/applications-and-licenses/builders-licensing-scheme-bls/','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,c.source_program_key,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('carpenter','electrician','plumber','wall-floor-tiler','welder','bricklayer','hvac-technician','construction-manager')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
