insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('IE:carpenter','IE','carpenter','Carpenters and joiners','SOC','SOC 2010','5315','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:electrician','IE','electrician','Electricians and electrical fitters','SOC','SOC 2010','5241','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:plumber','IE','plumber','Plumbers and heating and ventilating engineers','SOC','SOC 2010','5314','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:wall-floor-tiler','IE','wall-floor-tiler','Floorers and wall tilers','SOC','SOC 2010','5322','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:welder','IE','welder','Welding trades','SOC','SOC 2010','5215','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:bricklayer','IE','bricklayer','Bricklayers and masons','SOC','SOC 2010','5312','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:hvac-technician','IE','hvac-technician','Air-conditioning and refrigeration engineers','SOC','SOC 2010','5225','EUR',false,null,null,'profile_ready','2026-08-10',now()),
('IE:construction-manager','IE','construction-manager','Construction project managers and related professionals','SOC','SOC 2010','2436','EUR',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('IE:carpenter','2026-08-10',null,null,null,15,0,0,0,12,0,0,6,4,37,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5315 Carpenters and joiners.','shortage_basis','SOLAS National Skills Bulletin 2025 identifies Carpenters as a current shortage; 15/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised. Construction SEO statutory minimum rates are not treated as median salary; 0/10.','entry_basis','National Carpentry and Joinery craft apprenticeship; 12/15.','entry_burden_basis','No universal professional register; Safe Pass is a separate mandatory site-safety credential; 4/5.'),'2026-08-10'),
('IE:electrician','2026-08-10',null,null,null,8,0,0,0,12,0,0,6,2,28,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5241 Electricians and electrical fitters.','shortage_basis','SOLAS National Skills Bulletin 2025 identifies Electricians as a potential future skills shortage; 8/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','National Electrical craft apprenticeship; 12/15.','entry_burden_basis','Restricted electrical works/electrical contracting are regulated through CRU Safe Electric and require REC scope; 2/5.'),'2026-08-10'),
('IE:plumber','2026-08-10',null,null,null,8,0,0,0,12,0,0,6,3,29,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5314 Plumbers and heating and ventilating engineers.','shortage_basis','SOLAS National Skills Bulletin 2025 identifies Plumbers as a potential future skills shortage; 8/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','National Plumbing craft apprenticeship; 12/15.','entry_burden_basis','General plumbing has no universal register, but regulated gas works require RGI registration; 3/5.'),'2026-08-10'),
('IE:wall-floor-tiler','2026-08-10',null,null,null,0,0,0,0,8,0,0,6,4,18,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5322 Floorers and wall tilers.','shortage_basis','No exact current shortage finding in the SOLAS 2025 construction summary; broader construction demand is not inherited; 0/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','No dedicated exact craft apprenticeship is asserted from the current national apprenticeship directory; trade competence plus site-safety requirements; 8/15.','entry_burden_basis','No universal professional register; Safe Pass applies to construction-site workers; 4/5.'),'2026-08-10'),
('IE:welder','2026-08-10',null,null,null,15,0,0,0,10,0,0,6,4,35,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5215 Welding trades.','shortage_basis','SOLAS National Skills Bulletin 2025 identifies Welders/fabricators as a current shortage; 15/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','Metal Fabrication national craft apprenticeship is retained as a related structured welding pathway, not a one-to-one equivalence; 10/15.','entry_burden_basis','No universal statutory welder register; project/process qualifications and Safe Pass can apply by setting; 4/5.'),'2026-08-10'),
('IE:bricklayer','2026-08-10',null,null,null,0,0,0,0,12,0,0,6,4,22,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5312 Bricklayers and masons.','shortage_basis','No separate exact shortage finding in the SOLAS 2025 construction summary; wider housing pressure is not converted into occupation points; 0/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','National Brick and Stonelaying craft apprenticeship; 12/15.','entry_burden_basis','No universal professional register; Safe Pass applies to construction-site workers; 4/5.'),'2026-08-10'),
('IE:hvac-technician','2026-08-10',null,null,null,0,0,0,0,12,0,0,6,2,20,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 5225 Air-conditioning and refrigeration engineers.','shortage_basis','No exact current HVAC shortage finding is asserted from the reviewed SOLAS 2025 summaries; 0/20.','visa_basis','Outside the current Ineligible List; General Employment Permit route can apply subject to normal criteria; 6/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','National Refrigeration craft apprenticeship; 12/15.','entry_burden_basis','Covered F-gas installation/service/repair/recovery work requires appropriate personnel certification; 2/5.'),'2026-08-10'),
('IE:construction-manager','2026-08-10',null,null,null,15,0,0,0,6,0,0,10,4,35,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','Primary SOC 2010 2436 Construction project managers and related professionals, with SOC 1122 Site Manager retained as an included management scope.','shortage_basis','SOLAS National Skills Bulletin 2025 identifies Construction project managers as a current shortage; 15/20.','visa_basis','Current Critical Skills Occupations List includes SOC 2436 Construction project managers and SOC 1122 Site Manager; 10/10.','salary_method','No exact current occupation-level median earnings series is normalised; 0/10.','entry_basis','Degree/technical education and substantial construction-project experience are common; no unverified Ireland university programme is published from the current programme cohort; 6/15.','entry_burden_basis','No universal statutory construction-manager register; project/site competence and Safe Pass rules may apply; 4/5.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('IE:carpenter','5315','Carpenters and joiners',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:electrician','5241','Electricians and electrical fitters',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:plumber','5314','Plumbers and heating and ventilating engineers',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:wall-floor-tiler','5322','Floorers and wall tilers',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:welder','5215','Welding trades',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:bricklayer','5312','Bricklayers and masons',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:hvac-technician','5225','Air-conditioning and refrigeration engineers',null,true,true,1,'https://www.cso.ie/en/releasesandpublications/ep/p-cp11eoi/cp11eoi/bgn/','2026-08-10'),
('IE:construction-manager','2436','Construction project managers / Construction Planner / Construction Scheduler',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
('IE:construction-manager','1122','Site Manager',null,true,true,2,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('IE:carpenter','entry_program','Generation Apprenticeship — Carpentry and Joinery craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','official_training',null,1,'2026-08-10'),
('IE:electrician','entry_program','Generation Apprenticeship — Electrical craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','official_training',null,1,'2026-08-10'),
('IE:plumber','entry_program','Generation Apprenticeship — Plumbing craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','official_training',null,1,'2026-08-10'),
('IE:welder','entry_program','Generation Apprenticeship — Metal Fabrication craft route (related welding pathway)','https://apprenticeship.ie/craft-apprenticeship-training-locations','official_training',null,1,'2026-08-10'),
('IE:bricklayer','entry_program','Generation Apprenticeship — Brick and Stonelaying craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','official_training',null,1,'2026-08-10'),
('IE:hvac-technician','entry_program','Generation Apprenticeship — Refrigeration craft route','https://apprenticeship.ie/craft-apprenticeship-training-locations','official_training',null,1,'2026-08-10'),
('IE:carpenter','source','SOLAS — Construction occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/construction/','official_labour',null,2,'2026-08-10'),
('IE:electrician','source','SOLAS — Other Craft occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/other-craft/','official_labour',null,2,'2026-08-10'),
('IE:plumber','source','SOLAS — Construction occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/construction/','official_labour',null,2,'2026-08-10'),
('IE:wall-floor-tiler','source','SOLAS — Construction occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/construction/','official_labour',null,2,'2026-08-10'),
('IE:welder','source','SOLAS — Other Craft occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/other-craft/','official_labour',null,2,'2026-08-10'),
('IE:bricklayer','source','SOLAS — Construction occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/construction/','official_labour',null,2,'2026-08-10'),
('IE:hvac-technician','source','SOLAS — National Skills Bulletin 2025 research library','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/research/','official_labour',null,2,'2026-08-10'),
('IE:construction-manager','source','SOLAS — Construction occupation shortage summary','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/construction/','official_labour',null,2,'2026-08-10'),
('IE:carpenter','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:electrician','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:plumber','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:wall-floor-tiler','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:welder','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:bricklayer','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:hvac-technician','source','DETE — General Employment Permit','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/permit-types/general-employment-permit/','official_immigration',null,3,'2026-08-10'),
('IE:construction-manager','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','official_immigration',null,3,'2026-08-10'),
('IE:carpenter','source','SOLAS — Safe Pass','https://www.solas.ie/construction-lp/safe-pass/','official_regulator',null,4,'2026-08-10'),
('IE:electrician','source','CRU — RGI and Safe Electric schemes','https://www.cru.ie/regulations-policy/safety/rgi-and-safe-electric/','official_regulator',null,4,'2026-08-10'),
('IE:plumber','source','CRU — RGI and Safe Electric schemes','https://www.cru.ie/regulations-policy/safety/rgi-and-safe-electric/','official_regulator',null,4,'2026-08-10'),
('IE:wall-floor-tiler','source','SOLAS — Safe Pass','https://www.solas.ie/construction-lp/safe-pass/','official_regulator',null,4,'2026-08-10'),
('IE:welder','source','SOLAS — Safe Pass for construction-site scope','https://www.solas.ie/construction-lp/safe-pass/','official_regulator',null,4,'2026-08-10'),
('IE:bricklayer','source','SOLAS — Safe Pass','https://www.solas.ie/construction-lp/safe-pass/','official_regulator',null,4,'2026-08-10'),
('IE:hvac-technician','source','EPA — F-gas training and qualifications','https://www.epa.ie/our-services/compliance--enforcement/air/fluorinated-greenhouse-gases-f-gases/training--qualifications-for-ods-and-f-gases/','official_regulator',null,4,'2026-08-10'),
('IE:construction-manager','source','CSO — SOC2010 occupation classification','https://www.cso.ie/en/releasesandpublications/ep/p-lfs/labourforcesurveyquarter12026/backgroundnotes/','official_labour',null,4,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
