-- Singapore Health occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.
-- Also normalises Singapore programme refs to sg-program:<catalog_id> so duplicate source_program_key values cannot collide.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:registered-nurse','SG','registered-nurse','Registered nurse and related nursing professional — registered nurse scope','SSOC','2024','22200','SGD',true,'Singapore Nursing Board (SNB)','https://www.snb.gov.sg/for-professionals/for-nurses-and-midwives/registers-of-nurses-midwives-roll-of-nurses/','profile_ready','2026-08-11',now()),
('SG:midwife','SG','midwife','Registered midwife — nursing-professional reference scope','SSOC','2024',null,'SGD',true,'Singapore Nursing Board (SNB)','https://www.snb.gov.sg/for-professionals/for-nurses-and-midwives/registers-of-nurses-midwives-roll-of-nurses/','profile_ready','2026-08-11',now()),
('SG:care-worker','SG','care-worker','Care worker — healthcare assistant/nursing aide/personal-care umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:physiotherapist','SG','physiotherapist','Physiotherapist','SSOC','2024','22640','SGD',true,'Allied Health Professions Council (AHPC)','https://www.ahpc.gov.sg/for-professionals/registers-of-allied-health-professionals/','profile_ready','2026-08-11',now()),
('SG:medical-laboratory-technician','SG','medical-laboratory-technician','Medical/Pathology laboratory technician','SSOC','2024','32120','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:radiographer','SG','radiographer','Diagnostic radiographer','SSOC','2024','22693','SGD',true,'Allied Health Professions Council (AHPC)','https://www.ahpc.gov.sg/for-professionals/registers-of-allied-health-professionals/','profile_ready','2026-08-11',now()),
('SG:pharmacist','SG','pharmacist','Pharmacist (patient care)','SSOC','2024','22621','SGD',true,'Singapore Pharmacy Council (SPC)','https://www.spc.gov.sg/for-professionals/apply-for-registration/','profile_ready','2026-08-11',now()),
('SG:occupational-therapist','SG','occupational-therapist','Occupational therapist','SSOC','2024','22680','SGD',true,'Allied Health Professions Council (AHPC)','https://www.ahpc.gov.sg/for-professionals/registers-of-allied-health-professionals/','profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:registered-nurse','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Registered nurse and related nursing professional (excluding enrolled nurse) to 22200. This canonical profile is restricted to the registered-nurse scope and does not include enrolled nurses.','entry_level_basis','An accredited nursing qualification followed by SNB registration and a valid Practising Certificate is the direct professional route. Three reviewed Singapore nursing programmes are retained as direct study pathways.','qualification_note','Under the Nurses and Midwives Act, a person must be registered with SNB and hold a valid Practising Certificate to practise nursing in Singapore.','market_scope','Professional registration and programme availability are not treated as shortage or demand evidence in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:midwife','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 does not publish a standalone five-digit Midwife occupation in its classification structure. CampCareer therefore leaves the primary code null and uses 22200 only as a non-rollup nursing-professional reference.','entry_level_basis','Singapore Nursing Board lists midwifery as a post-registration route for Registered Nurses; the current locally accredited route includes an Advanced Diploma in Nursing (Midwifery) followed by application for Registered Midwife registration.','qualification_note','A person must be registered as a midwife with SNB and possess a valid Practising Certificate before practising midwifery in Singapore.','market_scope','The shared nursing-professional classification is not treated as an exact Midwife labour-market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:care-worker','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The broad Care Worker role spans SSOC 53201 Healthcare assistant, 53202 Nursing aide/assistant and 53209 Healthcare assistant and related personal care worker n.e.c.; no one five-digit code covers all home, community and facility support tasks in the canonical role.','entry_level_basis','Care work is commonly entered through employer training, caregiving or healthcare-support qualifications and supervised workplace experience. Five reviewed nursing/social-work programmes are related educational context rather than occupational qualifications.','qualification_note','There is no single statutory professional registration scheme for the broad Care Worker occupation. Employers and care settings can impose role-specific training, screening and competency requirements.','market_scope','Healthcare-assistant and nursing-aide classifications are preserved separately and are not merged into one unsupported exact market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:physiotherapist','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Physiotherapist directly to 22640.','entry_level_basis','A recognised entry-to-practice physiotherapy qualification is required. AHPC registration applicants must possess the relevant professional qualification and meet the Council requirements; one reviewed Singapore programme is retained as direct.','qualification_note','Physiotherapists are regulated under the Allied Health Professions Act and must be registered with AHPC and hold a valid Practising Certificate before practising.','market_scope','Registration evidence is not converted into shortage or demand credit; market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:medical-laboratory-technician','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 directly maps Medical/Pathology laboratory technician to 32120. The separate professional-level 21342 Medical laboratory scientist is not rolled into this technician profile.','entry_level_basis','Relevant laboratory or biomedical-science technician education plus supervised laboratory competency provides the clearest entry route; no approved Singapore programme link is currently attached to this canonical technician profile.','qualification_note','Medical Laboratory Technician is not among the healthcare professions currently regulated by the statutory Professional Boards listed by Singapore MOH. Laboratories and employers can still impose qualification, competency, biosafety and quality requirements.','market_scope','The technician and scientist levels are kept separate and no exact shortage, vacancy, salary or growth series is scored yet.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:radiographer','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Diagnostic radiographer directly to 22693. Radiation therapist is a separate occupation at 22694 and is not included in the canonical Radiographer classification.','entry_level_basis','A recognised diagnostic-radiography qualification followed by AHPC registration is the direct professional route. Two staging programmes are reviewed as common pathways and are therefore conservatively retained as related, including the separate Radiation Therapy programme.','qualification_note','Diagnostic Radiographers must be registered with AHPC and hold a valid Practising Certificate before practising in Singapore.','market_scope','The separate radiation-therapy occupation and programme are not merged into radiographer market evidence.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:pharmacist','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The canonical patient-facing Pharmacist role maps to SSOC 22621 Pharmacist (patient care). SSOC 22629 Pharmacist n.e.c. is not automatically rolled into this profile.','entry_level_basis','A Singapore Pharmacy Council-recognised pharmacy degree is followed by prescribed practical experience and the applicable registration route. One reviewed Singapore Pharmacy programme is retained as direct.','qualification_note','Pharmacists must meet SPC registration requirements; a pharmacy degree alone does not automatically confer unrestricted practice. Foreign-trained applicants can require recognised qualifications, local practical experience, examinations and conditional registration.','market_scope','Patient-care pharmacy is kept separate from residual pharmacist scopes and market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:occupational-therapist','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Occupational therapist directly to 22680.','entry_level_basis','A recognised occupational-therapy qualification followed by AHPC registration is the direct professional route. One reviewed Singapore Occupational Therapy programme is retained as direct.','qualification_note','Occupational Therapists are regulated under the Allied Health Professions Act and must be registered with AHPC and hold a valid Practising Certificate before practising.','market_scope','Registration and programme evidence are not treated as shortage, vacancy or salary evidence in foundation scoring.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:registered-nurse','22200','Registered nurse and related nursing professional — registered nurse scope',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:midwife','22200','Nursing professional reference — Midwife has no standalone SSOC 2024 five-digit code',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:care-worker','53201','Healthcare assistant',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:care-worker','53202','Nursing aide/assistant',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:care-worker','53209','Healthcare assistant and related personal care worker n.e.c.',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:physiotherapist','22640','Physiotherapist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:medical-laboratory-technician','32120','Medical/Pathology laboratory technician',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:radiographer','22693','Diagnostic radiographer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:pharmacist','22621','Pharmacist (patient care)',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:occupational-therapist','22680','Occupational therapist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('registered-nurse','midwife','care-worker','physiotherapist','medical-laboratory-technician','radiographer','pharmacist','occupational-therapist')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('registered-nurse','midwife','care-worker','physiotherapist','medical-laboratory-technician','radiographer','pharmacist','occupational-therapist')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:registered-nurse','source','Singapore Nursing Board — Registers of Nurses and Midwives','https://www.snb.gov.sg/for-professionals/for-nurses-and-midwives/registers-of-nurses-midwives-roll-of-nurses/','government',30,'2026-08-11'),
('SG:midwife','source','Singapore Nursing Board — Registers of Nurses and Midwives','https://www.snb.gov.sg/for-professionals/for-nurses-and-midwives/registers-of-nurses-midwives-roll-of-nurses/','government',30,'2026-08-11'),
('SG:midwife','source','Singapore Nursing Board — Programmes leading to registration','https://www.snb.gov.sg/for-professionals/becoming-a-nurse-or-midwife/accredited-nursing-programmes/programmes-leading-to-registration-enrolment/','government',31,'2026-08-11'),
('SG:physiotherapist','source','Allied Health Professions Council — Registers','https://www.ahpc.gov.sg/for-professionals/registers-of-allied-health-professionals/','government',30,'2026-08-11'),
('SG:radiographer','source','Allied Health Professions Council — Registers','https://www.ahpc.gov.sg/for-professionals/registers-of-allied-health-professionals/','government',30,'2026-08-11'),
('SG:occupational-therapist','source','Allied Health Professions Council — Registers','https://www.ahpc.gov.sg/for-professionals/registers-of-allied-health-professionals/','government',30,'2026-08-11'),
('SG:pharmacist','source','Singapore Pharmacy Council — Registration','https://www.spc.gov.sg/for-professionals/apply-for-registration/','government',30,'2026-08-11'),
('SG:medical-laboratory-technician','source','MOH — Healthcare Professionals Regulation','https://www.moh.gov.sg/others/health-regulation/healthcare-professionals-regulation/','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

-- Normalise the already-applied Construction programme refs, then use the same collision-safe convention for Health.
delete from public.country_occupation_program_links where profile_key='SG:construction-manager';
insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id='construction-manager'
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;

delete from public.country_occupation_program_links where profile_key in ('SG:registered-nurse','SG:midwife','SG:care-worker','SG:physiotherapist','SG:medical-laboratory-technician','SG:radiographer','SG:pharmacist','SG:occupational-therapist');
insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('registered-nurse','midwife','care-worker','physiotherapist','medical-laboratory-technician','radiographer','pharmacist','occupational-therapist')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
