-- UAE program collection snapshot as verified on 2026-08-09.
-- Program-provider institutions below support program provenance only; the selective /institutions/ae publication cohort remains unchanged.

with providers(slug,name,kind,website,city,identifier_system,identifier_value,source_url) as (values
('ajman-university','Ajman University','university','https://www.ajman.ac.ae/','Ajman','AE_CAA_PROGRAM_PROVIDER_NAME','AJMAN UNIVERSITY','https://www.caa.ae/Pages/Programs/All.aspx'),
('fakeeh-college-medical-sciences-dubai','Fakeeh College for Medical Sciences – Dubai','college','https://en.fakeeh.care/educations/fakeeh-college-for-medical-sciences','Dubai','AE_CAA_PROGRAM_PROVIDER_NAME','FAKEEH COLLEGE FOR MEDICAL SCIENCES – DUBAI','https://www.caa.ae/Pages/Programs/All.aspx'),
('american-university-in-the-emirates','American University in the Emirates','university','https://aue.ae/','Dubai','AE_CAA_PROGRAM_PROVIDER_NAME','AMERICAN UNIVERSITY IN THE EMIRATES','https://www.caa.ae/Pages/Programs/All.aspx'),
('emirates-college-for-advanced-education','Emirates College for Advanced Education','college','https://www.ecae.ac.ae/','Abu Dhabi','AE_CAA_PROGRAM_PROVIDER_NAME','EMIRATES COLLEGE FOR ADVANCED EDUCATION','https://www.caa.ae/Pages/Programs/All.aspx'),
('fujairah-university','Fujairah University','university','https://fu.ac.ae/','Fujairah','AE_CAA_PROGRAM_PROVIDER_NAME','FUJAIRAH UNIVERSITY (FORMERLY: UNIVERSITY OF FUJAIRAH)','https://www.caa.ae/Pages/Programs/All.aspx'),
('abu-dhabi-hospitality-academy-les-roches','Abu Dhabi Hospitality Academy – Les Roches','college','https://lesroches.edu/campuses/abu-dhabi/','Abu Dhabi','AE_CAA_PROGRAM_PROVIDER_NAME','ABU DHABI HOSPITALITY ACADEMY – LES ROCHES','https://www.caa.ae/Pages/Programs/All.aspx'),
('emirates-aviation-university','Emirates Aviation University','university','https://www.eau.ac.ae/','Dubai','AE_CAA_PROGRAM_PROVIDER_NAME','EMIRATES AVIATION UNIVERSITY','https://www.caa.ae/Pages/Programs/All.aspx'),
('sharjah-maritime-academy','Sharjah Maritime Academy','college','https://www.sma.ac.ae/','Khor Fakkan','AE_CAA_PROGRAM_PROVIDER_NAME','SHARJAH MARITIME ACADEMY','https://www.caa.ae/Pages/Programs/All.aspx'),
('dubai-college-of-tourism','Dubai College of Tourism','college','https://dct.ac.ae/','Dubai','AE_MOE_TVET_PROGRAM_PROVIDER_NAME','DUBAI COLLEGE OF TOURISM','https://u.ae/en/information-and-services/education/technical-and-vocational-education'),
('emirates-flight-training-academy','Emirates Flight Training Academy','other','https://www.emiratesflighttrainingacademy.com/en','Dubai','AE_GCAA_TRAINING_PROVIDER_NAME','EMIRATES FLIGHT TRAINING ACADEMY','https://www.gcaa.gov.ae/en/departments/as/licensing')
)
insert into catalog.institutions(id,country_code,canonical_name,institution_type,website_url,status,slug,institution_kind,ownership_type,created_at,updated_at)
select md5('AE|program-provider|'||slug)::uuid,'AE',name,null,website,'active',slug,kind,null,now(),now()
from providers p
where not exists(select 1 from catalog.institutions i where i.country_code='AE' and i.slug=p.slug);

with providers(slug,identifier_system,identifier_value,source_url) as (values
('ajman-university','AE_CAA_PROGRAM_PROVIDER_NAME','AJMAN UNIVERSITY','https://www.caa.ae/Pages/Programs/All.aspx'),
('fakeeh-college-medical-sciences-dubai','AE_CAA_PROGRAM_PROVIDER_NAME','FAKEEH COLLEGE FOR MEDICAL SCIENCES – DUBAI','https://www.caa.ae/Pages/Programs/All.aspx'),
('american-university-in-the-emirates','AE_CAA_PROGRAM_PROVIDER_NAME','AMERICAN UNIVERSITY IN THE EMIRATES','https://www.caa.ae/Pages/Programs/All.aspx'),
('emirates-college-for-advanced-education','AE_CAA_PROGRAM_PROVIDER_NAME','EMIRATES COLLEGE FOR ADVANCED EDUCATION','https://www.caa.ae/Pages/Programs/All.aspx'),
('fujairah-university','AE_CAA_PROGRAM_PROVIDER_NAME','FUJAIRAH UNIVERSITY (FORMERLY: UNIVERSITY OF FUJAIRAH)','https://www.caa.ae/Pages/Programs/All.aspx'),
('abu-dhabi-hospitality-academy-les-roches','AE_CAA_PROGRAM_PROVIDER_NAME','ABU DHABI HOSPITALITY ACADEMY – LES ROCHES','https://www.caa.ae/Pages/Programs/All.aspx'),
('emirates-aviation-university','AE_CAA_PROGRAM_PROVIDER_NAME','EMIRATES AVIATION UNIVERSITY','https://www.caa.ae/Pages/Programs/All.aspx'),
('sharjah-maritime-academy','AE_CAA_PROGRAM_PROVIDER_NAME','SHARJAH MARITIME ACADEMY','https://www.caa.ae/Pages/Programs/All.aspx'),
('dubai-college-of-tourism','AE_MOE_TVET_PROGRAM_PROVIDER_NAME','DUBAI COLLEGE OF TOURISM','https://u.ae/en/information-and-services/education/technical-and-vocational-education'),
('emirates-flight-training-academy','AE_GCAA_TRAINING_PROVIDER_NAME','EMIRATES FLIGHT TRAINING ACADEMY','https://www.gcaa.gov.ae/en/departments/as/licensing')
)
insert into catalog.institution_identifiers(institution_id,identifier_system,identifier_value,source_url,valid_from)
select i.id,p.identifier_system,p.identifier_value,p.source_url,'2026-08-09'::date
from providers p join catalog.institutions i on i.country_code='AE' and i.slug=p.slug
on conflict(identifier_system,identifier_value) do update set institution_id=excluded.institution_id,source_url=excluded.source_url,valid_from=excluded.valid_from;

with providers(slug,city,website,source_url) as (values
('ajman-university','Ajman','https://www.ajman.ac.ae/','https://www.ajman.ac.ae/en/pharmacy'),
('fakeeh-college-medical-sciences-dubai','Dubai','https://en.fakeeh.care/educations/fakeeh-college-for-medical-sciences','https://en.fakeeh.care/educations/fakeeh-college-for-medical-sciences'),
('american-university-in-the-emirates','Dubai','https://aue.ae/','https://aue.ae/college-of-health-sciences/'),
('emirates-college-for-advanced-education','Abu Dhabi','https://www.ecae.ac.ae/','https://www.ecae.ac.ae/en/academics/applynow/'),
('fujairah-university','Fujairah','https://fu.ac.ae/','https://fu.ac.ae/'),
('abu-dhabi-hospitality-academy-les-roches','Abu Dhabi','https://lesroches.edu/campuses/abu-dhabi/','https://lesroches.edu/campuses/abu-dhabi/'),
('emirates-aviation-university','Dubai','https://www.eau.ac.ae/','https://www.eau.ac.ae/'),
('sharjah-maritime-academy','Khor Fakkan','https://www.sma.ac.ae/','https://www.sma.ac.ae/undergraduate'),
('dubai-college-of-tourism','Dubai','https://dct.ac.ae/','https://dct.ac.ae/en/about-dct/'),
('emirates-flight-training-academy','Dubai','https://www.emiratesflighttrainingacademy.com/en','https://www.emiratesflighttrainingacademy.com/en/admissions/')
)
insert into catalog.campuses(id,institution_id,name,city,region,country_code,status,locality,official_url,source_url,source_checked_at,metadata)
select md5('AE|program-provider-campus|'||p.slug)::uuid,i.id,'Primary program publication location',p.city,null,'AE','active',p.city,p.website,p.source_url,'2026-08-09'::timestamptz,jsonb_build_object('scope','program-provider-publication-location','complete_campus_inventory',false)
from providers p join catalog.institutions i on i.country_code='AE' and i.slug=p.slug
where not exists(select 1 from catalog.campuses c where c.id=md5('AE|program-provider-campus|'||p.slug)::uuid);

with seed(source_name,source_program_key,institution_name,title,programme_level,credential_type,field_name,emirate,city,duration_years,tuition_fee_aed,official_program_url,caa_detail_url,source_url,source_as_of,collection_status,verification_tier) as (values
('CAA+institution','ajman:bsc-physiotherapy','Ajman University','Bachelor of Science in Physiotherapy','BACHELOR','Bachelor of Science','Health Sciences','Ajman','Ajman',null,null,'https://www.ajman.ac.ae/en/pharmacy','https://caa.ae/Pages/Programs/Details.aspx?GUID=8868','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','ajman:doctor-pharmacy','Ajman University','Doctor of Pharmacy','MASTER','Doctor of Pharmacy','Health Sciences','Ajman','Ajman',null,null,'https://www.ajman.ac.ae/en/pharmacy',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','aue:bsc-digital-animation','American University in the Emirates','Bachelor of Science in Digital Animation','BACHELOR','Bachelor of Science','Art and Design','Dubai','Dubai',null,null,'https://aue.ae/','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=561','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','aue:bsc-medical-diagnostic-imaging','American University in the Emirates','Bachelor of Science in Medical Diagnostic Imaging','BACHELOR','Bachelor of Science','Health Sciences','Dubai','Dubai',null,null,'https://aue.ae/college-of-health-sciences/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','aue:bsc-medical-laboratory-sciences','American University in the Emirates','Bachelor of Science in Medical Laboratory Sciences','BACHELOR','Bachelor of Science','Health Sciences','Dubai','Dubai',null,null,'https://aue.ae/college-of-health-sciences/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','aus:b-interior-design','American University of Sharjah','Bachelor of Interior Design','BACHELOR','Bachelor','Art and Design','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:ba-mass-communication','American University of Sharjah','Bachelor of Arts in Mass Communication','BACHELOR','Bachelor of Arts','Communication/Media','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:ba-psychology','American University of Sharjah','Bachelor of Arts in Psychology','BACHELOR','Bachelor of Arts','Social/Behavioural','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:barch','American University of Sharjah','Bachelor of Architecture','BACHELOR','Bachelor of Architecture','Art and Design','Sharjah','Sharjah',null,null,'https://www.aus.edu/caad/department-of-architecture/bachelor-of-architecture',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','aus:bsba-accounting','American University of Sharjah','Bachelor of Science in Business Administration in Accounting','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsba-economics','American University of Sharjah','Bachelor of Science in Business Administration in Economics','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsba-finance','American University of Sharjah','Bachelor of Science in Business Administration in Finance','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsba-is-business-analytics','American University of Sharjah','Bachelor of Science in Business Administration in Information Systems and Business Analytics','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsba-management','American University of Sharjah','Bachelor of Science in Business Administration in Management','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsba-marketing','American University of Sharjah','Bachelor of Science in Business Administration in Marketing','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsba-supply-chain','American University of Sharjah','Bachelor of Science in Business Administration in Supply Chain Management','BACHELOR','Bachelor of Science','Business/Management','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-chemical-biological-engineering','American University of Sharjah','Bachelor of Science in Chemical and Biological Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-chemical-engineering','American University of Sharjah','Bachelor of Science in Chemical Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-civil-engineering','American University of Sharjah','Bachelor of Science in Civil Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-computer-engineering','American University of Sharjah','Bachelor of Science in Computer Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-computer-science','American University of Sharjah','Bachelor of Science in Computer Science','BACHELOR','Bachelor of Science','Comp.Sci/IT','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-data-science','American University of Sharjah','Bachelor of Science in Data Science','BACHELOR','Bachelor of Science','Comp.Sci/IT','Sharjah','Sharjah',null,null,'https://www.aus.edu/cas/department-of-mathematics-and-statistics/bachelor-of-science-in-data-science',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','aus:bsc-design-management','American University of Sharjah','Bachelor of Science in Design Management','BACHELOR','Bachelor of Science','Art and Design','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-digital-construction','American University of Sharjah','Bachelor of Science in Digital Construction Engineering and Management','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-electrical-engineering','American University of Sharjah','Bachelor of Science in Electrical Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/cen/undergraduate-degree/bachelor-of-science-in-electrical-engineering',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','aus:bsc-environmental-sciences-sustainability','American University of Sharjah','Bachelor of Science in Environmental Sciences and Sustainability','BACHELOR','Bachelor of Science','Natural/Quantitative','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-film-new-media-design','American University of Sharjah','Bachelor of Science in Film and New Media Design','BACHELOR','Bachelor of Science','Art and Design','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-graphic-design','American University of Sharjah','Bachelor of Science in Graphic Design','BACHELOR','Bachelor of Science','Art and Design','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-industrial-engineering','American University of Sharjah','Bachelor of Science in Industrial Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-intelligent-systems-mechatronics','American University of Sharjah','Bachelor of Science in Intelligent Systems and Mechatronics Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','aus:bsc-mechanical-engineering','American University of Sharjah','Bachelor of Science in Mechanical Engineering','BACHELOR','Bachelor of Science','Engineering','Sharjah','Sharjah',null,null,'https://www.aus.edu/programs/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','eau:applied-bachelor-aircraft-maintenance','Emirates Aviation University','Applied Bachelor in Aircraft Maintenance Engineering','BACHELOR','Applied Bachelor','Engineering','Dubai','Dubai',null,null,'https://www.eau.ac.ae/programmes/aircraft-maintenance-engineering-applied-bachelor/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','eau:higher-diploma-aircraft-maintenance','Emirates Aviation University','Higher Diploma in Aircraft Maintenance Engineering','HIGHER DIPLOMA','Higher Diploma','Engineering','Dubai','Dubai',null,null,'https://www.eau.ac.ae/programmes/aircraft-maintenance-engineering-applied-bachelor/','https://caa.ae/Pages/Programs/Details.aspx?GUID=8980','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','ecae:pgde-early-years-primary','Emirates College for Advanced Education','Pre-Service Early Years/Primary Postgraduate Diploma in Education','POSTGRADUATE DIPLOMA','Postgraduate Diploma','Education','Abu Dhabi','Abu Dhabi',null,null,'https://www.ecae.ac.ae/en/academics/applynow/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','ecae:pgde-secondary','Emirates College for Advanced Education','Pre-Service Secondary Postgraduate Diploma in Education','POSTGRADUATE DIPLOMA','Postgraduate Diploma','Education','Abu Dhabi','Abu Dhabi',null,null,'https://www.ecae.ac.ae/en/academics/post-graduate-programs/pre-secondary-pgd/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','fakeeh:bsc-midwifery','Fakeeh College for Medical Sciences – Dubai','Bachelor of Science in Midwifery','BACHELOR','Bachelor of Science','Health Sciences','Dubai','Dubai',null,null,'https://en.fakeeh.care/educations/fakeeh-college-for-medical-sciences',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','fakeeh:bsc-occupational-therapy','Fakeeh College for Medical Sciences – Dubai','Bachelor of Science in Occupational Therapy','BACHELOR','Bachelor of Science','Health Sciences','Dubai','Dubai',null,null,'https://en.fakeeh.care/educations/fakeeh-college-for-medical-sciences','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=8838','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','fu:ba-sociology-social-work','Fujairah University','Bachelor of Arts in Sociology and Social Work','BACHELOR','Bachelor of Arts','Social/Behavioural','Fujairah','Fujairah',null,null,'https://fu.ac.ae/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','ku:bsc-aerospace-engineering','Khalifa University','Bachelor of Science in Aerospace Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-applied-math-stats-data-science','Khalifa University','Bachelor of Science in Applied Mathematics, Statistics and Data Science','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-biomedical-engineering','Khalifa University','Bachelor of Science in Biomedical Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-cell-molecular-biology','Khalifa University','Bachelor of Science in Cell and Molecular Biology','BACHELOR','Bachelor of Science','Health Sciences','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-chemical-engineering','Khalifa University','Bachelor of Science in Chemical Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-chemistry','Khalifa University','Bachelor of Science in Chemistry','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-civil-engineering','Khalifa University','Bachelor of Science in Civil Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-computer-engineering','Khalifa University','Bachelor of Science in Computer Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/program/bsc-in-computer-engineering','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2470','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','ku:bsc-computer-science','Khalifa University','Bachelor of Science in Computer Science','BACHELOR','Bachelor of Science','Comp.Sci/IT','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2830','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','ku:bsc-earth-planetary-sciences','Khalifa University','Bachelor of Science in Earth and Planetary Sciences','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-electrical-engineering','Khalifa University','Bachelor of Science in Electrical Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-energy-engineering','Khalifa University','Bachelor of Science in Energy Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=7704','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','ku:bsc-engineering-systems-management','Khalifa University','Bachelor of Science in Engineering Systems and Management','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-mechanical-engineering','Khalifa University','Bachelor of Science in Mechanical Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-petroleum-engineering','Khalifa University','Bachelor of Science in Petroleum Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-physics','Khalifa University','Bachelor of Science in Physics','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:bsc-robotics-ai','Khalifa University','Bachelor of Science in Robotics and Artificial Intelligence','BACHELOR','Bachelor of Science','Comp.Sci/IT','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/undergraduate-programs',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','ku:meng-hse-environmental-engineering','Khalifa University','Master of Engineering in Health, Safety and Environmental Engineering','MASTER','Master of Engineering','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://www.ku.ac.ae/academics/graduate-programs','https://caa.ae/Pages/Programs/Details.aspx?GUID=2516','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','lesroches:bsc-global-hospitality-management','Abu Dhabi Hospitality Academy – Les Roches','Bachelor of Science in Global Hospitality Management','BACHELOR','Bachelor of Science','Business/Management','Abu Dhabi','Abu Dhabi',null,null,'https://lesroches.edu/programs/bachelors-degree-global-hospitality-management/','https://www.caa.ae/Pages/Programs/All.aspx','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','lesroches:msc-international-hospitality-management','Abu Dhabi Hospitality Academy – Les Roches','Master of Science in International Hospitality Management','MASTER','Master of Science','Business/Management','Abu Dhabi','Abu Dhabi',null,null,'https://lesroches.edu/campuses/abu-dhabi/','https://www.caa.ae/Pages/Programs/All.aspx','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','mbru:bsc-nursing','Mohammed Bin Rashid University of Medicine and Health Sciences','Bachelor of Science in Nursing','BACHELOR','Bachelor of Science','Health Sciences','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','mbru:graduate-entry-md-4','Mohammed Bin Rashid University of Medicine and Health Sciences','Graduate Entry Doctor of Medicine – 4 years','PROFESSIONAL','Doctor of Medicine','Health Sciences','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','mbru:md-6','Mohammed Bin Rashid University of Medicine and Health Sciences','Doctor of Medicine (MD) – 6 years','PROFESSIONAL','Doctor of Medicine','Health Sciences','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','mbru:msc-biomedical-sciences','Mohammed Bin Rashid University of Medicine and Health Sciences','Master of Science in Biomedical Sciences','MASTER','Master of Science','Health Sciences','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','mbru:msc-health-professions-education','Mohammed Bin Rashid University of Medicine and Health Sciences','Master of Science in Health Professions Education','MASTER','Master of Science','Education','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','mbru:pgdip-health-professions-education','Mohammed Bin Rashid University of Medicine and Health Sciences','Postgraduate Diploma in Health Professions Education','POSTGRADUATE DIPLOMA','Postgraduate Diploma','Education','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','mbru:phd-biomedical-sciences','Mohammed Bin Rashid University of Medicine and Health Sciences','Doctor of Philosophy in Biomedical Sciences','DOCTORATE','Doctor of Philosophy','Health Sciences','Dubai','Dubai',null,null,'https://www.mbru.ac.ae/programs/',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:ba-art-art-history','New York University Abu Dhabi','Bachelor of Arts in Art and Art History','BACHELOR','Bachelor of Arts','Art and Design','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=1344','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','nyuad:ba-business-organizations-society','New York University Abu Dhabi','Bachelor of Arts in Business, Organizations and Society','BACHELOR','Bachelor of Arts','Business/Management','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/divisions/social-science/academic-programs.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:ba-economics','New York University Abu Dhabi','Bachelor of Arts in Economics','BACHELOR','Bachelor of Arts','Business/Management','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/divisions/social-science/academic-programs.html','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=862','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','nyuad:ba-film-new-media','New York University Abu Dhabi','Bachelor of Arts in Film and New Media','BACHELOR','Bachelor of Arts','Communication/Media','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=885','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','nyuad:ba-interactive-media','New York University Abu Dhabi','Bachelor of Arts in Interactive Media','BACHELOR','Bachelor of Arts','Art and Design','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:ba-psychology','New York University Abu Dhabi','Bachelor of Arts in Psychology','BACHELOR','Bachelor of Arts','Social/Behavioural','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/divisions/science/academic-programs.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:ba-social-research-public-policy','New York University Abu Dhabi','Bachelor of Arts in Social Research and Public Policy','BACHELOR','Bachelor of Arts','Social/Behavioural','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/divisions/social-science/academic-programs.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-bioengineering','New York University Abu Dhabi','Bachelor of Science in Bioengineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-civil-urban-engineering','New York University Abu Dhabi','Bachelor of Science in Civil and Urban Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-computer-engineering','New York University Abu Dhabi','Bachelor of Science in Computer Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=978','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','nyuad:bs-computer-science','New York University Abu Dhabi','Bachelor of Science in Computer Science','BACHELOR','Bachelor of Science','Comp.Sci/IT','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-electrical-engineering','New York University Abu Dhabi','Bachelor of Science in Electrical Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-general-engineering','New York University Abu Dhabi','Bachelor of Science in General Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-mathematics','New York University Abu Dhabi','Bachelor of Science in Mathematics','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:bs-mechanical-engineering','New York University Abu Dhabi','Bachelor of Science in Mechanical Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/academics/undergraduate/majors-and-minors.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:mba','New York University Abu Dhabi','Master of Business Administration','MASTER','Master','Business/Management','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/apply.html','https://www.caa.ae/Pages/Programs/Details.aspx?GUID=6536','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','nyuad:mfa-art-media','New York University Abu Dhabi','Master of Fine Arts in Art and Media','MASTER','Master of Fine Arts','Art and Design','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/apply.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:msc-data-science-ai','New York University Abu Dhabi','Master of Science in Interdisciplinary Data Science and Artificial Intelligence','MASTER','Master of Science','Comp.Sci/IT','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/apply.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','nyuad:msc-economics','New York University Abu Dhabi','Master of Science in Economics','MASTER','Master of Science','Business/Management','Abu Dhabi','Abu Dhabi',null,null,'https://nyuad.nyu.edu/en/apply.html',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','sma:b-marine-engineering-technology','Sharjah Maritime Academy','Bachelor of Marine Engineering Technology','BACHELOR','Bachelor','Maritime','Sharjah','Khor Fakkan',null,null,'https://www.sma.ac.ae/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','sma:b-maritime-logistics-supply-chain','Sharjah Maritime Academy','Bachelor of Maritime Logistics and Supply Chain Management','BACHELOR','Bachelor','Business/Management','Sharjah','Khor Fakkan',null,null,'https://www.sma.ac.ae/undergraduate',null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','B'),
('CAA+institution','sma:b-maritime-transport','Sharjah Maritime Academy','Bachelor of Maritime Transport','BACHELOR','Bachelor','Maritime','Sharjah','Khor Fakkan',null,null,'https://www.sma.ac.ae/undergraduate','https://caa.ae/Pages/Programs/Details.aspx?GUID=6300','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','uaeu:b-accounting','United Arab Emirates University','Bachelor of Accounting','BACHELOR','Bachelor','Business/Management','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2971','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:ba-geography','United Arab Emirates University','Bachelor of Arts in Geography','BACHELOR','Bachelor of Arts','Natural/Quantitative','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2958','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:ba-mass-communication','United Arab Emirates University','Bachelor of Arts in Mass Communication','BACHELOR','Bachelor of Arts','Communication/Media','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2952','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bba-entrepreneurship','United Arab Emirates University','Bachelor of Business Administration in Entrepreneurship','BACHELOR','Bachelor','Business/Management','Abu Dhabi','Al Ain',null,null,null,null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','uaeu:bba-human-resources','United Arab Emirates University','Bachelor of Business Administration in Human Resources Management and Development','BACHELOR','Bachelor','Business/Management','Abu Dhabi','Al Ain',null,null,null,null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','uaeu:bba-marketing','United Arab Emirates University','Bachelor of Business Administration in Marketing','BACHELOR','Bachelor','Business/Management','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=6542','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bba-supply-chain-logistics','United Arab Emirates University','Bachelor of Business Administration in Supply Chain Management and Logistics','BACHELOR','Bachelor','Business/Management','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=6543','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bed-early-childhood','United Arab Emirates University','Bachelor of Education in Early Childhood','BACHELOR','Bachelor of Education','Education','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2968','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bed-special-education','United Arab Emirates University','Bachelor of Education in Special Education','BACHELOR','Bachelor of Education','Education','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2969','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bsc-aerospace-engineering','United Arab Emirates University','Bachelor of Science in Aerospace Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=4115','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bsc-data-science-ai','United Arab Emirates University','Bachelor of Science in Data Science and Artificial Intelligence','BACHELOR','Bachelor of Science','Comp.Sci/IT','Abu Dhabi','Al Ain',null,null,null,null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','uaeu:bsc-food-science','United Arab Emirates University','Bachelor of Science in Food Science','BACHELOR','Bachelor of Science','Agriculture','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2980','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bsc-geosciences','United Arab Emirates University','Bachelor of Science in Geosciences','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2967','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bsc-horticulture','United Arab Emirates University','Bachelor of Science in Horticulture','BACHELOR','Bachelor of Science','Agriculture','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2977','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:bsc-marine-fisheries-animal-science','United Arab Emirates University','Bachelor of Science in Marine Fisheries and Animal Science','BACHELOR','Bachelor of Science','Agriculture','Abu Dhabi','Al Ain',null,null,null,'https://caa.ae/Pages/Programs/Details.aspx?GUID=2978','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','occupation_gap_provider_verified_2026','A'),
('CAA+institution','uaeu:bsc-math-data-science','United Arab Emirates University','Bachelor of Science in the Mathematics of Data Science','BACHELOR','Bachelor of Science','Natural/Quantitative','Abu Dhabi','Al Ain',null,null,null,null,'https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','B'),
('CAA+institution','uaeu:bsc-petroleum-engineering','United Arab Emirates University','Bachelor of Science in Petroleum Engineering','BACHELOR','Bachelor of Science','Engineering','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=2986','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('CAA+institution','uaeu:master-education','United Arab Emirates University','Master of Education','MASTER','Master','Education','Abu Dhabi','Al Ain',null,null,null,'https://www.caa.ae/Pages/Programs/Details.aspx?GUID=3016','https://www.caa.ae/Pages/Programs/All.aspx','2026-08-09','official_current_program_verified_2026','A'),
('GCAA/EFTA','efta:integrated-atpl','Emirates Flight Training Academy','Airline Transport Pilot Licence Integrated Programme','PROFESSIONAL LICENCE','Integrated ATPL','Aviation','Dubai','Dubai',2,null,'https://www.emiratesflighttrainingacademy.com/en/course-information/',null,'https://www.emiratesflighttrainingacademy.com/en/admissions/','2026-08-09','official_current_program_verified_2026','A'),
('MOE/DCT','dct:advanced-diploma-culinary-management','Dubai College of Tourism','Advanced Diploma in Culinary Management','NQF LEVEL 5','Advanced Diploma','Culinary/Hospitality','Dubai','Dubai',2,70000,'https://dct.ac.ae/en/courses/culinary-arts/',null,'https://dct.ac.ae/en/courses/culinary-arts/','2026-08-09','official_current_program_verified_2026','A'),
('MOE/DCT','dct:certificate-culinary-operations','Dubai College of Tourism','Certificate in Culinary Operations','NQF LEVEL 3','Certificate','Culinary/Hospitality','Dubai','Dubai',1,35000,'https://dct.ac.ae/en/courses/culinary-arts/',null,'https://dct.ac.ae/en/courses/culinary-arts/','2026-08-09','official_current_program_verified_2026','A')
)
insert into public.program_catalog_ae_staging(
 source_name,source_program_key,institution_name,institution_id,title,programme_level,credential_type,education_level,field_name,emirate,city,duration_years,tuition_fee_aed,official_program_url,caa_detail_url,source_url,source_as_of,accreditation_status,collection_status,verification_tier
)
select s.source_name,s.source_program_key,s.institution_name,i.id,s.title,s.programme_level,s.credential_type,s.programme_level,s.field_name,s.emirate,s.city,s.duration_years,s.tuition_fee_aed,s.official_program_url,s.caa_detail_url,s.source_url,s.source_as_of::date,'active',s.collection_status,s.verification_tier
from seed s join catalog.institutions i on i.country_code='AE' and i.canonical_name=s.institution_name
on conflict(source_name,source_program_key) do update set
 institution_name=excluded.institution_name,institution_id=excluded.institution_id,title=excluded.title,programme_level=excluded.programme_level,credential_type=excluded.credential_type,
 education_level=excluded.education_level,field_name=excluded.field_name,emirate=excluded.emirate,city=excluded.city,duration_years=excluded.duration_years,
 tuition_fee_aed=excluded.tuition_fee_aed,official_program_url=excluded.official_program_url,caa_detail_url=excluded.caa_detail_url,source_url=excluded.source_url,
 source_as_of=excluded.source_as_of,accreditation_status='active',collection_status=excluded.collection_status,verification_tier=excluded.verification_tier,collected_at=now();

insert into public.program_international_ae_staging(program_catalog_id,source_as_of,verification_status,rule_notes)
select p.id,'2026-08-09'::date,'unverified','No programme-level international admission inference; awaiting provider evidence.'
from public.program_catalog_ae_staging p
on conflict(program_catalog_id) do nothing;
