insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:civil-engineer','NZ','civil-engineer','Civil Engineer','ANZSCO','1.3','233211','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:mechanical-engineer','NZ','mechanical-engineer','Mechanical Engineer','ANZSCO','1.3','233512','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:electrical-engineer','NZ','electrical-engineer','Electrical Engineer','ANZSCO','1.3','233311','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:manufacturing-engineer','NZ','manufacturing-engineer','Production or Plant Engineer — manufacturing engineering scope','ANZSCO','1.3','233513','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:industrial-engineer','NZ','industrial-engineer','Industrial Engineer','ANZSCO','1.3','233511','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:chemical-engineer','NZ','chemical-engineer','Chemical Engineer','ANZSCO','1.3','233111','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:environmental-engineer','NZ','environmental-engineer','Environmental Engineer','ANZSCO','1.3','233915','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:engineering-technician','NZ','engineering-technician','Building and Engineering Technicians nec — general engineering technician scope','ANZSCO','1.3','312999','NZD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
