-- Official CRICOS provider/location foundation for city-aware programme search.

insert into catalog.institution_identifiers (institution_id, identifier_system, identifier_value, source_url)
select distinct
  i.id,
  'AU_CRICOS_PROVIDER_CODE',
  c.cricos_code,
  'https://cricos.education.gov.au/institution/InstitutionSearch.aspx'
from catalog.institutions i
join catalog.institution_identifiers legacy
  on legacy.institution_id = i.id
 and legacy.identifier_system = 'AU_PROVIDER_ID'
join ingest.courses_au c
  on c.institution_id = legacy.identifier_value
where i.country_code = 'AU'
  and c.cricos_code is not null
  and btrim(c.cricos_code) <> ''
on conflict (identifier_system, identifier_value)
do update set institution_id = excluded.institution_id, source_url = excluded.source_url;

with missing_provider(canonical_name, provider_code) as (
  values
    ('Avondale University', '02731D'),
    ('TAFE NSW', '00591E'),
    ('TAFE SA', '00092B'),
    ('The University of Notre Dame Australia', '01032F'),
    ('The University of South Australia', '00121B'),
    ('The University of Sydney', '00026A'),
    ('The University of Western Australia', '00126G'),
    ('University of Divinity', '01037A'),
    ('Victoria University', '00124K'),
    ('Victoria University', '02475D')
)
insert into catalog.institution_identifiers (institution_id, identifier_system, identifier_value, source_url)
select i.id, 'AU_CRICOS_PROVIDER_CODE', m.provider_code,
       'https://cricos.education.gov.au/institution/InstitutionSearch.aspx'
from missing_provider m
join catalog.institutions i
  on i.country_code = 'AU'
 and i.canonical_name = m.canonical_name
on conflict (identifier_system, identifier_value)
do update set institution_id = excluded.institution_id, source_url = excluded.source_url;

create table if not exists ingest.cricos_locations_au (
  id bigint generated by default as identity primary key,
  source_row_id integer,
  provider_code text not null,
  institution_name text not null,
  location_name text not null,
  location_type text,
  address_line_1 text,
  address_line_2 text,
  address_line_3 text,
  address_line_4 text,
  city text,
  state text,
  postcode text,
  source_resource_id text not null,
  source_last_modified timestamptz not null,
  synced_at timestamptz not null default now()
);

create unique index if not exists cricos_locations_au_identity_uidx
  on ingest.cricos_locations_au(provider_code, location_name, coalesce(city, ''), coalesce(state, ''), coalesce(postcode, ''));
create index if not exists cricos_locations_au_provider_idx
  on ingest.cricos_locations_au(provider_code, state, city, postcode);

alter table ingest.cricos_locations_au enable row level security;
revoke all on table ingest.cricos_locations_au from anon, authenticated;
grant select, insert, update, delete on table ingest.cricos_locations_au to service_role;
grant usage, select on sequence ingest.cricos_locations_au_id_seq to service_role;

create table if not exists ingest.cricos_course_locations_au (
  id bigint generated by default as identity primary key,
  source_row_id integer,
  provider_code text not null,
  institution_name text not null,
  course_code text not null,
  location_name text not null,
  location_city text,
  location_state text,
  source_resource_id text not null,
  source_last_modified timestamptz not null,
  synced_at timestamptz not null default now()
);

create unique index if not exists cricos_course_locations_au_identity_uidx
  on ingest.cricos_course_locations_au(provider_code, course_code, location_name, coalesce(location_city, ''), coalesce(location_state, ''));
create index if not exists cricos_course_locations_au_course_idx
  on ingest.cricos_course_locations_au(provider_code, course_code);
create index if not exists cricos_course_locations_au_location_idx
  on ingest.cricos_course_locations_au(location_state, location_city, location_name);

alter table ingest.cricos_course_locations_au enable row level security;
revoke all on table ingest.cricos_course_locations_au from anon, authenticated;
grant select, insert, update, delete on table ingest.cricos_course_locations_au to service_role;
grant usage, select on sequence ingest.cricos_course_locations_au_id_seq to service_role;

alter table ingest.courses_au
  add column if not exists verified_city_ids uuid[] not null default '{}'::uuid[],
  add column if not exists verified_city_slugs text[] not null default '{}'::text[],
  add column if not exists verified_delivery_locations jsonb not null default '[]'::jsonb,
  add column if not exists location_source_resource text,
  add column if not exists location_source_last_modified timestamptz,
  add column if not exists location_verified_at timestamptz;

create index if not exists courses_au_verified_city_slugs_gin_idx
  on ingest.courses_au using gin (verified_city_slugs);

alter table catalog.programme_offerings
  add column if not exists source_system text,
  add column if not exists source_record_key text,
  add column if not exists verification_status text not null default 'unverified',
  add column if not exists source_checked_at timestamptz;

alter table catalog.programme_offerings
  drop constraint if exists programme_offerings_verification_status_check;
alter table catalog.programme_offerings
  add constraint programme_offerings_verification_status_check
  check (verification_status in ('unverified','verified','stale','rejected'));

create unique index if not exists programme_offerings_source_record_uidx
  on catalog.programme_offerings(source_system, source_record_key)
  where source_system is not null and source_record_key is not null;

update catalog.programme_offerings
set source_system = coalesce(source_system, 'legacy_backfill'),
    verification_status = case when verification_status = 'verified' then verification_status else 'unverified' end
where intake_label = 'Legacy imported offering';

create or replace view public.courses_au
with (security_invoker = true)
as
select
  id, institution_id, course_code, cricos_code, title, field_name, broad_field, narrow_field,
  aqf_level, course_type, duration_years, tuition_fee_aud, qualifax_url, cricos_url,
  employment_rate, synced_at, official_course_url, official_url_status, official_url_checked_at,
  official_url_source, cricos_status, cricos_last_seen_at, cricos_content_hash,
  verified_city_ids, verified_city_slugs, verified_delivery_locations,
  location_source_resource, location_source_last_modified, location_verified_at
from ingest.courses_au;

create or replace view api_private.au_program_catalog_v1
with (security_invoker = true)
as
select
  id, institution_id, course_code, title, field_name, broad_field, aqf_level, course_type,
  duration_years, tuition_fee_aud, employment_rate, qualifax_url, cricos_url,
  official_course_url, official_url_status, official_url_checked_at, cricos_status,
  cricos_last_seen_at, synced_at, verified_city_ids, verified_city_slugs,
  verified_delivery_locations, location_source_resource, location_source_last_modified,
  location_verified_at
from ingest.courses_au c;
