insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NL:accountant','NL','accountant','Accountants','ISCO-08','2008','2411','EUR',true,'Nederlandse Beroepsorganisatie van Accountants (NBA)','https://www.nba.nl/over-nba/lidmaatschap/accountantstitel/','profile_ready','2026-08-12',now()),
('NL:financial-analyst','NL','financial-analyst','Financial Analysts','ISCO-08','2008','2413','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:business-analyst','NL','business-analyst','Management and Organisation Analysts — business-analysis scope','ISCO-08','2008','2421','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:supply-chain-analyst','NL','supply-chain-analyst','Supply Chain Analyst — Netherlands career scope','NL career scope','2026-08-12',null,'EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:human-resources-specialist','NL','human-resources-specialist','Personnel and Careers Professionals — HR specialist scope','ISCO-08','2008','2423','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:marketing-specialist','NL','marketing-specialist','Advertising and Marketing Professionals — marketing-specialist scope','ISCO-08','2008','2431','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:auditor','NL','auditor','Accountants — external/statutory auditor scope','ISCO-08','2008','2411','EUR',true,'NBA / Autoriteit Financiële Markten (AFM)','https://www.afm.nl/nl-nl/sector/accountantsorganisaties/begrippen','profile_ready','2026-08-12',now()),
('NL:project-manager','NL','project-manager','Project Manager — cross-sector Netherlands career scope','NL career scope','2026-08-12',null,'EUR',false,null,null,'profile_ready','2026-08-12',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
