ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA taxonomy REVOKE INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES FROM service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA taxonomy REVOKE UPDATE ON SEQUENCES FROM service_role;
