-- South Korea Transport occupation cohort.
-- Classification basis: Korean Employment Classification of Occupations (KECO) 2025.
-- Logistics Coordinator is intentionally kept as a cross-mode umbrella rather than assigned one fabricated exact code.
-- Commercial freight driving, aviation maintenance/piloting and seagoing officer roles retain their statutory qualification boundaries.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('KR:truck-driver','KR','truck-driver','화물차 및 특수차 운전원','KECO','2025','6223','KRW',true,'국토교통부 / 한국교통안전공단 화물운송 종사자격','https://main.kotsa.or.kr/portal/contents.do?menuCode=01050300','profile_ready','2026-08-10',now()),
('KR:logistics-coordinator','KR','logistics-coordinator','물류 코디네이터 — cross-mode logistics umbrella','KECO','2025',null,'KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:aircraft-maintenance-technician','KR','aircraft-maintenance-technician','항공기 정비원','KECO','2025','8121','KRW',true,'국토교통부 / 한국교통안전공단 항공종사자 자격증명','https://main.kotsa.or.kr/portal/contents.do?menuCode=02010200','profile_ready','2026-08-10',now()),
('KR:commercial-pilot','KR','commercial-pilot','항공기 조종사 — commercial pilot scope','KECO','2025','6211','KRW',true,'국토교통부 / 한국교통안전공단 항공종사자 자격증명','https://main.kotsa.or.kr/portal/contents.do?menuCode=02010200','profile_ready','2026-08-10',now()),
('KR:marine-engineer','KR','marine-engineer','선박 기관사 — marine-engineer scope','KECO','2025','6212','KRW',true,'해양수산부 / 해기사 면허','https://lems.seaman.or.kr/Lems/ExamStep/selectExamStepView.do','profile_ready','2026-08-10',now()),
('KR:deck-officer','KR','deck-officer','선장 및 항해사·도선사 — deck-officer scope','KECO','2025','6212','KRW',true,'해양수산부 / 해기사 면허','https://lems.seaman.or.kr/Lems/ExamStep/selectExamStepView.do','profile_ready','2026-08-10',now()),
('KR:warehouse-manager','KR','warehouse-manager','운송 관련 관리자 — warehouse-operations scope','KECO','2025','0152','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:automotive-service-technician','KR','automotive-service-technician','자동차 정비원','KECO','2025','8124','KRW',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('KR:truck-driver','2026-08-10',0,0,0,0,13,0,0,0,2,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 6223 화물차 및 특수차 운전원 is the direct truck-driving anchor.','entry_level_basis','The role is primarily a driving-licence and occupational-qualification pathway rather than a university route.','qualification_note','Business-use freight driving requires the statutory 화물운송 종사자격 in addition to the appropriate road driving licence and fitness requirements.','market_scope','Exact recurring 6223 shortage, vacancy, salary and growth evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:logistics-coordinator','2026-08-10',0,0,0,0,13,0,0,0,5,18,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','The canonical role crosses KECO 0282, 0283, 0284 and 0289 transport/inventory clerical scopes; no fabricated exact roll-up is used.','entry_level_basis','Two reviewed industrial-engineering programmes are related study pathways and operations experience is also relevant.','market_scope','Component KECO groups are not aggregated into an exact logistics-coordinator market series.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Only entry accessibility and low universal licensing burden are credited.'),'2026-08-10'),
('KR:aircraft-maintenance-technician','2026-08-10',0,0,0,0,8,0,0,0,1,9,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 8121 항공기 정비원 is the direct maintenance occupation.','entry_level_basis','Two reviewed aerospace-engineering degrees remain related academic routes rather than maintenance-licence programmes.','qualification_note','Regulated aircraft-maintenance duties require the applicable 항공정비사 aviation-personnel qualification and any relevant limitation.','market_scope','Aerospace-sector demand is not used as exact aircraft-maintenance demand.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:commercial-pilot','2026-08-10',0,0,0,0,5,0,0,0,1,6,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','Commercial Pilot is a restricted paid-flight subset of KECO 2025 6211 항공기 조종사.','entry_level_basis','The reviewed Flight Operation degree remains a related pathway; flight training, aeronautical experience and employer selection are separate gates.','qualification_note','Commercial flying requires the applicable 사업용조종사 or higher aviation-personnel qualification plus medical and operational requirements.','market_scope','General airline or aviation-sector hiring is not converted into exact Commercial Pilot market points.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:marine-engineer','2026-08-10',0,0,0,0,7,0,0,0,1,8,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','The current KSCO-to-KECO crosswalk places seagoing ship engineers within KECO 6212; CampCareer restricts this profile to 선박 기관사 duties.','entry_level_basis','One reviewed Marine System Engineering programme is a direct study link.','qualification_note','Seagoing engineer-officer duties require the applicable 기관사 해기사 면허, examination, sea service, medical fitness and required training.','market_scope','Broad KECO 6212 data is not treated as Marine Engineer-only evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:deck-officer','2026-08-10',0,0,0,0,7,0,0,0,1,8,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','Deck Officer is a restricted navigation-officer subset of KECO 2025 6212 선장 및 항해사·도선사.','entry_level_basis','One reviewed Navigation Convergence Studies programme is a direct study link.','qualification_note','Officer duties require the applicable 항해사 해기사 면허, examination, sea service, medical fitness and required training.','market_scope','Broader captain, pilot and navigation-role data is not treated as Deck Officer-only evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:warehouse-manager','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 0152 운송 관련 관리자 includes warehouse operations management; clerical warehouse work remains separate under 0284.','entry_level_basis','One reviewed Industrial Engineering programme is related, while operational and supervisory progression is a common route.','market_scope','Broad 0152 manager observations are not treated as exact Warehouse Manager evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Experience-based entry and low universal licensing burden only.'),'2026-08-10'),
('KR:automotive-service-technician','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 8124 자동차 정비원 is the direct automotive-maintenance occupation.','entry_level_basis','Vocational automotive training and workplace progression provide accessible routes; one Future Automotive Engineering degree remains related study.','qualification_note','No single universal personal mechanic licence is applied across the whole canonical occupation; business and specialist inspection requirements are separate.','market_scope','Exact recurring 8124 shortage, vacancy, salary and growth evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('KR:truck-driver','6223','화물차 및 특수차 운전원',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:logistics-coordinator','0282','도로 및 철도운송 사무원 — logistics reference',null,null,false,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:logistics-coordinator','0283','수상 및 항공운송 사무원 — logistics reference',null,null,false,2,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:logistics-coordinator','0284','자재관리 사무원 — inventory/warehouse reference',null,null,false,3,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:logistics-coordinator','0289','기타 운송 및 무역 사무원 — logistics reference',null,null,false,4,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:aircraft-maintenance-technician','8121','항공기 정비원',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:commercial-pilot','6211','항공기 조종사 — commercial pilot scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:marine-engineer','6212','선박 기관사 — marine-engineer scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:deck-officer','6212','선장 및 항해사·도선사 — deck-officer scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:warehouse-manager','0152','운송 관련 관리자 — warehouse-operations scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:automotive-service-technician','8124','자동차 정비원',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Work24 job search','https://www.work24.go.kr/wk/a/b/1200/retriveDtlEmpSrchList.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='KR' and p.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','KECO 2025 classification','https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='KR' and p.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('KR:truck-driver','source','TS freight transport qualification','https://main.kotsa.or.kr/portal/contents.do?menuCode=01050300','government',30,'2026-08-10'),
('KR:aircraft-maintenance-technician','source','TS aviation personnel qualification','https://main.kotsa.or.kr/portal/contents.do?menuCode=02010200','government',30,'2026-08-10'),
('KR:commercial-pilot','source','TS aviation personnel qualification','https://main.kotsa.or.kr/portal/contents.do?menuCode=02010200','government',30,'2026-08-10'),
('KR:marine-engineer','source','KIMFT maritime officer examination','https://lems.seaman.or.kr/Lems/ExamStep/selectExamStepView.do','government',30,'2026-08-10'),
('KR:deck-officer','source','KIMFT maritime officer examination','https://lems.seaman.or.kr/Lems/ExamStep/selectExamStepView.do','government',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'KR:'||canonical_career_id,source_program_key,case when relation_type='direct' then 'direct' else 'related' end,coalesce(source_checked_at,'2026-08-09'::date)
from public.program_occupation_kr_v1
where canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
