ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA api_private REVOKE ALL PRIVILEGES ON TABLES FROM service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA api_private REVOKE ALL PRIVILEGES ON SEQUENCES FROM service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA api_private REVOKE EXECUTE ON FUNCTIONS FROM service_role;
