insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:registered-nurse','NZ','registered-nurse','Registered Nurses (roll-up)','ANZSCO','1.3','2544','NZD',true,'Nursing Council of New Zealand','https://www.nursingcouncil.org.nz/Public/NCNZ/nursing-section/Register_as_a_nurse.aspx','profile_ready','2026-08-10',now()),
('NZ:midwife','NZ','midwife','Midwife','ANZSCO','1.3','254111','NZD',true,'Midwifery Council of New Zealand','https://www.midwiferycouncil.health.nz/Public/Unpublished-or-Removed-content/Public/07.-I-want-to-be-a-midwife-Aotearoa--New-Zealand/3.-I-am-an-overseas-registered-midwife.aspx','profile_ready','2026-08-10',now()),
('NZ:care-worker','NZ','care-worker','Personal Care Assistant (Health Care Assistant)','ANZSCO','1.3','423313','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:physiotherapist','NZ','physiotherapist','Physiotherapist','ANZSCO','1.3','252511','NZD',true,'Physiotherapy Board of New Zealand','https://physioboard.org.nz/registering-in-aotearoa-new-zealand','profile_ready','2026-08-10',now()),
('NZ:medical-laboratory-technician','NZ','medical-laboratory-technician','Medical Laboratory Technician','ANZSCO','1.3','311213','NZD',true,'Medical Sciences Council of New Zealand','https://www.mscouncil.org.nz/pre-registration/overseas-trained-how-to-register/overseas-trained-registration-medical-laboratory-technician','profile_ready','2026-08-10',now()),
('NZ:radiographer','NZ','radiographer','Medical Imaging Technologist','ANZSCO','1.3','251211','NZD',true,'Medical Radiation Technologists Board','https://www.mrtboard.org.nz/pre-registration/overseas-trained-how-to-register','profile_ready','2026-08-10',now()),
('NZ:pharmacist','NZ','pharmacist','Pharmacists (roll-up)','ANZSCO','1.3','2515','NZD',true,'Pharmacy Council of New Zealand','https://pharmacycouncil.org.nz/pharmacy_registries/i-want-to-register-as-a-pharmacist/','profile_ready','2026-08-10',now()),
('NZ:occupational-therapist','NZ','occupational-therapist','Occupational Therapist','ANZSCO','1.3','252411','NZD',true,'Occupational Therapy Board of New Zealand','https://www.health.govt.nz/regulation-legislation/health-practitioners/responsible-authorities','profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
