-- Singapore Business occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:accountant','SG','accountant','Accountant (excluding tax accountant)','SSOC','2024','24111','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:financial-analyst','SG','financial-analyst','Financial analyst','SSOC','2024','24131','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:business-analyst','SG','business-analyst','Business consultant — business analyst scope','SSOC','2024','24212','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:supply-chain-analyst','SG','supply-chain-analyst','Supply chain analyst — consulting/logistics-analysis umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:human-resources-specialist','SG','human-resources-specialist','Human resources specialist — consultant/generalist umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:marketing-specialist','SG','marketing-specialist','Marketing specialist — research/strategy/digital umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:auditor','SG','auditor','Auditor (accounting)','SSOC','2024','24112','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:project-manager','SG','project-manager','Project manager — cross-industry umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:accountant','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the broad non-tax Accountant role directly to 24111 Accountant excluding tax accountant; Auditor 24112 and Tax accountant 24113 remain separate.','entry_level_basis','Accounting and accountancy degrees provide direct preparation; five approved Singapore accountancy programmes are retained as direct study pathways.','qualification_note','ACRA states that general accounting work does not require Public Accountant registration. Public accountancy services such as auditing and reporting on financial statements are separately reserved to registered Public Accountants.','market_scope','No exact current shortage, vacancy, salary or growth series has yet been normalised into SG v1.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:financial-analyst','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Financial analyst directly to 24131 and separates financial risk/compliance, portfolio management and financial advisory occupations.','entry_level_basis','Finance, quantitative finance, economics, accountancy and related analytical degrees provide relevant preparation; fourteen approved programmes are related study pathways.','qualification_note','There is no universal statutory occupational registration for the broad Financial Analyst role. Regulated financial-services activities and representatives can carry separate activity-specific requirements.','market_scope','Programme availability is not treated as demand evidence and all market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:business-analyst','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','For non-ICT Business Analyst, SSOC 2024 directly lists Business analyst as an example under 24212 Business consultant. ICT business analyst remains separately classified at 25112 and is excluded.','entry_level_basis','Business analytics and business-technology study provide relevant preparation; six approved programmes are related pathways rather than professional credentials.','qualification_note','There is no universal statutory occupational registration for non-ICT Business Analysts.','market_scope','The clean classification anchor does not imply an exact current labour-market series in CampCareer SG v1.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:supply-chain-analyst','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 does not provide one five-digit occupation titled Supply chain analyst. Analytical improvement work spans 24212 Business consultant, which explicitly includes Supply chain consultant, and 33461 Logistics/Production planner, which includes Logistics solutions analyst.','entry_level_basis','Supply-chain, maritime, international trading and digital supply-chain study provide relevant preparation; four approved programmes are related pathways.','qualification_note','There is no universal statutory occupational registration for Supply Chain Analysts.','market_scope','The two reference occupations are not combined into a fabricated exact salary, vacancy or shortage series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:human-resources-specialist','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The canonical HR Specialist spans SSOC 24231 Human resource consultant and 24233 Personnel/Human resource officer. 24231 explicitly includes compensation and benefits specialists and talent acquisition specialists, while 24233 covers generalist HR development and personnel work.','entry_level_basis','Human-resource management and HR consulting degrees provide direct subject preparation; two approved programmes are retained as direct study pathways.','qualification_note','There is no universal statutory occupational registration for Human Resources Specialists. Employment-law, recruitment-agency or industrial-relations activities can have separate organisational or role-specific rules.','market_scope','Multiple HR sub-scopes are preserved without manufacturing one exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:marketing-specialist','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The canonical Marketing Specialist spans SSOC 24312 Market research professional, 24313 Marketing strategy/planning professional and 24314 Digital marketing professional rather than one five-digit occupation.','entry_level_basis','Marketing, business and digital-media study provide relevant preparation; three approved programmes are related pathways.','qualification_note','There is no universal statutory occupational registration for Marketing Specialists.','market_scope','Research, strategy and digital marketing classifications are kept distinct and are not merged into an unsupported occupation-level market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:auditor','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Auditor accounting directly to 24112 and explicitly includes both External auditor and Internal auditor.','entry_level_basis','Accountancy degrees provide a common academic route; five approved programmes are related pathways because degree completion alone does not confer statutory public-audit authority.','qualification_note','ACRA requires Public Accountant registration to provide public accountancy services such as auditing and reporting on financial statements. Because SSOC 24112 also includes Internal auditor, the broad canonical Auditor role is not treated as universally requiring every worker to be a registered PA.','market_scope','Statutory audit regulation is not converted into labour-demand credit.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:project-manager','2026-08-11',0,0,0,0,8,0,0,0,5,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Singapore does not have one cross-industry five-digit SSOC occupation for generic Project Manager. 24213 Business/Financial project management professional is retained as the closest non-sector business-project reference, while construction, ICT, logistics and other sector project managers remain in their own classifications.','entry_level_basis','Project-management, business and engineering study can support entry, but dedicated project-manager roles commonly depend on prior domain and delivery experience; four approved programmes are related pathways.','qualification_note','There is no universal statutory occupational registration for cross-industry Project Managers. Sector-specific regulated responsibilities remain separate.','market_scope','The 24213 reference is not presented as an exact generic Project Manager labour-market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:accountant','24111','Accountant (excluding tax accountant)',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:financial-analyst','24131','Financial analyst',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:business-analyst','24212','Business consultant — Business analyst scope',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:supply-chain-analyst','24212','Business consultant — Supply chain consultant reference',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:supply-chain-analyst','33461','Logistics/Production planner — Logistics solutions analyst reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:human-resources-specialist','24231','Human resource consultant — specialist scope',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:human-resources-specialist','24233','Personnel/Human resource officer — generalist scope',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:marketing-specialist','24312','Market research professional',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:marketing-specialist','24313','Marketing strategy/planning professional',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:marketing-specialist','24314','Digital marketing professional',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:auditor','24112','Auditor (accounting)',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:project-manager','24213','Business/Financial project management professional — closest non-sector reference',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('accountant','financial-analyst','business-analyst','supply-chain-analyst','human-resources-specialist','marketing-specialist','auditor','project-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('accountant','financial-analyst','business-analyst','supply-chain-analyst','human-resources-specialist','marketing-specialist','auditor','project-manager')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:accountant','source','ACRA — Public Accountant requirements','https://www.acra.gov.sg/register/public-accountant/requirements-eligibility/','government',30,'2026-08-11'),
('SG:auditor','source','ACRA — Audit regulation in Singapore','https://www.acra.gov.sg/manage/public-accountant-accounting-entity/regulation-compliance/audit-regulation-singapore/','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('accountant','financial-analyst','business-analyst','supply-chain-analyst','human-resources-specialist','marketing-specialist','auditor','project-manager')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
