insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:software-developer','NZ','software-developer','Developer Programmer — Software Developer scope','ANZSCO','1.3','261312','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:data-analyst','NZ','data-analyst','Data Analyst — technology scope','NZ career scope','2026-08-10',null,'NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:data-engineer','NZ','data-engineer','Data Engineer — data-platform scope','NZ career scope','2026-08-10',null,'NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:cybersecurity-analyst','NZ','cybersecurity-analyst','ICT Security Specialist — analyst scope','ANZSCO','1.3','262112','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:network-administrator','NZ','network-administrator','Network Administrator','ANZSCO','1.3','263112','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:cloud-engineer','NZ','cloud-engineer','Cloud Engineer — cloud-infrastructure scope','NZ career scope','2026-08-10',null,'NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:database-administrator','NZ','database-administrator','Database Administrator','ANZSCO','1.3','262111','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:ict-support-technician','NZ','ict-support-technician','ICT Customer Support Officer — ICT Support Technician scope','ANZSCO','1.3','313112','NZD',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
