ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA evidence REVOKE TRUNCATE, REFERENCES, TRIGGER, MAINTAIN ON TABLES FROM service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA evidence REVOKE UPDATE ON SEQUENCES FROM service_role;
