insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:truck-driver','NZ','truck-driver','Truck Driver (General)','ANZSCO','1.3','733111','NZD',true,'NZ Transport Agency Waka Kotahi','https://www.nzta.govt.nz/driver-licences/getting-a-licence/licences-by-vehicle-type/heavy-vehicles','profile_ready','2026-08-11',now()),
('NZ:logistics-coordinator','NZ','logistics-coordinator','Logistics Specialist — coordinator scope','NZ career scope','2026-08-11',null,'NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:aircraft-maintenance-technician','NZ','aircraft-maintenance-technician','Aircraft Maintenance Engineer — avionics/mechanical/structures roll-up','ANZSCO','1.3','3231','NZD',true,'Civil Aviation Authority of New Zealand','https://www.aviation.govt.nz/licensing-and-certification/engineering/maintenance-engineer-licensing/','profile_ready','2026-08-11',now()),
('NZ:commercial-pilot','NZ','commercial-pilot','Aeroplane Pilot — commercial pilot scope','ANZSCO','1.3','231111','NZD',true,'Civil Aviation Authority of New Zealand','https://www.aviation.govt.nz/rules/rule-part/part-61/subpart-e/','profile_ready','2026-08-11',now()),
('NZ:marine-engineer','NZ','marine-engineer','Ship''s Engineer (Marine Engineer)','ANZSCO','1.3','231212','NZD',true,'Maritime New Zealand','https://www.maritimenz.govt.nz/seafarers/getting-certified/','profile_ready','2026-08-11',now()),
('NZ:deck-officer','NZ','deck-officer','Ship''s Officer (Deck Officer)','ANZSCO','1.3','231214','NZD',true,'Maritime New Zealand','https://www.maritimenz.govt.nz/seafarers/getting-certified/','profile_ready','2026-08-11',now()),
('NZ:warehouse-manager','NZ','warehouse-manager','Supply and Distribution Manager — warehouse/distribution scope','ANZSCO','1.3','133611','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:automotive-service-technician','NZ','automotive-service-technician','Motor Mechanic (General) — automotive light technician scope','ANZSCO','1.3','321211','NZD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
