-- Singapore Design / Creative occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:graphic-designer','SG','graphic-designer','Graphic designer','SSOC','2024','21661','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:ux-designer','SG','ux-designer','Interaction designer — UX/UI scope','SSOC','2024','25124','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:multimedia-designer','SG','multimedia-designer','Multimedia designer/artist/animator','SSOC','2024','21662','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:animator','SG','animator','Animator — under Multimedia designer/artist/animator','SSOC','2024','21662','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:interior-designer','SG','interior-designer','Interior designer','SSOC','2024','34321','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:film-editor','SG','film-editor','Film/Video editor — creative post-production reference scope','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:architect','SG','architect','Building architect','SSOC','2024','21610','SGD',true,'Board of Architects Singapore (BOA)','https://www.boa.gov.sg/register/requirements/','profile_ready','2026-08-11',now()),
('SG:web-designer','SG','web-designer','Web designer — internet graphic/interaction design umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:graphic-designer','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21661 Graphic designer is a direct match and explicitly includes Internet graphic designer.','entry_level_basis','Portfolio-led design study and applied visual communication pathways support entry; three approved programmes are related rather than occupational certification.','qualification_note','No universal statutory occupational registration is identified for Graphic Designers.','market_scope','No shortage, vacancy, salary or growth series is scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:ux-designer','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 25124 Interaction designer directly lists User experience designer and User interface designer.','entry_level_basis','UX entry commonly combines interaction/product design, research and portfolio evidence; five approved programmes are related pathways.','qualification_note','No universal statutory occupational registration is identified for UX Designers.','market_scope','No labour-market component is inferred from the ICT classification.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:multimedia-designer','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21662 Multimedia designer/artist/animator directly covers graphics, 2D/3D animation, special effects and video editing.','entry_level_basis','Multimedia entry commonly requires a portfolio plus design/media skills; three approved programmes are related pathways.','qualification_note','No universal statutory occupational registration is identified.','market_scope','The shared 21662 code is not converted into exact multimedia-only market statistics.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:animator','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21662 explicitly lists Animator within Multimedia designer/artist/animator.','entry_level_basis','Animation is portfolio-led and can be entered through art, design, media and interactive-content pathways; two approved programmes are related.','qualification_note','No universal statutory occupational registration is identified for Animators.','market_scope','No animator-specific market series is fabricated from the wider 21662 scope.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:interior-designer','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 34321 Interior designer directly covers interior space planning, design, specifications and supervision of decorating work.','entry_level_basis','Interior and spatial design study plus portfolio/project experience provide common entry routes; two approved programmes are related.','qualification_note','The broad Interior Designer occupation is not treated as requiring BOA architect registration; reserved architectural practice remains separate.','market_scope','No exact market series is scored in SG v1 foundation.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:film-editor','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 has no exact five-digit Film Editor occupation. 21662 is retained as a non-rollup creative post-production reference because its definition explicitly includes editing videos; 26544 is not used because it describes editorial/script coordination rather than picture editing.','entry_level_basis','Film/video editing is portfolio and production-workflow driven; two approved programmes are related pathways.','qualification_note','No universal statutory occupational registration is identified for Film Editors.','market_scope','No proxy code is treated as exact film-editor demand, salary or vacancy evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:architect','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21610 Building architect is the direct occupational match; architectural engineer, landscape architect and interior designer remain separate classifications.','entry_level_basis','BOA registration requires an approved architecture qualification, prescribed practical experience and the relevant professional examination or interview route. Three approved architecture/landscape/design programmes remain related study links because programme completion alone does not confer registration.','qualification_note','The Architects Act requires BOA registration to practise architecture and restricts use of the architect title; a practising certificate is required for practice.','market_scope','Legal registration evidence is not converted into labour-demand points.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:web-designer','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Singapore has no standalone five-digit Web Designer occupation. The visual/interface scope is represented by 21661 Internet graphic designer and 25124 Interaction designer. 25122 Web/Mobile applications developer is intentionally excluded because it is a software-development occupation.','entry_level_basis','Web design entry is portfolio-led and can combine graphic, interaction and digital-media skills; three approved programmes are related pathways.','qualification_note','No universal statutory occupational registration is identified for Web Designers.','market_scope','Reference codes are not aggregated into a fabricated exact web-designer market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:graphic-designer','21661','Graphic designer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:ux-designer','25124','Interaction designer — includes User experience/User interface designer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:multimedia-designer','21662','Multimedia designer/artist/animator',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:animator','21662','Multimedia designer/artist/animator — Animator scope',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:interior-designer','34321','Interior designer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:film-editor','21662','Multimedia designer/artist/animator — creative video-editing reference',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:architect','21610','Building architect',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:web-designer','21661','Graphic designer — includes Internet graphic designer',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:web-designer','25124','Interaction designer — UX/UI interface-design reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:architect','source','Board of Architects — Registration requirements','https://www.boa.gov.sg/register/requirements/','government',30,'2026-08-11'),
('SG:architect','source','Board of Architects — Architect registration FAQ','https://www.boa.gov.sg/faq/','government',31,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
