insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('UK:chef','UK','chef','Chefs','SOC','SOC 2020','5434','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:cook','UK','cook','Cooks','SOC','SOC 2020','5435','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:hotel-manager','UK','hotel-manager','Hotel and accommodation managers and proprietors','SOC','SOC 2020','1221','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:restaurant-manager','UK','restaurant-manager','Restaurant and catering establishment managers and proprietors','SOC','SOC 2020','1222','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:baker','UK','baker','Bakers and flour confectioners — baker scope','SOC','SOC 2020','5432','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:tourism-manager','UK','tourism-manager','Travel agency managers and proprietors — tourism/travel management scope','SOC','SOC 2020','1225','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:event-planner','UK','event-planner','Events managers and organisers — event planner scope','SOC','SOC 2020','3557','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:hospitality-supervisor','UK','hospitality-supervisor','Bar and catering supervisors — hospitality supervisor scope','SOC','SOC 2020','9261','GBP',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
