insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:carpenter','NZ','carpenter','Carpenter','ANZSCO','1.3','331212','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:electrician','NZ','electrician','Electrician (General)','ANZSCO','1.3','341111','NZD',true,'Electrical Workers Registration Board','https://www.ewrb.govt.nz/registration/registration-overseas-trained-pathway/electrician/','profile_ready','2026-08-10',now()),
('NZ:plumber','NZ','plumber','Plumber (General)','ANZSCO','1.3','334111','NZD',true,'Plumbers, Gasfitters and Drainlayers Board','https://www.pgdb.co.nz/apply_for_registration/register_with_overseas_qualifications','profile_ready','2026-08-10',now()),
('NZ:wall-floor-tiler','NZ','wall-floor-tiler','Wall and Floor Tiler','ANZSCO','1.3','333411','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:welder','NZ','welder','Welder','ANZSCO','1.3','322313','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:bricklayer','NZ','bricklayer','Bricklayer','ANZSCO','1.3','331111','NZD',false,null,null,'profile_ready','2026-08-10',now()),
('NZ:hvac-technician','NZ','hvac-technician','Airconditioning and Refrigeration Mechanic','ANZSCO','1.3','342111','NZD',true,'Electrical Workers Registration Board','https://www.ewrb.govt.nz/registration/registration-overseas-trained-pathway/electrical-service-technician/','profile_ready','2026-08-10',now()),
('NZ:construction-manager','NZ','construction-manager','Construction Project Manager','ANZSCO','1.3','133111','NZD',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
