-- South Korea Design occupation cohort.
-- Classification basis: Korean Employment Classification of Occupations (KECO) 2025.
-- UX Designer and Web Designer use restricted subsets of broader visual/media design groups.
-- Architect represents the regulated Korean 건축사 professional scope.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('KR:graphic-designer','KR','graphic-designer','시각 디자이너','KECO','2025','4154','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:ux-designer','KR','ux-designer','시각 디자이너 — UX/UI scope','KECO','2025','4154','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:multimedia-designer','KR','multimedia-designer','미디어 콘텐츠 디자이너','KECO','2025','4155','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:animator','KR','animator','만화가 및 만화영화 작가 — animator scope','KECO','2025','4143','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:interior-designer','KR','interior-designer','실내장식 디자이너','KECO','2025','4153','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:film-editor','KR','film-editor','영상·녹화 및 편집 기사','KECO','2025','4166','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:architect','KR','architect','건축가 — licensed architect scope','KECO','2025','1401','KRW',true,'국토교통부 / 대한건축사협회 건축사등록원','https://kirakarb.kira.or.kr/arcts/rgacPage.do','profile_ready','2026-08-10',now()),
('KR:web-designer','KR','web-designer','미디어 콘텐츠 디자이너 — web designer scope','KECO','2025','4155','KRW',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('KR:graphic-designer','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 4154 시각 디자이너 is the direct graphic-design anchor.','entry_level_basis','Reviewed visual-design programmes and portfolio-based entry support accessible graduate entry.','market_scope','Exact recurring 4154 vacancy, salary, shortage and growth series are not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Only entry accessibility and low universal licensing burden are credited.'),'2026-08-10'),
('KR:ux-designer','2026-08-10',0,0,0,0,13,0,0,0,5,18,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','UX/UI design is kept as a restricted subset of broader KECO 4154 시각 디자이너.','entry_level_basis','Six reviewed design programmes provide related study pathways; portfolio and UX practice remain central.','market_scope','Broad 4154 observations are not treated as UX-only evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Only entry accessibility and low licensing burden are credited.'),'2026-08-10'),
('KR:multimedia-designer','2026-08-10',0,0,0,0,13,0,0,0,5,18,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 4155 미디어 콘텐츠 디자이너 is the direct media-content design family.','entry_level_basis','Two direct digital-content/visual-media programmes plus related media programmes support entry.','market_scope','Adjacent broadcasting and software signals are not substituted for exact 4155 evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Only entry accessibility and low licensing burden are credited.'),'2026-08-10'),
('KR:animator','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 4143 만화가 및 만화영화 작가 includes animator work and is restricted here to animation.','entry_level_basis','The reviewed Digital Content programme is related rather than direct; reel and portfolio quality remain decisive.','market_scope','Broader content-industry demand is not converted into animator-only market points.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Conservative entry credit plus low licensing burden only.'),'2026-08-10'),
('KR:interior-designer','2026-08-10',0,0,0,0,13,0,0,0,5,18,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 4153 실내장식 디자이너 is a direct mapping.','entry_level_basis','One reviewed Interior Architecture Design programme is a direct study pathway.','qualification_note','Architect and construction execution duties remain separate and can carry other legal requirements.','market_scope','Exact recurring 4153 market evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:film-editor','2026-08-10',0,0,0,0,13,0,0,0,5,18,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 4166 영상·녹화 및 편집 기사 directly covers film/video editing.','entry_level_basis','Four reviewed media/visual-media programmes remain related study pathways.','market_scope','Broadcasting-sector observations are not substituted for exact 4166 evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry accessibility and low licensing burden only.'),'2026-08-10'),
('KR:architect','2026-08-10',0,0,0,0,8,0,0,0,1,9,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 1401 건축가 is restricted to the CampCareer canonical 건축사 professional scope.','entry_level_basis','Seven reviewed architecture programmes are direct study links, subject to accreditation and professional eligibility.','qualification_note','Architect services require qualification examination and registration; education alone is not sufficient.','market_scope','Broader construction or architecture-sector demand is not used as exact architect market evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Long regulated entry route keeps both entry and burden credit conservative.'),'2026-08-10'),
('KR:web-designer','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','Web Designer is an explicit subset of KECO 2025 4155 미디어 콘텐츠 디자이너.','entry_level_basis','Three reviewed visual/design programmes are related pathways and portfolio-based entry is relatively accessible.','market_scope','Broad 4155 data is not presented as web-designer-only evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Only entry accessibility and low licensing burden are credited.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('KR:graphic-designer','4154','시각 디자이너',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:ux-designer','4154','시각 디자이너 — UX/UI scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:multimedia-designer','4155','미디어 콘텐츠 디자이너',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:animator','4143','만화가 및 만화영화 작가 — animator scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:interior-designer','4153','실내장식 디자이너',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:film-editor','4166','영상·녹화 및 편집 기사',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:architect','1401','건축가 — licensed architect scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:web-designer','4155','미디어 콘텐츠 디자이너 — web designer scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Work24 job search','https://www.work24.go.kr/wk/a/b/1200/retriveDtlEmpSrchList.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='KR' and p.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','KECO 2025 classification','https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='KR' and p.canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('KR:architect','source','Architect qualification registration','https://kirakarb.kira.or.kr/arcts/rgacPage.do','professional_body',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'KR:'||canonical_career_id,source_program_key,case when relation_type='direct' then 'direct' else 'related' end,coalesce(source_checked_at,'2026-08-09'::date)
from public.program_occupation_kr_v1
where canonical_career_id in ('graphic-designer','ux-designer','multimedia-designer','animator','interior-designer','film-editor','architect','web-designer')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
