insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:early-childhood-teacher','IE','early-childhood-teacher','Primary and nursery education teaching professionals — nursery / early-childhood teacher scope','SOC','SOC 2010','2315','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:primary-school-teacher','IE','primary-school-teacher','Primary and nursery education teaching professionals — primary-school teacher scope','SOC','SOC 2010','2315','EUR',true,'The Teaching Council','https://www.teachingcouncil.ie/i-am-applying-to-register/qualified-in-ireland/register-as-a-primary-teacher/','profile_ready','2026-08-11',now()),
  ('IE:secondary-school-teacher','IE','secondary-school-teacher','Secondary education teaching professionals','SOC','SOC 2010','2314','EUR',true,'The Teaching Council','https://www.teachingcouncil.ie/i-am-applying-to-register/qualified-in-ireland/register-as-a-post-primary-teacher/','profile_ready','2026-08-11',now()),
  ('IE:special-education-teacher','IE','special-education-teacher','Special needs education teaching professionals','SOC','SOC 2010','2316','EUR',true,'The Teaching Council','https://www.teachingcouncil.ie/registration/','profile_ready','2026-08-11',now()),
  ('IE:social-worker','IE','social-worker','Social workers','SOC','SOC 2010','2442','EUR',true,'CORU — Social Workers Registration Board','https://www.coru.ie/about-us/registration-boards/social-workers-registration-board/','profile_ready','2026-08-11',now()),
  ('IE:youth-worker','IE','youth-worker','Youth and community workers — youth-work scope','SOC','SOC 2010','3231','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:community-worker','IE','community-worker','Youth and community workers — community-work scope','SOC','SOC 2010','3231','EUR',false,null,null,'profile_ready','2026-08-11',now()),
  ('IE:counsellor','IE','counsellor','Counsellors','SOC','SOC 2010','3235','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:early-childhood-teacher','2026-08-11',null,null,null,0,0,0,0,10,0,0,5,3,18,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2315 Primary and nursery education teaching professionals, constrained to nursery / early-childhood teacher-level work.','shortage_note','SOLAS 2025 Education identifies subject-specific secondary teachers as the shortage; no occupation-wide Early Childhood Teacher shortage is inferred; 0/20.','visa_basis','SOC 2315 is not explicitly on the current CSEP or Ineligible lists, so a genuine teaching-professional role may use ordinary GEP access subject to DETE classification and permit conditions; cautious 5/10 because early-years duties can instead fall under permit-ineligible SOC 3233 or 6121.','scope_boundary','Child and early years officers (3233), nursery nurses/assistants (6121) and childminders are not included in this professional teacher profile.','entry_basis','Early Learning and Care staff working directly with children must hold at least an NFQ Level 5 major award or a qualification recognised as equivalent; 10/15.','entry_burden_basis','Mandatory recognised qualification applies, but there is no Teaching Council registration requirement for generic Early Learning and Care practitioner work; 3/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:primary-school-teacher','2026-08-11',null,null,null,0,0,0,0,8,0,0,6,1,15,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2315 Primary and nursery education teaching professionals, constrained to primary-school teachers.','shortage_note','SOLAS 2025 notes difficulties filling some primary posts, including special-school and regional issues, but its explicit Education shortage is subject-specific secondary teachers; broad Primary shortage remains 0/20.','visa_basis','SOC 2315 is not explicitly on the current CSEP or Ineligible lists; ordinary GEP access may apply subject to employer, remuneration and Labour Market Needs Test conditions; 6/10.','registration_basis','Teaching Council registration is required for teachers in state-recognised primary schools to receive State-paid teacher salary.','entry_basis','Teaching Council registration requires an approved undergraduate primary ITE qualification or a Level 8 degree plus approved postgraduate primary teacher education; 8/15.','entry_burden_basis','Statutory professional registration and prescribed teacher-education requirements create high entry burden; 1/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:secondary-school-teacher','2026-08-11',null,null,null,12,0,0,0,8,0,0,6,1,27,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2314 Secondary education teaching professionals.','shortage_note','SOLAS 2025 explicitly identifies subject-specific secondary teachers as a shortage. The broad canonical occupation receives partial 12/20 rather than universal maximum shortage credit because the finding is subject-specific.','visa_basis','SOC 2314 is not explicitly on the current CSEP or Ineligible lists; ordinary GEP access may apply subject to current conditions; 6/10.','registration_basis','Teaching Council registration is required for recognised post-primary teaching.','entry_basis','Post-primary registration normally requires an appropriate Level 8 subject degree plus approved PME, or an approved concurrent post-primary ITE degree; 8/15.','entry_burden_basis','Statutory registration and curricular-subject qualification requirements create high entry burden; 1/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:special-education-teacher','2026-08-11',null,null,null,5,0,0,0,8,0,0,6,1,20,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2316 Special needs education teaching professionals.','shortage_note','SOLAS 2025 reports greater special-education demand and vacancy issues in special schools, but does not list the broad occupation as a direct shortage; limited demand credit 5/20.','visa_basis','SOC 2316 is not explicitly on the current CSEP or Ineligible lists; ordinary GEP access may apply subject to current conditions; 6/10.','registration_basis','Teaching Council registration applies to teachers working in recognised school settings; there is no separate statutory Special Education Teacher licence layered on top of teacher registration.','entry_basis','Primary or post-primary initial teacher education and Teaching Council registration are the core professional route, with special-education expertise layered by setting and role; 8/15.','entry_burden_basis','Teacher registration and ITE requirements create high entry burden; 1/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:social-worker','2026-08-11',null,null,null,0,0,0,0,8,0,0,10,1,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2442 Social workers.','shortage_note','No separate SOLAS occupation-specific shortage component is imported here; CSEP eligibility is kept in the visa component rather than double-counted as shortage; 0/20.','visa_basis','Social Worker SOC 2442 is explicitly on the current Critical Skills Occupations List; 10/10.','registration_basis','Social worker is a legally protected title in Ireland and CORU Social Workers Registration Board registration is required to use the title.','entry_basis','Approved professional social-work qualification or recognised international qualification is required for CORU registration; 8/15.','entry_burden_basis','Protected title and statutory CORU registration create high entry burden; 1/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:youth-worker','2026-08-11',null,null,null,0,0,0,0,12,0,0,0,5,17,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3231 Youth and community workers, constrained to youth-work scope.','shortage_note','No recurring occupation-specific Irish shortage evidence is used; 0/20.','visa_basis','SOC 3231 Youth and community workers is on the current Ineligible List for employment permits, except the separately named Family Support Worker disability-services exception; canonical Youth Worker receives 0/10.','scope_boundary','The disability-services Family Support Worker exception is not borrowed for generic Youth Worker roles.','entry_basis','SOLAS lists a Youth Work traineeship with substantial on-the-job learning and a Level 6 Community Development outcome, supporting an accessible structured route; 12/15.','entry_burden_basis','No universal statutory professional registration applies to generic youth work; 5/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:community-worker','2026-08-11',null,null,null,0,0,0,0,12,0,0,0,5,17,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3231 Youth and community workers, constrained to community-work scope.','shortage_note','No recurring occupation-specific Irish shortage evidence is used; 0/20.','visa_basis','SOC 3231 Youth and community workers is on the current Ineligible List for employment permits, except the separately named Family Support Worker disability-services exception; canonical Community Worker receives 0/10.','scope_boundary','Family Support Worker disability-services exceptions and separately regulated Social Worker/Social Care Worker titles are not rolled into generic Community Worker.','entry_basis','SOLAS Social and Community Care and Youth Work traineeship pathways provide related structured work-based entry into community-facing support roles; 12/15.','entry_burden_basis','No universal statutory registration applies to generic Community Worker; 5/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11'),
  ('IE:counsellor','2026-08-11',null,null,null,0,0,0,0,8,0,0,0,5,13,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3235 Counsellors.','shortage_note','No recurring occupation-specific Irish shortage evidence is used; 0/20.','visa_basis','SOC 3235 Counsellors is on the current Ineligible List for employment permits; 0/10.','regulation_boundary','CORU has established a Counsellors and Psychotherapists Registration Board and published future standards, but the counsellor and psychotherapist registers are not yet open; current profile remains registration_required=false.','entry_basis','Formal counselling education and supervised practice are common, but no current CORU-approved qualification pathway can be asserted before the statutory register and programme-approval process opens; conservative 8/15.','entry_burden_basis','No current statutory counsellor register is open, so current legal registration burden is not scored; 5/5.','salary_method','No exact comparable current Irish occupation-level salary series normalised; 0.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (
  profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at
) values
  ('IE:early-childhood-teacher','2315','Primary and nursery education teaching professionals — nursery / early-childhood teacher scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:primary-school-teacher','2315','Primary and nursery education teaching professionals — primary-school teacher scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-11'),
  ('IE:secondary-school-teacher','2314','Secondary education teaching professionals — subject-specific shortage scope',12,true,true,1,'https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/education/','2026-08-11'),
  ('IE:special-education-teacher','2316','Special needs education teaching professionals',5,true,true,1,'https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/education/','2026-08-11'),
  ('IE:social-worker','2442','Social workers — Critical Skills employment',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-11'),
  ('IE:youth-worker','3231','Youth and community workers — youth-work scope',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:community-worker','3231','Youth and community workers — community-work scope',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11'),
  ('IE:counsellor','3235','Counsellors',null,false,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (
  profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at
) values
  ('IE:early-childhood-teacher','source','SOLAS — Education labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/education/','government',null,1,'2026-08-11'),
  ('IE:early-childhood-teacher','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:early-childhood-teacher','entry_program','DCDE — recognition of an Early Years qualification','https://www.gov.ie/en/department-of-children-disability-and-equality/services/recognition-of-an-early-years-qualification/','government',null,3,'2026-08-11'),
  ('IE:primary-school-teacher','source','SOLAS — Education labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/education/','government',null,1,'2026-08-11'),
  ('IE:primary-school-teacher','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:primary-school-teacher','entry_program','Teaching Council — Primary teacher registration route','https://www.teachingcouncil.ie/i-am-applying-to-register/qualified-in-ireland/register-as-a-primary-teacher/','regulator',null,3,'2026-08-11'),
  ('IE:secondary-school-teacher','source','SOLAS — Education shortage evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/education/','government',null,1,'2026-08-11'),
  ('IE:secondary-school-teacher','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:secondary-school-teacher','entry_program','Teaching Council — Post-primary teacher registration route','https://www.teachingcouncil.ie/i-am-applying-to-register/qualified-in-ireland/register-as-a-post-primary-teacher/','regulator',null,3,'2026-08-11'),
  ('IE:special-education-teacher','source','SOLAS — Education demand / special-school vacancy evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/education/','government',null,1,'2026-08-11'),
  ('IE:special-education-teacher','source','DETE — employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-11'),
  ('IE:special-education-teacher','entry_program','Teaching Council — teacher registration framework','https://www.teachingcouncil.ie/registration/','regulator',null,3,'2026-08-11'),
  ('IE:social-worker','source','DETE — Critical Skills Occupations List, Social Worker SOC 2442','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,1,'2026-08-11'),
  ('IE:social-worker','source','CORU — Social Workers Registration Board','https://www.coru.ie/about-us/registration-boards/social-workers-registration-board/','regulator',null,2,'2026-08-11'),
  ('IE:social-worker','entry_program','CORU — Social Workers Registration Board approved qualification framework','https://coru.ie/about-us/legislation/registration-board-bye-laws/social-workers-registration-board-bye-laws/','regulator',null,3,'2026-08-11'),
  ('IE:youth-worker','source','DETE — Ineligible List, Youth and community workers SOC 3231','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,1,'2026-08-11'),
  ('IE:youth-worker','entry_program','SOLAS — Youth Work traineeship','https://www.solas.ie/programmes/traineeship/','government',null,2,'2026-08-11'),
  ('IE:community-worker','source','DETE — Ineligible List, Youth and community workers SOC 3231','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,1,'2026-08-11'),
  ('IE:community-worker','entry_program','SOLAS — Social and Community Care / Youth Work traineeship routes','https://www.solas.ie/programmes/traineeship/','government',null,2,'2026-08-11'),
  ('IE:counsellor','source','DETE — Ineligible List, Counsellors SOC 3235','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/ineligible-categories-of-employment/','government',null,1,'2026-08-11'),
  ('IE:counsellor','source','CORU — counsellor registration implementation status','https://www.coru.ie/about-us/registration-boards/counsellors-and-psychotherapists-registration-board/faqs/faq-b-opening-of-the-registers/','regulator',null,2,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
