insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NL:software-developer','NL','software-developer','Software Developers','ISCO-08','2008','2512','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:data-analyst','NL','data-analyst','Data Analyst / BI Analyst — Netherlands career scope','NL career scope','2026-08-12',null,'EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:data-engineer','NL','data-engineer','Data Engineer — database/software engineering scope','NL career scope','2026-08-12',null,'EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:cybersecurity-analyst','NL','cybersecurity-analyst','Database and Network Professionals n.e.c. — cybersecurity analysis scope','ISCO-08','2008','2529','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:network-administrator','NL','network-administrator','Computer Network Professionals — network administration scope','ISCO-08','2008','2523','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:cloud-engineer','NL','cloud-engineer','Cloud Engineer / DevOps infrastructure — Netherlands career scope','NL career scope','2026-08-12',null,'EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:database-administrator','NL','database-administrator','Database Designers and Administrators','ISCO-08','2008','2521','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:ict-support-technician','NL','ict-support-technician','ICT User Support Technicians','ISCO-08','2008','3512','EUR',false,null,null,'profile_ready','2026-08-12',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
