insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('UK:graphic-designer','UK','graphic-designer','Graphic and multimedia designers — graphic designer scope','SOC','SOC 2020','2142','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:ux-designer','UK','ux-designer','Web design professionals — UI and UX designer/researcher scope','SOC','SOC 2020','2141','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:multimedia-designer','UK','multimedia-designer','Graphic and multimedia designers — multimedia designer scope','SOC','SOC 2020','2142','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:animator','UK','animator','Graphic and multimedia designers — multimedia animator scope','SOC','SOC 2020','2142','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:interior-designer','UK','interior-designer','Interior designers','SOC','SOC 2020','3421','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:film-editor','UK','film-editor','Arts officers, producers and directors — broadcasting and entertainment editor scope','SOC','SOC 2020','3416','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:architect','UK','architect','Architects — architect excluding landscape scope','SOC','SOC 2020','2451','GBP',true,'Architects Registration Board','https://arb.org.uk/architect-information/applying-for-registration-for-the-first-time/registration-the-facts/','profile_ready','2026-08-10',now()),
('UK:web-designer','UK','web-designer','Web design professionals — web designer scope','SOC','SOC 2020','2141','GBP',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
