-- South Korea Hospitality occupation cohort.
-- Classification basis: Korean Employment Classification of Occupations (KECO) 2025.
-- Cook and Hospitality Supervisor are umbrellas without a single exact KECO unit group.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('KR:chef','KR','chef','주방장 및 요리 연구가 — chef scope','KECO','2025','5311','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:cook','KR','cook','조리사 — cook umbrella','KECO','2025',null,'KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:hotel-manager','KR','hotel-manager','숙박·여행·오락 및 스포츠 관련 관리자 — hotel-management scope','KECO','2025','0141','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:restaurant-manager','KR','restaurant-manager','음식 서비스 관련 관리자','KECO','2025','0142','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:baker','KR','baker','제과원 및 제빵사','KECO','2025','8711','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:tourism-manager','KR','tourism-manager','숙박·여행·오락 및 스포츠 관련 관리자 — tourism-management scope','KECO','2025','0141','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:event-planner','KR','event-planner','행사·전시 및 회의 기획자','KECO','2025','0244','KRW',false,null,null,'profile_ready','2026-08-10',now()),
('KR:hospitality-supervisor','KR','hospitality-supervisor','호스피탈리티 현장 감독 — umbrella','KECO','2025',null,'KRW',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('KR:chef','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 5311 주방장 및 요리 연구가 is restricted here to chef/kitchen-leadership work.','entry_level_basis','Chef roles normally require progression from practical kitchen work; the reviewed degree is related rather than an appointment guarantee.','qualification_note','No universal chef licence is assigned, while specified food-service settings can require a licensed 조리사 under the Food Sanitation Act.','market_scope','Exact recurring chef vacancy, salary, shortage and growth evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:cook','2026-08-10',0,0,0,0,15,0,0,0,4,19,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','Cook spans KECO 5312, 5313, 5314, 5315, 5318 and 5319; no fabricated generic code is used.','entry_level_basis','Practical and vocational entry is relatively accessible.','qualification_note','The broad occupation is not universally licensed, but specified institutional food-service settings can require a licensed 조리사.','market_scope','Multiple cooking codes are not aggregated into a synthetic exact market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-10'),
('KR:hotel-manager','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','Hotel management is a restricted subset of broader KECO 0141.','entry_level_basis','A reviewed Hospitality Management degree is direct study evidence, but operational experience is normally required for management appointment.','market_scope','Broad 0141 observations are not treated as hotel-manager-only evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry structure and low universal licensing burden only.'),'2026-08-10'),
('KR:restaurant-manager','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 0142 음식 서비스 관련 관리자 is the direct management family.','entry_level_basis','Hospitality study is related and management progression usually requires operational experience.','market_scope','Exact recurring 0142 vacancy, salary, shortage and growth evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry and burden only.'),'2026-08-10'),
('KR:baker','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 8711 제과원 및 제빵사 is a direct mapping.','entry_level_basis','Vocational qualification, workplace training and related culinary study support accessible entry.','market_scope','Exact recurring 8711 vacancy, salary, shortage and growth evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry accessibility and low universal licensing burden only.'),'2026-08-10'),
('KR:tourism-manager','2026-08-10',0,0,0,0,10,0,0,0,5,15,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','Tourism management is a restricted subset of broader KECO 0141; frontline travel service code 5211 is not substituted for management.','entry_level_basis','One direct Tourism & Convention programme and two related hospitality/tourism programmes are retained.','market_scope','Broad 0141 demand is not presented as tourism-manager-only evidence.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry and burden only.'),'2026-08-10'),
('KR:event-planner','2026-08-10',0,0,0,0,15,0,0,0,5,20,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','KECO 2025 0244 행사·전시 및 회의 기획자 is a direct mapping.','entry_level_basis','One direct Tourism & Convention programme plus related hospitality, culture and tourism study support project-based entry.','market_scope','Exact recurring 0244 market evidence is not yet normalised.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Entry accessibility and low licensing burden only.'),'2026-08-10'),
('KR:hospitality-supervisor','2026-08-10',0,0,0,0,13,0,0,0,5,18,'career-opportunity-kr-v1','provisional',jsonb_build_object('classification_scope','No single KECO unit group covers cross-venue hospitality supervisors; 0141, 0142, 5230 and 5322 are kept only as reference specialisations.','entry_level_basis','A reviewed Hospitality Management programme is direct study evidence and frontline experience supports progression.','market_scope','Hotel, restaurant and frontline service series are not combined into a synthetic supervisor market figure.','visa_scope','No occupation-specific visa credit is assigned.','score_scope','Moderate entry credit and low universal licensing burden only.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('KR:chef','5311','주방장 및 요리 연구가 — chef scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:cook','5312','한식 조리사',null,null,false,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:cook','5313','중식 조리사',null,null,false,2,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:cook','5314','양식 조리사',null,null,false,3,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:cook','5315','일식 조리사',null,null,false,4,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:cook','5318','단체급식 조리사',null,null,false,5,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:cook','5319','기타 조리사',null,null,false,6,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:hotel-manager','0141','숙박·여행·오락 및 스포츠 관련 관리자 — hotel-management scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:restaurant-manager','0142','음식 서비스 관련 관리자',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:baker','8711','제과원 및 제빵사',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:tourism-manager','0141','숙박·여행·오락 및 스포츠 관련 관리자 — tourism-management scope',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:event-planner','0244','행사·전시 및 회의 기획자',null,null,true,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:hospitality-supervisor','0141','숙박·여행·오락 및 스포츠 관련 관리자 — supervisor reference',null,null,false,1,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:hospitality-supervisor','0142','음식 서비스 관련 관리자 — supervisor reference',null,null,false,2,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:hospitality-supervisor','5230','숙박시설 서비스 종사원 — supervisor reference',null,null,false,3,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10'),
('KR:hospitality-supervisor','5322','식음료 서비스 종사원 — supervisor reference',null,null,false,4,'https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','Work24 job search','https://www.work24.go.kr/wk/a/b/1200/retriveDtlEmpSrchList.do','government',10,'2026-08-10' from public.country_occupation_profiles p where p.country_code='KR' and p.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','KECO 2025 classification','https://www.keis.or.kr/keis/ko/proj/114/pblc/detail.do?categoryIdx=125&pubIdx=11172','government',20,'2026-08-10' from public.country_occupation_profiles p where p.country_code='KR' and p.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('KR:chef','source','Food Sanitation Act — cook licence context','https://www.law.go.kr/법령/식품위생법','government',30,'2026-08-10'),
('KR:cook','source','Food Sanitation Act — cook licence context','https://www.law.go.kr/법령/식품위생법','government',30,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'KR:'||canonical_career_id,source_program_key,case when relation_type='direct' then 'direct' else 'related' end,coalesce(source_checked_at,'2026-08-09'::date)
from public.program_occupation_kr_v1
where canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
