insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NL:carpenter','NL','carpenter','Carpenter / Timmerman','ISCO-08','2008','7115','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:electrician','NL','electrician','Building and related electrician / Elektromonteur','ISCO-08','2008','7411','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:plumber','NL','plumber','Plumber and pipe fitter / Loodgieter-installatiemonteur','ISCO-08','2008','7126','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:wall-floor-tiler','NL','wall-floor-tiler','Floor layer and tile setter / Tegelzetter','ISCO-08','2008','7122','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:welder','NL','welder','Welder and flame cutter / Lasser','ISCO-08','2008','7212','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:bricklayer','NL','bricklayer','Bricklayer / Metselaar','ISCO-08','2008','7112','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:hvac-technician','NL','hvac-technician','Air-conditioning and refrigeration mechanic / Koude- en klimaatsysteemmonteur','ISCO-08','2008','7127','EUR',true,'Rijkswaterstaat / BRL 200 refrigerant certification system','https://iplo.nl/thema/lucht/ozon-en-f-gassen/certificering/eisen-natuurlijke-personen-monteurs/','profile_ready','2026-08-11',now()),
('NL:construction-manager','NL','construction-manager','Construction Manager / Bouwprojectleider-uitvoerder','ISCO-08','2008','1323','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
