-- Singapore Technology occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:software-developer','SG','software-developer','Software developer','SSOC','2024','25121','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:data-analyst','SG','data-analyst','Statistical officer/Data analyst','SSOC','2024','21231','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:data-engineer','SG','data-engineer','Data engineer','SSOC','2024','25213','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:cybersecurity-analyst','SG','cybersecurity-analyst','Cybersecurity analyst — risk/operations/incident/threat umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:network-administrator','SG','network-administrator','Network/Server/Applications/Computer systems administrator','SSOC','2024','25220','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:cloud-engineer','SG','cloud-engineer','Cloud specialist — cloud-engineering scope','SSOC','2024','25231','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:database-administrator','SG','database-administrator','Data/Database administrator','SSOC','2024','25211','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:ict-support-technician','SG','ict-support-technician','IT support technician','SSOC','2024','35123','SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:software-developer','2026-08-11',0,0,0,0,15,0,0,0,3,18,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the broad software-development scope directly to 25121 Software developer, while web/mobile, DevOps, AI/ML and other specialised roles have separate codes.','entry_level_basis','Computer science, software engineering and related computing degrees are common routes; fifteen approved Singapore programmes are retained as related study pathways because the reviewed staging relation is common_pathway rather than direct occupational qualification.','qualification_note','There is no universal statutory occupational licence required to work as a Software Developer in Singapore.','market_scope','No exact comparable shortage, vacancy, earnings or growth series is scored in this foundation phase.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:data-analyst','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Statistical officer/Data analyst directly to 21231, distinct from 21222 Data scientist and ICT business analyst 25112.','entry_level_basis','Analytics, data science, statistics, economics and quantitative business study are relevant routes; ten approved programmes are retained as related pathways.','qualification_note','There is no universal statutory occupational licence required to work as a Data Analyst in Singapore.','market_scope','Classification evidence is not converted into demand or salary points until the later comparable market-data phase.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:data-engineer','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 provides the direct five-digit occupation 25213 Data engineer, separated from database administration and architecture.','entry_level_basis','Data, computing and engineering degrees can support entry, but production data-platform roles often expect database, programming, cloud and pipeline experience; five approved programmes are retained as related pathways.','qualification_note','There is no universal statutory occupational licence required to work as a Data Engineer in Singapore.','market_scope','No exact shortage, vacancy, earnings or growth component is assigned in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:cybersecurity-analyst','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 does not publish one generic Cybersecurity Analyst five-digit code. The canonical analyst scope crosses 25241 Cyber risk specialist, 25243 Security operations specialist, 25246 Cyber incident investigation specialist, 25247 Threat analysis specialist and 25249 Cybersecurity professional n.e.c.','entry_level_basis','Information-security and cybersecurity degrees provide structured entry; two approved Singapore information-security programmes are retained as direct academic pathways, but study does not itself constitute a professional licence.','qualification_note','There is no universal personal occupational licence for every Cybersecurity Analyst. Under the Cybersecurity Act, CSA separately licenses providers of specified services, currently penetration testing and managed SOC monitoring; that provider-service regime is not attributed to every employee analyst role.','market_scope','The multi-code analyst scope is kept explicit and is not collapsed into an unsupported exact labour-market series.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:network-administrator','2026-08-11',0,0,0,0,15,0,0,0,3,18,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps network, server, applications and computer-systems administration to 25220, providing a direct operational infrastructure anchor for the canonical Network Administrator.','entry_level_basis','Computing, computer engineering and information-systems study plus practical network and systems administration skills provide common routes; five approved programmes are retained as related pathways.','qualification_note','There is no universal statutory occupational licence required to work as a Network Administrator in Singapore. Telecommunications or service-provider licences regulate organisations and services rather than this general employee occupation.','market_scope','No exact comparable market components are scored at foundation stage.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:cloud-engineer','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 provides 25231 Cloud specialist as the direct cloud-platform occupation anchor, while DevOps engineer remains separately classified at 25125.','entry_level_basis','Computer science, software engineering and ICT degrees can lead toward cloud work, but production cloud roles commonly require operating-system, networking, automation, security and platform experience; ten approved programmes are related pathways.','qualification_note','There is no universal statutory occupational licence required for Cloud Engineers. Cloud-provider certifications and the MTCS organisational certification scheme are not personal licences to practise this occupation.','market_scope','No exact comparable shortage, vacancy, salary or growth evidence is scored in SG v1 foundation.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:database-administrator','2026-08-11',0,0,0,0,12,0,0,0,3,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Data/Database administrator directly to 25211 and keeps database architecture at 25212 and data engineering at 25213.','entry_level_basis','Computer science, information systems and ICT study can support entry, while dedicated DBA roles commonly value SQL, database operations, backup, recovery and systems experience; eight approved programmes are retained as related pathways.','qualification_note','There is no universal statutory occupational licence required to work as a Database Administrator in Singapore.','market_scope','No exact comparable market components are assigned in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11'),
('SG:ict-support-technician','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 directly identifies 35123 IT support technician, distinct from IT infrastructure technician 35121 and IT security technician 35122.','entry_level_basis','ICT diplomas, computing qualifications, vendor training and practical troubleshooting experience are common entry routes; five approved degree programmes are retained as related rather than direct technician qualifications.','qualification_note','There is no universal statutory occupational licence required to work as an IT Support Technician in Singapore.','market_scope','No exact comparable shortage, vacancy, earnings or growth series is scored in this foundation phase.','visa_scope','No occupation-specific visa credit is assigned in this foundation phase.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:software-developer','25121','Software developer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:data-analyst','21231','Statistical officer/Data analyst',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:data-engineer','25213','Data engineer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cybersecurity-analyst','25241','Cyber risk specialist',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cybersecurity-analyst','25243','Security operations specialist',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cybersecurity-analyst','25246','Cyber incident investigation specialist',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cybersecurity-analyst','25247','Threat analysis specialist',null,null,false,4,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cybersecurity-analyst','25249','Cybersecurity professional n.e.c.',null,null,false,5,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:network-administrator','25220','Network/Server/Applications/Computer systems administrator',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cloud-engineer','25231','Cloud specialist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:database-administrator','25211','Data/Database administrator',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:ict-support-technician','35123','IT support technician',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('software-developer','data-analyst','data-engineer','cybersecurity-analyst','network-administrator','cloud-engineer','database-administrator','ict-support-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('software-developer','data-analyst','data-engineer','cybersecurity-analyst','network-administrator','cloud-engineer','database-administrator','ict-support-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:cybersecurity-analyst','source','CSA Cybersecurity Act and service-provider licensing','https://www.csa.gov.sg/legislation/cybersecurity-act/','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('software-developer','data-analyst','data-engineer','cybersecurity-analyst','network-administrator','cloud-engineer','database-administrator','ict-support-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
