-- Finland Cities Phase 4: exactly five verified metrics for each of eight Tier A municipalities.
with t as (select id,slug,name,code from core.geographies where country_code='FI' and metadata->>'publication_tier'='A'),
v(slug,amount) as (values ('helsinki',694392::numeric),('espoo',325716),('tampere',263337),('turku',209633),('oulu',217469),('jyvaskyla',149895),('lappeenranta',73241),('joensuu',79129))
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select md5('fi_city_phase4:'||t.id||':city_population')::uuid,t.id,'city',t.id::text,'city_population',jsonb_build_object('amount',v.amount,'geography',t.name||' municipality','geography_kind','statistics_finland_municipality','municipality_code',t.code,'estimate_kind','registered_population_year_end','estimate_date','2025-12-31'),'Statistics Finland — Population structure','https://pxdata.stat.fi/PxWeb/pxweb/en/StatFin/StatFin__vaerak/statfin_vaerak_pxt_11rf.px/','2025-12-31',now(),'high','observed','verified',now(),now() from t join v using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence=excluded.confidence,evidence_kind=excluded.evidence_kind,review_status='verified',updated_at=now();

with t as (select id from core.geographies where country_code='FI' and metadata->>'publication_tier'='A')
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select md5('fi_city_phase4:'||t.id||':student_living_cost_monthly_range')::uuid,t.id,'city',t.id::text,'student_living_cost_monthly_range',jsonb_build_object('low',900,'high',1200,'currency','EUR','period','month','reference_scope','national_student_budget_planning_range','city_specific',false,'indicative',true,'official_migri_minimum_monthly',800,'note','Study in Finland recommends budgeting approximately EUR 900–1,200 per month depending on location; Migri official minimum is EUR 800/month. The same national planning range is retained across cities and is not a city cost ranking.'),'Study in Finland — Fees and cost of living','https://www.studyinfinland.fi/funding-your-studies/fees-and-cost-living','2026-08-11',now(),'medium','observed','verified',now(),now() from t
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence=excluded.confidence,evidence_kind=excluded.evidence_kind,review_status='verified',updated_at=now();

with t as (select id,slug from core.geographies where country_code='FI' and metadata->>'publication_tier'='A'),
v(slug,amount,period,kind,note,source,url,evidence_kind) as (values
 ('helsinki',44.34::numeric,'30_days','hsl_ab_student_season_calculated','40% student discount applied to the 2026 adult one-off 30-day AB fare of EUR 73.90; discount eligibility depends on HSL student criteria.','HSL — 2026 fares and student discount','https://www.hsl.fi/en/hsl/news/news/2025/10/hsl-fares-in-2026','calculated'),
 ('espoo',44.34,'30_days','hsl_ab_student_season_calculated','40% student discount applied to the 2026 adult one-off 30-day AB fare of EUR 73.90; discount eligibility depends on HSL student criteria.','HSL — 2026 fares and student discount','https://www.hsl.fi/en/hsl/news/news/2025/10/hsl-fares-in-2026','calculated'),
 ('tampere',48.00,'30_days','nysse_mobile_student_ab','Full-time student 30-day mobile season ticket, AB reference; ABC costs more.','Nysse — Student season ticket / fares','https://www.nysse.fi/en/tickets-and-fares/season-ticket.html','observed'),
 ('turku',1.90,'2_hours','foli_student_value_ticket','Student value-card journey reference; student discount requires Föli eligibility. This is intentionally source-native rather than converted to a monthly price.','Föli — student discount and fares','https://www.foli.fi/en/tickets/travel-cards/students','observed'),
 ('oulu',52.00,'30_days','osl_student_season','Student 30-day season ticket; current source-native season product.','Oulu Regional Transport — 2026 fares','https://www.osl.fi/en/fares2026/','observed'),
 ('jyvaskyla',42.00,'30_days','linkki_student_one_zone_season','Youth/student/senior 30-day one-zone season ticket.','Linkki — Prices','https://linkki.jyvaskyla.fi/en/liput-ja-hinnat/prices','observed'),
 ('lappeenranta',47.00,'30_days','jouko_student_one_zone_season','Student 30-day one-zone season ticket for Lappeenranta regional public transport.','City of Lappeenranta — Tickets and fares','https://lappeenranta.fi/en/public-transport/tickets-and-fares-in-public-transport','observed'),
 ('joensuu',49.00,'30_days','jojo_student_one_zone_season','Youth/student 30-day one-zone season ticket.','JOJO — Season Ticket','https://jojo.joensuu.fi/en/tickets/season-ticket/','observed')
)
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select md5('fi_city_phase4:'||t.id||':student_transport_reference')::uuid,t.id,'city',t.id::text,'student_transport_reference',jsonb_build_object('amount',v.amount,'currency','EUR','period',v.period,'reference_kind',v.kind,'student_specific',true,'source_native_period',true,'note',v.note),v.source,v.url,'2026-08-11',now(),'high',v.evidence_kind,'verified',now(),now() from t join v using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence=excluded.confidence,evidence_kind=excluded.evidence_kind,review_status='verified',updated_at=now();

with t as (select id from core.geographies where country_code='FI' and metadata->>'publication_tier'='A')
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select md5('fi_city_phase4:'||t.id||':student_work_hours_week')::uuid,t.id,'city',t.id::text,'student_work_hours_week',jsonb_build_object('hours_normal_period',30,'period','week_average','average_reference_period','calendar_year','monthly_average_hours',120,'annual_hours',1560,'national_rule',true,'degree_related_training_exception',true,'note','A residence permit for studies allows paid employment in any field for an average of 30 hours/week. Individual weeks may exceed 30 if the year-end average stays within the limit. Degree-related practical training or diploma work can be outside the normal limit under Migri conditions.'),'Finnish Immigration Service — Working and internships during studies','https://migri.fi/en/working-and-internships-during-studies','2026-08-11',now(),'high','observed','verified',now(),now() from t
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence=excluded.confidence,evidence_kind=excluded.evidence_kind,review_status='verified',updated_at=now();

with t as (select id,slug from core.geographies where country_code='FI' and metadata->>'publication_tier'='A'),
v(slug,basis,sectors,source,url) as (values
 ('helsinki','City of Helsinki 2025–2029 business-growth focus themes','["Health and wellbeing","Maritime cluster","Circular economy in construction","Creative industries","Food industry"]'::jsonb,'City of Helsinki — Business Helsinki strategy focus','https://www.hel.fi/en/business-and-work/what-is-business-helsinki'),
 ('espoo','City of Espoo innovation and deep-tech ecosystem strengths','["Deep tech","Microelectronics and semiconductors","5G and 6G","Quantum technology","Health and MedTech with AI","Clean energy and sustainable materials"]'::jsonb,'City of Espoo — Innovative Espoo','https://www.espoo.fi/en/city-and-decision-making/innovative-espoo'),
 ('tampere','Business Tampere current ecosystem and industry networks','["Manufacturing and intelligent machines","ICT and AI","Health technology and life sciences","Cybersecurity"]'::jsonb,'Business Tampere — Ecosystems and networks','https://businesstampere.com/en/ecosystems-and-networks/manufacturing-industry/'),
 ('turku','Business Turku current key-industry framework','["Blue economy and maritime","Health and life sciences","Security and dual use","Food and nutrition","Clean transition"]'::jsonb,'Business Turku — Key industries','https://businessturku.fi/en/key-industries/'),
 ('oulu','BusinessOulu sector-specific business-development areas','["ICT and wireless technologies","Health and life sciences","Cleantech and industry","Logistics","Creative industries"]'::jsonb,'BusinessOulu — Sector-specific services','https://www.businessoulu.com/en/businesses-and-entrepreneurs/sector-specific-services/'),
 ('jyvaskyla','City of Jyväskylä four key sectors','["Exercise, health and wellbeing","Industry renewal","ICT and cybersecurity","Education expertise and export"]'::jsonb,'City of Jyväskylä Business Development — Key sectors','https://elinkeinopalvelut.jyvaskyla.fi/en/verkostot/karkialat'),
 ('lappeenranta','City of Lappeenranta business networks and green/industrial strengths','["Energy and environmental technology","Green transition","Metal industry","Research-based and knowledge-intensive business"]'::jsonb,'City of Lappeenranta — Business networks','https://lappeenranta.fi/en/business-services/networks'),
 ('joensuu','Business Joensuu current investment-industry strengths','["Forest bioeconomy and circular economy","Photonics","Digital border security","Mining and minerals","Green transition and energy","Metal and plastics manufacturing"]'::jsonb,'Business Joensuu — Key industries','https://businessjoensuu.fi/en/invest-in-joensuu/key-industries')
)
insert into public.report_metric_evidence_city(id,geography_id,scope_type,scope_id,metric_key,value,source_name,source_url,data_as_of,last_verified_at,confidence,evidence_kind,review_status,created_at,updated_at)
select md5('fi_city_phase4:'||t.id||':employment_focus_sectors')::uuid,t.id,'city',t.id::text,'employment_focus_sectors',jsonb_build_object('basis',v.basis,'sectors',v.sectors,'indicative',true,'not_shortage_ranking',true,'note','Official/local economic-development context; not a shortage ranking, job guarantee or occupation-level demand score.'),v.source,v.url,'2026-08-11',now(),'medium','observed','verified',now(),now() from t join v using(slug)
on conflict(geography_id,metric_key) do update set value=excluded.value,source_name=excluded.source_name,source_url=excluded.source_url,data_as_of=excluded.data_as_of,last_verified_at=now(),confidence=excluded.confidence,evidence_kind=excluded.evidence_kind,review_status='verified',updated_at=now();

do $$ declare n integer; bad integer; begin
  select count(*) into n from public.report_metric_evidence_city r join core.geographies g on g.id=r.geography_id where g.country_code='FI' and g.metadata->>'publication_tier'='A' and r.review_status='verified' and r.metric_key in ('city_population','student_living_cost_monthly_range','student_transport_reference','student_work_hours_week','employment_focus_sectors');
  if n<>40 then raise exception 'FI Tier A metrics expected 40, found %',n; end if;
  select count(*) into bad from (select g.id from core.geographies g left join public.report_metric_evidence_city r on r.geography_id=g.id and r.review_status='verified' and r.metric_key in ('city_population','student_living_cost_monthly_range','student_transport_reference','student_work_hours_week','employment_focus_sectors') where g.country_code='FI' and g.metadata->>'publication_tier'='A' group by g.id having count(r.metric_key)<>5) q;
  if bad<>0 then raise exception 'Each FI Tier A city must have five verified metrics'; end if;
end $$;
