insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NL:early-childhood-teacher','NL','early-childhood-teacher','Early Childhood Educators — childcare / pedagogical education scope','ISCO-08','2008','2342','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:primary-school-teacher','NL','primary-school-teacher','Primary School Teachers','ISCO-08','2008','2341','EUR',true,'DUO / Ministry of Education, Culture and Science','https://duo.nl/particulier/buitenlands-diploma-in-nederland/werken-als-leraar.jsp','profile_ready','2026-08-12',now()),
('NL:secondary-school-teacher','NL','secondary-school-teacher','Secondary Education Teachers','ISCO-08','2008','2330','EUR',true,'DUO / Ministry of Education, Culture and Science','https://duo.nl/particulier/buitenlands-diploma-in-nederland/werken-als-leraar.jsp','profile_ready','2026-08-12',now()),
('NL:special-education-teacher','NL','special-education-teacher','Special Needs Teachers','ISCO-08','2008','2352','EUR',true,'DUO / Ministry of Education, Culture and Science','https://duo.nl/particulier/buitenlands-diploma-in-nederland/werken-als-leraar.jsp','profile_ready','2026-08-12',now()),
('NL:social-worker','NL','social-worker','Social Work and Counselling Professionals — social-worker scope','ISCO-08','2008','2635','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:youth-worker','NL','youth-worker','Social Work Associate Professionals — youth-services scope','ISCO-08','2008','3412','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:community-worker','NL','community-worker','Social Work Associate Professionals — community-services scope','ISCO-08','2008','3412','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:counsellor','NL','counsellor','Social Work and Counselling Professionals — non-clinical counselling scope','ISCO-08','2008','2635','EUR',false,null,null,'profile_ready','2026-08-12',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
