-- Canada Physiotherapist occupation profile; exact NOC 31202.
insert into public.country_occupation_profiles(profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values('CA:physiotherapist','CA','physiotherapist','Physiotherapists','NOC','2021 Version 1.0','31202','CAD',true,'Provincial physiotherapy regulators; CAPR provides national assessment services outside Quebec','https://alliancept.org/internationally-trained/credentialing-overview/','profile_ready','2026-08-09',now())
on conflict(profile_key) do update set official_title=excluded.official_title,official_unit_group_code=excluded.official_unit_group_code,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots(profile_key,as_of_date,employment_total,median_hourly_earnings,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values('CA:physiotherapist','2025-11-19',38300,46.15,15,0,0,0,13,10,0,10,2,50,'career-opportunity-ca-v1','provisional',jsonb_build_object('classification_scope','Exact NOC 31202 Physiotherapists.','shortage_note','COPS moderate risk of shortage nationally for 2024-2033.','visa_basis','Current IRCC healthcare and social services category includes NOC 31202.','registration_basis','CAPR credentialling and Canadian Physiotherapy Examination support licensure outside Quebec; provincial regulator grants the licence.','program_gap','Current direct entry-to-practice international routes are not presently open/publicly established in the verified catalogue; no programme link is published.'),'2026-08-09')
on conflict(profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,shortage_component=excluded.shortage_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations(profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at)
values('CA:physiotherapist','31202','Physiotherapists',null,true,true,1,'https://noc.esdc.gc.ca/Structure/NOCProfile?GocTemplateCulture=en-CA&code=31202&version=2021.0','2026-08-09')
on conflict(profile_key,official_code) do update set official_title=excluded.official_title,visa_eligible=excluded.visa_eligible,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links(profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('CA:physiotherapist','job_search','Job Bank — Physiotherapist in Canada','https://www.jobbank.gc.ca/marketreport/summary-occupation/18214/ca','official_job_board',null,1,'2026-08-09'),
('CA:physiotherapist','source','CAPR — Credentialling Overview','https://alliancept.org/internationally-trained/credentialing-overview/','official_regulator_network',null,1,'2026-08-09'),
('CA:physiotherapist','source','IRCC — Express Entry category-based selection','https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/rounds-invitations/category-based-selection.html','official_immigration',null,2,'2026-08-09')
on conflict(profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,source_checked_at=excluded.source_checked_at;
