ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA labour REVOKE ALL PRIVILEGES ON TABLES FROM service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA labour GRANT SELECT ON TABLES TO service_role;
