-- Singapore Hospitality / Tourism occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:chef','SG','chef','Chef (excluding pastry chef)','SSOC','2024','34341','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:cook','SG','cook','Cook','SSOC','2024','51201','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:hotel-manager','SG','hotel-manager','Hotel operations/Lodging services manager','SSOC','2024','14110','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:restaurant-manager','SG','restaurant-manager','Restaurant manager','SSOC','2024','14121','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:baker','SG','baker','Baker','SSOC','2024','75121','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:tourism-manager','SG','tourism-manager','Tourism manager — travel agency/attractions management umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:event-planner','SG','event-planner','Exhibition/Conference/Event planner','SSOC','2024','33320','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:hospitality-supervisor','SG','hospitality-supervisor','Hospitality supervisor — kitchen/service/gaming/housekeeping umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:chef','2026-08-11',0,0,0,0,15,0,0,0,4,19,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 34341 Chef (excluding pastry chef) is the primary general-chef anchor; pastry chef 34343 remains a separate reference.','entry_level_basis','Chef work is practically accessible through culinary training and supervised kitchen experience; no approved SG programme link is currently present.','qualification_note','There is no universal Chef occupational licence. In SFA-licensed food businesses, anyone handling or preparing food must meet WSQ Food Safety Course Level 1 training/retraining requirements and be registered as a Food Handler.','market_scope','No shortage, vacancy, salary or growth points are inferred from food-safety regulation.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:cook','2026-08-11',0,0,0,0,15,0,0,0,4,19,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 51201 Cook is the direct general-cook anchor; 51202 Senior cook remains a separate seniority reference.','entry_level_basis','Cook is a practical kitchen occupation that can be entered through vocational training and supervised experience; no approved SG programme link is currently present.','qualification_note','There is no universal Cook occupational licence, but food handlers in SFA-licensed establishments must complete the required food-safety training and registration.','market_scope','Food-handler compliance is not treated as labour-demand evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:hotel-manager','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 14110 Hotel operations/Lodging services manager directly anchors the canonical hotel-management role.','entry_level_basis','One approved Hospitality and Tourism Management programme is retained as a related pathway; management roles normally require operational responsibility in addition to study.','qualification_note','Singapore regulates hotel operations through establishment/operator licensing. CampCareer does not treat the broad Hotel Manager employee role as universally requiring a personal occupational licence.','market_scope','No hotel-demand, salary or vacancy figures are scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:restaurant-manager','2026-08-11',0,0,0,0,10,0,0,0,3,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 14121 Restaurant manager directly anchors restaurant operations management.','entry_level_basis','One approved Hospitality and Tourism Management programme is a related pathway; practical food-service operations and supervisory experience remain important.','qualification_note','Food Shop licences attach to the food business/operator, not every Restaurant Manager personally. A manager who handles food or is appointed as a Food Hygiene Officer can have separate mandatory SFA training and registration requirements.','market_scope','Food-safety licensing is not converted into demand or salary evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:baker','2026-08-11',0,0,0,0,15,0,0,0,4,19,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 75121 Baker directly anchors bread and baking production; 75122 Pastry/Confectionery maker remains separate.','entry_level_basis','Baking is a practical trade accessible through vocational training and supervised production experience; no approved SG programme link is currently present.','qualification_note','There is no universal Baker occupational licence. Bakers working as Food Handlers in SFA-licensed retail or manufacturing establishments must meet food-safety training/retraining and registration requirements.','market_scope','No labour-market credit is inferred from food establishment regulation.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:tourism-manager','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Singapore has no single five-digit SSOC occupation titled Tourism Manager. CampCareer preserves 14392 Travel agency manager and 14322 Attractions manager as non-rollup references for the broader tourism-product and visitor-experience scope.','entry_level_basis','One approved Hospitality and Tourism Management programme is retained as a related pathway; managerial tourism roles commonly require sector and commercial experience.','qualification_note','Travel Agent licensing applies to the business of supplying travel arrangements or tours, while Tourist Guide licensing applies to individuals personally providing remunerated guiding services. Neither is treated as a universal personal licence for every Tourism Manager.','market_scope','The two management references are not aggregated into a fabricated exact tourism-manager market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:event-planner','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 33320 Exhibition/Conference/Event planner directly covers planning and coordinating conferences, exhibitions and events; 14391 Event manager is retained as a separate managerial-seniority reference.','entry_level_basis','Event planning is accessible through event, hospitality, communications or business preparation plus practical delivery experience. One approved hospitality programme is related.','qualification_note','There is no universal personal occupational registration for Event Planners. Venue, public-space, liquor, entertainment or other event-specific permits remain separate.','market_scope','Event-specific permitting does not establish shortage or demand.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:hospitality-supervisor','2026-08-11',0,0,0,0,15,0,0,0,4,19,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Singapore does not have one cross-venue five-digit Hospitality Supervisor occupation. CampCareer uses kitchen operations head/supervisor 34342, waiter supervisor 51311, gaming supervisor 51701 and hotel housekeeping matron 51503 as non-rollup references.','entry_level_basis','Frontline hospitality supervision is commonly reached through operational experience and vocational or hospitality study; one approved Hospitality and Tourism Management programme is related.','qualification_note','There is no universal Hospitality Supervisor occupational licence. Supervisors who handle food, or who are appointed as Food Hygiene Officers in establishments that require one, can have mandatory SFA food-safety certification and registration obligations.','market_scope','Distinct supervisor occupations are not aggregated into unsupported labour-market metrics.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:chef','34341','Chef (excluding pastry chef)',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:chef','34343','Pastry chef — separate specialist reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cook','51201','Cook',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:cook','51202','Senior cook — seniority reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hotel-manager','14110','Hotel operations/Lodging services manager',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:restaurant-manager','14121','Restaurant manager',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:baker','75121','Baker',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:baker','75122','Pastry/Confectionery maker — separate reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:tourism-manager','14392','Travel agency manager — tourism-management reference',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:tourism-manager','14322','Attractions manager — visitor-experience reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:event-planner','33320','Exhibition/Conference/Event planner',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:event-planner','14391','Event manager — managerial-seniority reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hospitality-supervisor','34342','Kitchen operations head/supervisor',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hospitality-supervisor','51311','Captain waiter/Waiter supervisor',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hospitality-supervisor','51701','Gaming supervisor',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:hospitality-supervisor','51503','Housekeeping matron — hotel housekeeping-supervision reference',null,null,false,4,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:chef','source','SFA — Requirements for Food Handlers','https://www.sfa.gov.sg/food-handler-hygiene-officer/requirements-for-food-handler-hygiene-officer/requirements-for-food-handlers','government',30,'2026-08-11'),
('SG:cook','source','SFA — Requirements for Food Handlers','https://www.sfa.gov.sg/food-handler-hygiene-officer/requirements-for-food-handler-hygiene-officer/requirements-for-food-handlers','government',30,'2026-08-11'),
('SG:baker','source','SFA — Requirements for Food Handlers','https://www.sfa.gov.sg/food-handler-hygiene-officer/requirements-for-food-handler-hygiene-officer/requirements-for-food-handlers','government',30,'2026-08-11'),
('SG:restaurant-manager','source','SFA — Food Retail Licence Requirements','https://www.sfa.gov.sg/food-retail/licence-permit/requirements-for-licence-permit-for-food-retail','government',30,'2026-08-11'),
('SG:restaurant-manager','source','SFA — Requirements for Food Hygiene Officers','https://www.sfa.gov.sg/food-handler-hygiene-officer/requirements-for-food-handler-hygiene-officer/requirements-for-food-hygiene-officers','government',31,'2026-08-11'),
('SG:hospitality-supervisor','source','SFA — Requirements for Food Hygiene Officers','https://www.sfa.gov.sg/food-handler-hygiene-officer/requirements-for-food-handler-hygiene-officer/requirements-for-food-hygiene-officers','government',30,'2026-08-11'),
('SG:hotel-manager','source','STB — Licensing overview','https://www.stb.gov.sg/licensing-support/licenses/overview-of-licensing/','government',30,'2026-08-11'),
('SG:tourism-manager','source','STB — Travel Agent Licence','https://www.stb.gov.sg/licensing-support/licenses/travel-agent-licence/','government',30,'2026-08-11'),
('SG:tourism-manager','source','STB — Tourist Guide Licence','https://www.stb.gov.sg/licensing-support/licenses/tourist-guide-licence/','government',31,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('chef','cook','hotel-manager','restaurant-manager','baker','tourism-manager','event-planner','hospitality-supervisor')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
