-- Canada Medical Laboratory Technician profile; NOC 33101 includes this exact example title but is a broader technical group.
insert into public.country_occupation_profiles(profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at)
values('CA:medical-laboratory-technician','CA','medical-laboratory-technician','Medical laboratory assistants and related technical occupations','NOC','2021 Version 1.0','33101','CAD',false,null,'https://www.jobbank.gc.ca/marketreport/requirements/4211/ca','profile_ready','2026-08-09',now())
on conflict(profile_key) do update set official_title=excluded.official_title,official_unit_group_code=excluded.official_unit_group_code,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots(profile_key,as_of_date,employment_total,median_hourly_earnings,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at)
values('CA:medical-laboratory-technician','2025-11-19',null,27.00,15,0,0,0,10,4,0,10,4,43,'career-opportunity-ca-v1','provisional',jsonb_build_object('classification_scope','Medical Laboratory Technician is an official example title within broader NOC 33101; NOC 32120 Medical Laboratory Technologists is excluded.','shortage_note','COPS strong shortage risk applies to broader NOC 33101, so canonical credit is capped at 15/20.','visa_basis','Current IRCC healthcare and social services category includes NOC 33101.','registration_basis','Job Bank records NOC 33101 as not regulated; CSMLS certification is usually required by employers.','program_basis','Only scope-aligned approved direct ca-program:4173 Medical Laboratory Assistant is linked; Medical Laboratory Technology programmes are not automatically treated as technician routes.'),'2026-08-09')
on conflict(profile_key,as_of_date) do update set employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,shortage_component=excluded.shortage_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations(profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at)
values('CA:medical-laboratory-technician','33101','Medical laboratory assistants and related technical occupations',null,true,true,1,'https://noc.esdc.gc.ca/Structure/NOCProfile?GocTemplateCulture=en-CA&code=33101&version=2021.0','2026-08-09')
on conflict(profile_key,official_code) do update set official_title=excluded.official_title,visa_eligible=excluded.visa_eligible,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links(profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at) values
('CA:medical-laboratory-technician','job_search','Job Bank — Medical Laboratory Technician in Canada','https://www.jobbank.gc.ca/marketreport/summary-occupation/4211/ca','official_job_board',null,1,'2026-08-09'),
('CA:medical-laboratory-technician','source','Job Bank — Medical Laboratory Technician requirements','https://www.jobbank.gc.ca/marketreport/requirements/4211/ca','official_job_board',null,1,'2026-08-09'),
('CA:medical-laboratory-technician','source','IRCC — Express Entry category-based selection','https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry/rounds-invitations/category-based-selection.html','official_immigration',null,2,'2026-08-09')
on conflict(profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links(profile_key,program_ref,relation_type,source_checked_at)
values('CA:medical-laboratory-technician','ca-program:4173','direct','2026-08-09')
on conflict(profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
