-- Singapore Transport / Logistics occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:truck-driver','SG','truck-driver','Heavy truck/Lorry driver — multi-code umbrella','SSOC','2024',null,'SGD',true,'Singapore Police Force — Traffic Police','https://www.police.gov.sg/Knowledge-Hub/Traffic/Traffic-Matters/Singapore-Driving-Licence','profile_ready','2026-08-11',now()),
('SG:logistics-coordinator','SG','logistics-coordinator','Logistics coordinator — planning/shipping coordination umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:aircraft-maintenance-technician','SG','aircraft-maintenance-technician','Aircraft maintenance technician — aeronautical/engine maintenance umbrella','SSOC','2024',null,'SGD',true,'Civil Aviation Authority of Singapore (CAAS)','https://www.caas.gov.sg/personnel-licensing/aircraft-maintenance-personnel/','profile_ready','2026-08-11',now()),
('SG:commercial-pilot','SG','commercial-pilot','Commercial pilot — airline/non-airline pilot umbrella','SSOC','2024',null,'SGD',true,'Civil Aviation Authority of Singapore (CAAS)','https://www.caas.gov.sg/personnel-licensing/flight-crew-pilot/commercial-pilot-licence/','profile_ready','2026-08-11',now()),
('SG:marine-engineer','SG','marine-engineer','Marine engineering officer','SSOC','2024','31510','SGD',true,'Maritime and Port Authority of Singapore (MPA)','https://www.mpa.gov.sg/singapore-registry-of-ships/seafarer-training-and-certification/seafarer-certification','profile_ready','2026-08-11',now()),
('SG:deck-officer','SG','deck-officer','Ship''s deck navigating officer','SSOC','2024','31521','SGD',true,'Maritime and Port Authority of Singapore (MPA)','https://www.mpa.gov.sg/singapore-registry-of-ships/seafarer-training-and-certification/seafarer-certification','profile_ready','2026-08-11',now()),
('SG:warehouse-manager','SG','warehouse-manager','Supply and distribution/Logistics/Warehousing manager','SSOC','2024','13241','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:automotive-service-technician','SG','automotive-service-technician','Automotive mechanic','SSOC','2024','72310','SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:truck-driver','2026-08-11',0,0,0,0,15,0,0,0,2,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 8332 separates heavy truck and lorry driving into lorry, trailer-truck, concrete-mix, waste-truck and other heavy-truck occupations; no fake single five-digit code is used.','entry_level_basis','Practical driving entry is accessible, but the driver must hold the Singapore driving-licence class appropriate to the heavy vehicle.','qualification_note','Traffic Police Class 4 covers load-carrying vehicles above the stated unladen-weight threshold; Class 5 covers specified heavier non-load vehicles.','market_scope','No exact shortage, vacancy, salary or growth series is scored in foundation.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:logistics-coordinator','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Singapore has no single five-digit Logistics Coordinator title. Planning-heavy work aligns with 33461 Logistics/Production planner while shipment-documentation coordination overlaps 43231 Shipping clerk and 43239 Transport clerk n.e.c.','entry_level_basis','Three approved supply-chain/maritime programmes are related pathways; operations experience can also provide entry.','qualification_note','No universal personal occupational licence is identified.','market_scope','Reference codes are not aggregated into fabricated market metrics.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:aircraft-maintenance-technician','2026-08-11',0,0,0,0,12,0,0,0,1,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The canonical technician spans SSOC 31211 Aeronautical engineering technician and 72320 Aircraft engine mechanic/repairer rather than one exact code.','entry_level_basis','Technical and work-study routes are relevant; two approved degree programmes are related rather than licence-conferring pathways.','qualification_note','CAAS states that an Aircraft Maintenance (Personnel) Licence is required to perform, supervise or certify maintenance work on a Singapore-registered aircraft of the applicable type; SAR-66 examination, experience and rating requirements apply.','market_scope','Licensing is not converted into demand evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:commercial-pilot','2026-08-11',0,0,0,0,8,0,0,0,1,9,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC separates 21721 Commercial airline pilot from 21722 Aircraft pilot excluding commercial airline and air force; the broader CampCareer Commercial Pilot role therefore has no single primary code.','entry_level_basis','Entry requires approved flight training, theoretical examinations, flight tests, flying experience and Class 1 medical fitness.','qualification_note','CAAS requires a CPL for specified commercial public-transport/aerial-work operations, with ATPL or MPL requirements applying to other commercial flight capacities.','market_scope','No market component is inferred from licence scarcity or airline activity.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:marine-engineer','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 31510 Marine engineering officer directly matches the seagoing operational engineering-officer scope; 21711 Chief/Second engineer is retained as senior progression.','entry_level_basis','Marine-engineering study plus required sea service and competency assessment form the seagoing pathway. One approved programme is direct educational preparation.','qualification_note','MPA requires valid STCW-compliant Certificate of Competency or endorsement for seafarers serving in officer capacities.','market_scope','No shortage, salary or vacancy points are assigned at foundation stage.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:deck-officer','2026-08-11',0,0,0,0,10,0,0,0,1,11,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 31521 Ship''s deck navigating officer directly covers navigating officers; 21713 Ship captain/Chief mate is retained as senior progression and harbour pilot 31522 stays separate.','entry_level_basis','Nautical training, sea service, STCW courses and competency assessment are central. The approved Maritime Studies programme is related rather than a CoC-conferring pathway.','qualification_note','MPA requires valid STCW-compliant Certificate of Competency or endorsement for officers serving onboard ships.','market_scope','Certification is not converted into labour-demand points.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:warehouse-manager','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 13241 Supply and distribution/Logistics/Warehousing manager directly covers warehouse management.','entry_level_basis','Warehouse managers normally progress through logistics operations and supervisory responsibility; two approved supply-chain programmes are related pathways.','qualification_note','No universal personal occupational licence is identified; premises, dangerous-goods, forklift and workplace-safety duties remain separate controls.','market_scope','No exact 13241 market series is scored yet.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:automotive-service-technician','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 72310 Automotive mechanic directly matches the canonical vehicle-service and repair scope.','entry_level_basis','Applied automotive technical training and supervised workshop experience are practical routes; no approved Singapore programme mapping is currently present.','qualification_note','No universal personal statutory occupational licence is identified for Automotive Mechanics; workshop, inspection and specialist activity requirements are separate.','market_scope','No labour-market component is inferred from vehicle regulation.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:truck-driver','83321','Lorry driver',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:truck-driver','83322','Trailer-truck driver',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:truck-driver','83323','Concrete mix truck driver',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:truck-driver','83324','Waste truck driver',null,null,false,4,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:truck-driver','83329','Heavy truck/Lorry driver n.e.c.',null,null,false,5,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:logistics-coordinator','33461','Logistics/Production planner',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:logistics-coordinator','43231','Shipping clerk',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:logistics-coordinator','43239','Transport clerk n.e.c.',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:aircraft-maintenance-technician','31211','Aeronautical engineering technician',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:aircraft-maintenance-technician','72320','Aircraft engine mechanic/repairer',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:commercial-pilot','21721','Commercial airline pilot',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:commercial-pilot','21722','Aircraft pilot (excluding commercial airline and air force)',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:marine-engineer','31510','Marine engineering officer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:marine-engineer','21711','Chief/Second engineer (ship) — senior progression',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:deck-officer','31521','Ship''s deck navigating officer',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:deck-officer','21713','Ship captain/Chief mate — senior progression',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:warehouse-manager','13241','Supply and distribution/Logistics/Warehousing manager',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:automotive-service-technician','72310','Automotive mechanic',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:truck-driver','source','Traffic Police — Singapore Driving Licence','https://www.police.gov.sg/Knowledge-Hub/Traffic/Traffic-Matters/Singapore-Driving-Licence','government',30,'2026-08-11'),
('SG:aircraft-maintenance-technician','source','CAAS — Aircraft maintenance personnel licensing','https://www.caas.gov.sg/personnel-licensing/aircraft-maintenance-personnel/','government',30,'2026-08-11'),
('SG:commercial-pilot','source','CAAS — Commercial Pilot Licence','https://www.caas.gov.sg/personnel-licensing/flight-crew-pilot/commercial-pilot-licence/','government',30,'2026-08-11'),
('SG:marine-engineer','source','MPA — Seafarer Certification','https://www.mpa.gov.sg/singapore-registry-of-ships/seafarer-training-and-certification/seafarer-certification','government',30,'2026-08-11'),
('SG:deck-officer','source','MPA — Seafarer Certification','https://www.mpa.gov.sg/singapore-registry-of-ships/seafarer-training-and-certification/seafarer-certification','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('truck-driver','logistics-coordinator','aircraft-maintenance-technician','commercial-pilot','marine-engineer','deck-officer','warehouse-manager','automotive-service-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
