insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:civil-engineer','IE','civil-engineer','Civil engineers','SOC','SOC 2010','2121','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:mechanical-engineer','IE','mechanical-engineer','Mechanical engineers','SOC','SOC 2010','2122','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:electrical-engineer','IE','electrical-engineer','Electrical engineers','SOC','SOC 2010','2123','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:manufacturing-engineer','IE','manufacturing-engineer','Production and process engineers — manufacturing engineering scope','SOC','SOC 2010','2127','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:industrial-engineer','IE','industrial-engineer','Production and process engineers — industrial engineering scope','SOC','SOC 2010','2127','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:chemical-engineer','IE','chemical-engineer','Production and process engineers — Chemical Engineer scope','SOC','SOC 2010','2127','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:environmental-engineer','IE','environmental-engineer','Engineering professionals n.e.c. — environmental engineering scope','SOC','SOC 2010','2129','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:engineering-technician','IE','engineering-technician','Engineering technicians','SOC','SOC 2010','3113','EUR',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:civil-engineer','2026-08-10',null,null,null,20,0,0,0,8,0,0,10,5,43,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2121 Civil engineers.','shortage_note','SOLAS National Skills Bulletin 2025 directly identifies civil engineers as a current construction shortage; 20/20.','visa_basis','SOC 2121 Civil Engineers, including structural and site engineers, is explicitly on the current Critical Skills Occupations List; 10/10.','growth_boundary','Broad engineering/construction demand context is not converted into an exact occupation growth rate; 0.','salary_method','No current exact comparable Irish occupation-level median salary series has been normalised; 0.','entry_basis','Degree-level engineering education is the standard professional route, with accredited programmes preferred; 8/15.','entry_burden_basis','Engineers Ireland professional titles are valuable recognition but generic Civil Engineer practice is not universally subject to one personal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:mechanical-engineer','2026-08-10',null,null,null,20,0,0,0,8,0,0,10,5,43,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2122 Mechanical engineers.','shortage_note','SOLAS 2025 directly identifies mechanical engineers as a current science and engineering shortage; 20/20.','visa_basis','SOC 2122 Mechanical engineers is explicitly on the current Critical Skills Occupations List without a narrow specialist qualifier; 10/10.','growth_boundary','Broad science and engineering growth is context only, not an exact occupation growth series; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree-level or equivalent professional engineering formation; 8/15.','entry_burden_basis','No universal personal statutory registration across the generic occupation; 5/5.'),'2026-08-10'),
  ('IE:electrical-engineer','2026-08-10',null,null,null,20,0,0,0,8,0,0,10,5,43,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2123 Electrical engineers, distinct from craft Electrician SOC 5241.','shortage_note','SOLAS 2025 directly identifies electrical engineers as a current shortage; 20/20.','visa_basis','SOC 2123 Electrical engineers is explicitly on the current Critical Skills Occupations List; 10/10.','growth_boundary','Broad engineering demand is not used as an exact growth rate; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree-level electrical engineering or equivalent professional formation; 8/15.','entry_burden_basis','This professional profile is distinct from regulated electrical-contractor/restricted electrical work; no universal personal registration is asserted; 5/5.'),'2026-08-10'),
  ('IE:manufacturing-engineer','2026-08-10',null,null,null,15,0,0,0,8,0,0,8,5,36,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2127 Production and process engineers, constrained to manufacturing engineering.','shortage_note','SOLAS 2025 identifies quality control/assurance, process and design engineers as shortages; Manufacturing Engineer receives strong but non-maximal 15/20 because the published label is broader than this exact title.','visa_basis','SOC 2127 is on the Critical Skills list only for specified production/process specialisms or related relevant specialist skills; generic manufacturing engineering therefore receives conditional 8/10 rather than universal CSEP credit.','growth_boundary','Industrial-sector demand is not converted to exact occupation growth; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Typically degree-level manufacturing, mechanical or production engineering; 8/15.','entry_burden_basis','No universal personal statutory registration across the generic occupation; 5/5.'),'2026-08-10'),
  ('IE:industrial-engineer','2026-08-10',null,null,null,15,0,0,0,8,0,0,8,5,36,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2127 Production and process engineers, industrial engineering/process-optimisation scope.','shortage_note','SOLAS 2025 directly reports process/design engineering shortages; Industrial Engineer receives 15/20 because its canonical scope overlaps but is not identical to the published shortage label.','visa_basis','SOC 2127 CSEP access is specialist-dependent, covering listed process/automation/quality/power skills or related relevant specialisms; conditional 8/10.','growth_boundary','No exact industrial-engineer growth series normalised; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree-level industrial, manufacturing or production engineering is common; 8/15.','entry_burden_basis','No universal statutory personal registration; 5/5.'),'2026-08-10'),
  ('IE:chemical-engineer','2026-08-10',null,null,null,15,0,0,0,8,0,0,10,5,38,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','Ireland employment-permit SOC 2010 treatment places Chemical Engineer in SOC 2127 Production and process engineers.','shortage_note','SOLAS 2025 identifies process engineers as a shortage; Chemical Engineer receives strong 15/20 because the shortage finding is process-wide rather than a separate chemical-engineer count.','visa_basis','Chemical Engineer is explicitly named under SOC 2127 on the current Critical Skills Occupations List; 10/10.','growth_boundary','Pharma/industrial demand context is not converted into an exact occupation growth rate; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree-level chemical/process engineering is the standard route; 8/15.','entry_burden_basis','No universal personal statutory registration across the generic occupation; 5/5.'),'2026-08-10'),
  ('IE:environmental-engineer','2026-08-10',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2129 Engineering professionals n.e.c., constrained to environmental engineering where duties do not resolve to a more specific engineering SOC.','shortage_note','SOLAS expects continued green-engineering demand but does not name Environmental Engineer as a separate current shortage in the reviewed 2025 summary; 0/20.','visa_basis','Generic Environmental Engineer is not explicitly listed as a CSEP employment under SOC 2129; ordinary General Employment Permit accessibility may apply where the role is not ineligible and permit conditions are met; 6/10.','growth_boundary','Green-transition demand context is not an exact occupation growth series; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree-level environmental/civil/process engineering routes are common; 8/15.','entry_burden_basis','Chartered Environmentalist/Engineer titles are professional recognition, not universal statutory registration for every environmental-engineering job; 5/5.'),'2026-08-10'),
  ('IE:engineering-technician','2026-08-10',null,null,null,10,0,0,0,12,0,0,6,5,33,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3113 Engineering technicians, kept separate from 3114 building/civil engineering technicians and discipline-specific professional engineers.','shortage_note','SOLAS 2025 identifies maintenance/manufacturing/lab technicians as shortages. Generic Engineering Technician is broader, so receives limited 10/20 rather than the full signal.','visa_basis','SOC 3113 is not explicitly on the current Critical Skills list; ordinary General Employment Permit accessibility may apply subject to occupation and employer conditions; 6/10.','growth_boundary','Broad technician demand is not used as an exact growth series; 0.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Level 6 technician education and structured apprenticeships such as Civil Engineering Technician provide accessible work-based routes; 12/15.','entry_burden_basis','Engineers Ireland offers the registered professional title Engineering Technician, but it is not asserted as a universal legal licence to work in every engineering-technician job; 5/5.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (
  profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at
) values
  ('IE:civil-engineer','2121','Civil engineers',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:mechanical-engineer','2122','Mechanical engineers',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:electrical-engineer','2123','Electrical engineers',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:manufacturing-engineer','2127','Production and process engineers — manufacturing engineering scope',15,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:industrial-engineer','2127','Production and process engineers — industrial engineering scope',15,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:chemical-engineer','2127','Production and process engineers — Chemical Engineer',15,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:environmental-engineer','2129','Engineering professionals n.e.c. — environmental engineering scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-10'),
  ('IE:engineering-technician','3113','Engineering technicians',10,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (
  profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at
) values
  ('IE:civil-engineer','source','SOLAS — Construction labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/construction/','government',null,1,'2026-08-10'),
  ('IE:civil-engineer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:civil-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:mechanical-engineer','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:mechanical-engineer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:mechanical-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:electrical-engineer','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:electrical-engineer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:electrical-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:manufacturing-engineer','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:manufacturing-engineer','source','DETE — Critical Skills specialist SOC 2127 scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:manufacturing-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:industrial-engineer','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:industrial-engineer','source','DETE — Critical Skills specialist SOC 2127 scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:industrial-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:chemical-engineer','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:chemical-engineer','source','DETE — Critical Skills Chemical Engineer scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:chemical-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:environmental-engineer','source','SOLAS — Science and Engineering labour-market context','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:environmental-engineer','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-10'),
  ('IE:environmental-engineer','entry_program','Engineers Ireland — accredited engineering programmes','https://www.engineersireland.ie/Professionals/Membership/Become-a-member/Accredited-third-level-courses','professional_body',null,3,'2026-08-10'),
  ('IE:engineering-technician','source','SOLAS — Science and Engineering labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/science-and-engineering/','government',null,1,'2026-08-10'),
  ('IE:engineering-technician','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-10'),
  ('IE:engineering-technician','entry_program','Generation Apprenticeship — Civil Engineering Technician L6','https://apprenticeship.ie/career-seekers/get-started/next-steps/engineering/civil-engineering-technician-l6','government',null,3,'2026-08-10'),
  ('IE:engineering-technician','source','Engineers Ireland — Engineering Technician professional title','https://www.engineersireland.ie/Professionals/Membership/Registered-Professional-Titles/Engineering-Technician','professional_body',null,4,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
