insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:environmental-scientist','NZ','environmental-scientist','Environmental Research Scientist (Environmental Scientist)','ANZSCO','1.3','234313','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:agronomist','NZ','agronomist','Agricultural Scientist — Agronomist specialisation','ANZSCO','1.3','234112','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:farm-manager','NZ','farm-manager','Farmer and Farm Manager — broad livestock scope','NZ career scope','2026-08-11',null,'NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:forestry-technician','NZ','forestry-technician','Life Science Technician — Forestry Technician specialisation','ANZSCO','1.3','311413','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:food-technologist','NZ','food-technologist','Food Technologist','ANZSCO','1.3','234212','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:sustainability-specialist','NZ','sustainability-specialist','Sustainability Specialist','NZ career scope','2026-08-11',null,'NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:horticulturist','NZ','horticulturist','Horticulturist — broad horticulture scope','NZ career scope','2026-08-11',null,'NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:animal-science-technician','NZ','animal-science-technician','Agricultural Technician — animal science/husbandry scope','ANZSCO','1.3','311111','NZD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
