insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NL:registered-nurse','NL','registered-nurse','Verpleegkundige / Nursing professional','ISCO-08','2008','2221','EUR',true,'BIG-register','https://www.bigregister.nl/registratie','profile_ready','2026-08-11',now()),
('NL:midwife','NL','midwife','Verloskundige / Midwifery professional','ISCO-08','2008','2222','EUR',true,'BIG-register','https://www.bigregister.nl/registratie','profile_ready','2026-08-11',now()),
('NL:care-worker','NL','care-worker','Verzorgende IG / Health care assistant scope','ISCO-08','2008','5321','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:physiotherapist','NL','physiotherapist','Fysiotherapeut','ISCO-08','2008','2264','EUR',true,'BIG-register','https://www.bigregister.nl/registratie','profile_ready','2026-08-11',now()),
('NL:medical-lab-tech','NL','medical-lab-tech','Biologisch medisch analist / Medical laboratory technician','ISCO-08','2008','3212','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:radiographer','NL','radiographer','Radiodiagnostisch laborant / Medical imaging technician','ISCO-08','2008','3211','EUR',false,null,null,'profile_ready','2026-08-11',now()),
('NL:pharmacist','NL','pharmacist','Apotheker / Pharmacist','ISCO-08','2008','2262','EUR',true,'BIG-register','https://www.bigregister.nl/registratie','profile_ready','2026-08-11',now()),
('NL:occupational-therapist','NL','occupational-therapist','Ergotherapeut / Occupational therapist','ISCO-08','2008','2269','EUR',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
