create table if not exists public.institution_student_sponsor_uk_staging (
  id bigint generated by default as identity primary key,
  source_name text not null default 'UKVI Student sponsor register',
  source_sponsor_key text not null,
  sponsor_name text not null,
  town_city text,
  additional_locations text,
  sponsor_type text,
  sponsor_status text,
  route text,
  immigration_compliance text,
  institution_id uuid references catalog.institutions(id),
  ukprn text,
  match_status text not null default 'unmatched'
    check (match_status in ('unmatched','candidate','matched','rejected')),
  match_basis text,
  source_url text not null,
  source_as_of date not null,
  collected_at timestamptz not null default now(),
  unique (source_name, source_sponsor_key)
);

create index if not exists institution_student_sponsor_uk_staging_institution_idx
  on public.institution_student_sponsor_uk_staging (institution_id, match_status);
create index if not exists institution_student_sponsor_uk_staging_name_idx
  on public.institution_student_sponsor_uk_staging (lower(sponsor_name));

create table if not exists public.program_catalog_uk_staging (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_program_key text not null,
  institution_name text not null,
  institution_id uuid references catalog.institutions(id),
  ukprn text,
  awarding_institution_id uuid references catalog.institutions(id),
  delivery_institution_id uuid references catalog.institutions(id),
  provider_relationship text not null default 'direct_award'
    check (provider_relationship in ('direct_award','validated','franchised','embedded_pathway','joint_award','other','unknown')),
  source_program_name text,
  title text not null,
  qualification_title text,
  native_framework text
    check (native_framework is null or native_framework in ('RQF','FHEQ','SCQF','CQFW','OTHER','UNKNOWN')),
  native_level_code text,
  canonical_level text not null default 'UNKNOWN'
    check (canonical_level in ('BELOW_DEGREE','CERTIFICATE_HE','DIPLOMA_HE','FOUNDATION_DEGREE','BACHELOR','INTEGRATED_MASTER','MASTER','POSTGRADUATE_CERTIFICATE','POSTGRADUATE_DIPLOMA','DOCTORATE','APPRENTICESHIP','OTHER','UNKNOWN')),
  programme_type text,
  field_category text,
  city text,
  campus text,
  duration_months integer check (duration_months is null or duration_months > 0),
  study_mode text,
  official_program_url text not null,
  official_qualification_url text,
  source_as_of date,
  collection_status text not null default 'official_program_verified',
  verification_tier text not null default 'C'
    check (verification_tier in ('A','B','C')),
  legacy_course_id bigint,
  collected_at timestamptz not null default now(),
  unique (source_name, source_program_key)
);

create index if not exists program_catalog_uk_staging_institution_idx
  on public.program_catalog_uk_staging (institution_id);
create index if not exists program_catalog_uk_staging_awarding_idx
  on public.program_catalog_uk_staging (awarding_institution_id);
create index if not exists program_catalog_uk_staging_delivery_idx
  on public.program_catalog_uk_staging (delivery_institution_id);
create index if not exists program_catalog_uk_staging_level_idx
  on public.program_catalog_uk_staging (canonical_level, verification_tier);
create index if not exists program_catalog_uk_staging_title_idx
  on public.program_catalog_uk_staging (lower(title));

create table if not exists public.program_international_uk_staging (
  id bigint generated by default as identity primary key,
  program_catalog_id bigint not null unique references public.program_catalog_uk_staging(id) on delete cascade,
  student_sponsor_record_id bigint references public.institution_student_sponsor_uk_staging(id),
  student_sponsor_eligible boolean,
  international_students_eligible boolean,
  cas_eligibility boolean,
  international_admission_status text not null default 'not_yet_verified',
  language_requirement_context text,
  visa_context text,
  intake_label text,
  intake_start_date date,
  application_deadline date,
  admission_source_url text,
  international_source_url text,
  sponsor_source_url text,
  source_as_of date,
  verification_status text not null default 'not_yet_verified',
  rule_notes text,
  verified_at timestamptz,
  collected_at timestamptz not null default now()
);

create index if not exists program_international_uk_staging_status_idx
  on public.program_international_uk_staging (international_admission_status, international_students_eligible);
create index if not exists program_international_uk_staging_sponsor_idx
  on public.program_international_uk_staging (student_sponsor_record_id);

create table if not exists public.program_occupation_uk_staging (
  program_catalog_id bigint not null references public.program_catalog_uk_staging(id) on delete cascade,
  canonical_career_id text not null,
  rule_version text not null,
  match_basis text not null default 'official_program_title_review',
  match_pattern text not null,
  review_status text not null default 'candidate'
    check (review_status in ('candidate','approved','rejected')),
  relation_type text,
  source_checked_at date,
  reviewer_note text,
  matched_at timestamptz not null default now(),
  reviewed_at timestamptz,
  primary key (program_catalog_id, canonical_career_id)
);

create index if not exists program_occupation_uk_staging_career_idx
  on public.program_occupation_uk_staging (canonical_career_id, review_status);

alter table public.institution_student_sponsor_uk_staging enable row level security;
alter table public.program_catalog_uk_staging enable row level security;
alter table public.program_international_uk_staging enable row level security;
alter table public.program_occupation_uk_staging enable row level security;

revoke all on table public.institution_student_sponsor_uk_staging from public, anon, authenticated;
revoke all on table public.program_catalog_uk_staging from public, anon, authenticated;
revoke all on table public.program_international_uk_staging from public, anon, authenticated;
revoke all on table public.program_occupation_uk_staging from public, anon, authenticated;

grant select, insert, update, delete on table public.institution_student_sponsor_uk_staging to service_role;
grant select, insert, update, delete on table public.program_catalog_uk_staging to service_role;
grant select, insert, update, delete on table public.program_international_uk_staging to service_role;
grant select, insert, update, delete on table public.program_occupation_uk_staging to service_role;

grant usage, select on all sequences in schema public to service_role;

comment on table public.institution_student_sponsor_uk_staging is 'UK Phase 2 staging for Home Office/UKVI Student sponsor evidence; not a public institution allowlist.';
comment on table public.program_catalog_uk_staging is 'UK Phase 2 programme discovery staging. Legacy courses_uk rows are seeds only; rows here require current official programme evidence.';
comment on column public.program_catalog_uk_staging.native_framework is 'Native qualification framework where known; preserve SCQF separately from RQF/FHEQ/CQFW.';
comment on column public.program_catalog_uk_staging.provider_relationship is 'Relationship between delivery and awarding provider; do not infer direct award for validated/franchised provision.';
comment on table public.program_international_uk_staging is 'Programme-level international/Student-route evidence. Institution sponsor status alone does not prove programme eligibility or current admission.';
comment on table public.program_occupation_uk_staging is 'UK programme relationships to the canonical CampCareer 80-career taxonomy.';