insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NL:civil-engineer','NL','civil-engineer','Civil Engineer / Civiel ingenieur','ISCO-08','2008','2142','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:mechanical-engineer','NL','mechanical-engineer','Mechanical Engineer / Werktuigbouwkundig ingenieur','ISCO-08','2008','2144','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:electrical-engineer','NL','electrical-engineer','Electrical Engineer / Elektrotechnisch ingenieur','ISCO-08','2008','2151','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:manufacturing-engineer','NL','manufacturing-engineer','Industrial and Production Engineer — manufacturing engineering scope','ISCO-08','2008','2141','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:industrial-engineer','NL','industrial-engineer','Industrial and Production Engineer — industrial/process optimisation scope','ISCO-08','2008','2141','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:chemical-engineer','NL','chemical-engineer','Chemical Engineer / Chemisch ingenieur','ISCO-08','2008','2145','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:environmental-engineer','NL','environmental-engineer','Environmental Engineer / Milieu-ingenieur','ISCO-08','2008','2143','EUR',false,null,null,'profile_ready','2026-08-12',now()),
('NL:engineering-technician','NL','engineering-technician','Physical and Engineering Science Technician n.e.c. — general engineering technician scope','ISCO-08','2008','3119','EUR',false,null,null,'profile_ready','2026-08-12',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
