-- Singapore Education / Social Services occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:early-childhood-teacher','SG','early-childhood-teacher','Preschool education teacher','SSOC','2024','36100','SGD',true,'Early Childhood Development Agency (ECDA)','https://www.ecda.gov.sg/early-childhood-educators-%28ece%29/becoming-a-certified-educator/educator-certification','profile_ready','2026-08-11',now()),
('SG:primary-school-teacher','SG','primary-school-teacher','Primary school teacher','SSOC','2024','23500','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:secondary-school-teacher','SG','secondary-school-teacher','Secondary school teacher','SSOC','2024','23400','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:special-education-teacher','SG','special-education-teacher','Special education teacher — visual impairment/early intervention/other SPED umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:social-worker','SG','social-worker','Social worker — general/medical/other professional umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:youth-worker','SG','youth-worker','Youth work professional','SSOC','2024','26623','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:community-worker','SG','community-worker','Community worker — social-work-associate/community-services umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:counsellor','SG','counsellor','Counsellor — rehabilitation/addiction/family/school/general umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:early-childhood-teacher','2026-08-11',0,0,0,0,12,0,0,0,1,13,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Preschool education teacher directly to 36100.','entry_level_basis','ECDA-recognised early-childhood training is the regulated preparation route. One reviewed university programme is retained as a direct academic pathway, but ECDA notes that a degree alone is not the basic certification qualification.','qualification_note','ECDA states that educators in Singapore kindergartens and childcare centres must meet the relevant professional, academic and language requirements and obtain educator certification for the age group they teach.','market_scope','Certification and programme availability are not treated as labour-demand evidence; shortage, vacancy, salary and growth remain unscored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:primary-school-teacher','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Primary school teacher directly to 23500.','entry_level_basis','MOE school teaching uses structured teacher-selection and NIE professional preparation pathways, including education degrees and subject-specific diploma routes. No approved SG programme mapping is currently attached to this canonical profile.','qualification_note','MOE appointment and teacher-training requirements are employer and school-system entry requirements rather than one universal statutory personal occupational licence applying to every primary-school teacher in Singapore.','market_scope','Teacher training evidence is not converted into shortage, vacancy, earnings or growth credit in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:secondary-school-teacher','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps Secondary school teacher directly to 23400 and keeps junior-college/pre-university teaching separately at 23200.','entry_level_basis','MOE secondary-school teaching commonly requires subject expertise plus professional teacher preparation through NIE or another accepted appointment pathway. No approved SG programme mapping is currently attached to this canonical profile.','qualification_note','The public-school selection and professional-preparation pathway does not constitute a universal occupational licensing register for every secondary-school teacher across all Singapore employers.','market_scope','No exact recurring occupation-level market inputs are scored in SG v1.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:special-education-teacher','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Special Education Teacher is a deliberate umbrella across SSOC 23621 Teacher of the visually impaired, 23622 Early intervention teacher for infants and children and 23629 Special education teacher n.e.c.','entry_level_basis','SPED teaching requires disability- and learner-specific professional preparation and employer training. MOE and social-service-agency SPED schools operate within the National SPED Curriculum, but no approved canonical SG programme link is currently present.','qualification_note','There is no one universal statutory personal Special Education Teacher licence covering all three SSOC scopes. ECDA certification can apply when work falls within regulated preschool educator deployment, while SPED-school appointment and training requirements apply separately.','market_scope','The three distinct SPED scopes are not merged into a fabricated exact labour-market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:social-worker','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The broad canonical Social Worker spans SSOC 26621 Social worker (general), 26622 Medical social worker and 26629 Social work professional n.e.c.; Youth work professional 26623 is kept in the separate Youth Worker profile.','entry_level_basis','Recognised social-work degrees or graduate diplomas are the core professional preparation. Two approved Singapore Social Work programmes are retained as direct pathways.','qualification_note','Singapore has an MSF-owned, SWAAB-overseen professional accreditation system, but current SASW accreditation guidance explicitly states that accreditation is not mandatory. Employer and sector standards may nevertheless require or strongly prefer recognised social-work qualifications and accreditation.','market_scope','General, medical and other social-work professional scopes are preserved separately and market components remain unscored.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:youth-worker','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 provides the direct professional occupation 26623 Youth work professional. The lower-level 34121 Youth work associate is retained as a related reference but not rolled into the primary professional code.','entry_level_basis','Youth work draws on social work, psychology, counselling and community-service preparation; five approved Singapore programmes are retained as related academic pathways.','qualification_note','There is no universal statutory Youth Worker occupational registration. Safeguarding, screening, employer training and role-specific requirements can apply when working with children, vulnerable young people or residential services.','market_scope','Professional and associate youth-work codes are not collapsed into one unsupported market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:community-worker','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 has no exact five-digit occupation titled Community Worker. CampCareer keeps 34122 Social work associate as the closest practical support reference and 26629 Social work professional n.e.c. as a separate professional community-development reference rather than inventing one exact code.','entry_level_basis','Community work can be entered through social-service, community-development or related study and supervised practice. Three approved Singapore programmes are retained as related pathways.','qualification_note','There is no universal statutory Community Worker licence. Employers can impose safeguarding, casework, programme-delivery, volunteer-management or client-group-specific competency requirements.','market_scope','Associate and professional community-work references remain separate and no exact labour-market series is fabricated.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:counsellor','2026-08-11',0,0,0,0,10,0,0,0,4,14,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','The neutral Counsellor career spans SSOC 26631 rehabilitation, 26632 drugs/alcohol, 26633 family, 26634 school and 26639 counselling professional n.e.c. rather than one exact five-digit code.','entry_level_basis','NCSS describes postgraduate counselling qualifications as the international professional benchmark. The three currently approved Singapore psychology programmes are retained only as related study pathways, not as direct counselling qualifications.','qualification_note','NCSS states that Singapore does not require counsellors to be licensed. Singapore Association for Counselling registration is a professional credential with its own postgraduate and practice requirements, not a universal statutory occupational licence.','market_scope','Counselling specialisations are not aggregated into unsupported exact salary, vacancy or shortage figures at foundation stage.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:early-childhood-teacher','36100','Preschool education teacher',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:primary-school-teacher','23500','Primary school teacher',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:secondary-school-teacher','23400','Secondary school teacher',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:special-education-teacher','23621','Teacher of the visually impaired',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:special-education-teacher','23622','Early intervention teacher for infants and children',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:special-education-teacher','23629','Special education teacher n.e.c.',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:social-worker','26621','Social worker (general)',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:social-worker','26622','Medical social worker',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:social-worker','26629','Social work professional n.e.c.',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:youth-worker','26623','Youth work professional',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:youth-worker','34121','Youth work associate — related scope',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:community-worker','34122','Social work associate — community-support reference',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:community-worker','26629','Social work professional n.e.c. — community-development reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:counsellor','26631','Counsellor (rehabilitation)',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:counsellor','26632','Counsellor (drugs/alcohol)',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:counsellor','26633','Counsellor (family)',null,null,false,3,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:counsellor','26634','School counsellor',null,null,false,4,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:counsellor','26639','Counselling professional n.e.c.',null,null,false,5,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:early-childhood-teacher','source','ECDA Educator Certification','https://www.ecda.gov.sg/early-childhood-educators-%28ece%29/becoming-a-certified-educator/educator-certification','government',30,'2026-08-11'),
('SG:primary-school-teacher','source','MOE/NIE Bachelor of Arts (Academic Discipline and Education)','https://www.moe.gov.sg/coursefinder/coursedetail?course=ared-bachelor-of-arts-academic-discipline-and-education','government',30,'2026-08-11'),
('SG:secondary-school-teacher','source','MOE/NIE Bachelor of Arts (Academic Discipline and Education)','https://www.moe.gov.sg/coursefinder/coursedetail?course=ared-bachelor-of-arts-academic-discipline-and-education','government',30,'2026-08-11'),
('SG:special-education-teacher','source','MOE Special Education — National SPED Curriculum','https://cos.moe.gov.sg/2025-announcements/','government',30,'2026-08-11'),
('SG:social-worker','source','SASW/SWAAB Accreditation FAQ','https://sasw.org.sg/accreditation-faq/','professional_body',30,'2026-08-11'),
('SG:social-worker','source','NCSS Social Work Careers','https://www.ncss.gov.sg/careers/social-service-careers/roles-in-social-services/social-work/','government',31,'2026-08-11'),
('SG:youth-worker','source','NCSS Social Service Careers','https://www.ncss.gov.sg/careers/social-service-careers/roles-in-social-services/social-work/','government',30,'2026-08-11'),
('SG:community-worker','source','NCSS Social Work Careers','https://www.ncss.gov.sg/careers/social-service-careers/roles-in-social-services/social-work/','government',30,'2026-08-11'),
('SG:counsellor','source','NCSS Counselling Careers','https://www.ncss.gov.sg/careers/social-service-careers/roles-in-social-services/counselling/','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o
join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved'
  and o.canonical_career_id in ('early-childhood-teacher','primary-school-teacher','secondary-school-teacher','special-education-teacher','social-worker','youth-worker','community-worker','counsellor')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
