insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('NZ:accountant','NZ','accountant','Accountant (General)','ANZSCO','1.3','221111','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:financial-analyst','NZ','financial-analyst','Accountant (General) — Financial Analyst specialisation','ANZSCO','1.3','221111','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:business-analyst','NZ','business-analyst','Management Consultant — Business Analyst specialisation','ANZSCO','1.3','224711','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:supply-chain-analyst','NZ','supply-chain-analyst','Supply Chain Analyst — supply-chain analysis scope','NZ career scope','2026-08-11',null,'NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:human-resources-specialist','NZ','human-resources-specialist','Human Resource Adviser — HR specialist scope','ANZSCO','1.3','223111','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:marketing-specialist','NZ','marketing-specialist','Marketing Specialist','ANZSCO','1.3','225113','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:auditor','NZ','auditor','External and Internal Auditor roll-up','ANZSCO','1.3','2212','NZD',false,null,null,'profile_ready','2026-08-11',now()),
('NZ:project-manager','NZ','project-manager','Project Manager — cross-industry scope','NZ career scope','2026-08-11',null,'NZD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
