-- United Kingdom Education cohort: canonical profile identities.
insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('UK:early-childhood-teacher','UK','early-childhood-teacher','Nursery education teaching professionals — early years teacher scope','SOC','SOC 2020','2315','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:primary-school-teacher','UK','primary-school-teacher','Primary education teaching professionals','SOC','SOC 2020','2314','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:secondary-school-teacher','UK','secondary-school-teacher','Secondary education teaching professionals','SOC','SOC 2020','2313','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:special-education-teacher','UK','special-education-teacher','Special and additional needs education teaching professionals','SOC','SOC 2020','2316','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:social-worker','UK','social-worker','Social workers','SOC','SOC 2020','2461','GBP',true,'UK social-work regulators','https://www.regulated-professions.service.gov.uk/professions/social-worker-3','profile_ready','2026-08-10',now()),
('UK:youth-worker','UK','youth-worker','Youth work professionals','SOC','SOC 2020','2464','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:community-worker','UK','community-worker','Youth and community workers — community worker scope','SOC','SOC 2020','3221','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:counsellor','UK','counsellor','Counsellors','SOC','SOC 2020','3224','GBP',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
