-- Ireland Programs Phase 2 staging foundation.
-- Scope is deliberately bounded to programmes that map to CampCareer target occupations.
-- These tables are server-only collection surfaces; Phase 2 does not canonicalize or publish programmes.

CREATE TABLE public.program_catalog_ie_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name text NOT NULL,
  source_program_key text NOT NULL,
  legacy_course_id bigint,
  provider_kind text NOT NULL CHECK (provider_kind IN ('higher_education','apprenticeship_authority','other')),
  institution_id uuid REFERENCES catalog.institutions(id),
  provider_name text NOT NULL,
  canonical_provider_name text,
  provider_slug text,
  provider_identity_status text NOT NULL CHECK (provider_identity_status IN ('resolved_current','resolved_alias','authority_without_catalog_institution','review_required')),
  title text NOT NULL,
  nfq_level smallint CHECK (nfq_level BETWEEN 1 AND 10),
  course_type text,
  delivery_model text NOT NULL CHECK (delivery_model IN ('higher_education','employment_based_apprenticeship','other')),
  study_mode text,
  qualifax_url text NOT NULL,
  provider_program_url text,
  recognition_basis text NOT NULL CHECK (recognition_basis IN ('nfq_legacy_mapping','qualifax_discovery','irq_verified','provider_awarding_authority','generation_apprenticeship')),
  recognition_source_url text,
  currentness_status text NOT NULL CHECK (currentness_status IN ('current_provider_verified','current_national_directory_verified','legacy_snapshot_needs_recheck')),
  source_as_of date NOT NULL,
  collection_status text NOT NULL DEFAULT 'bounded_phase2_collected',
  verification_tier text NOT NULL DEFAULT 'B' CHECK (verification_tier IN ('A','B','C')),
  collected_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source_name, source_program_key)
);

CREATE INDEX program_catalog_ie_staging_institution_idx
  ON public.program_catalog_ie_staging(institution_id)
  WHERE institution_id IS NOT NULL;

CREATE TABLE public.program_occupation_ie_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_catalog_id bigint NOT NULL REFERENCES public.program_catalog_ie_staging(id) ON DELETE CASCADE,
  canonical_career_id text NOT NULL,
  rule_version text NOT NULL DEFAULT 'ie-program-occupation-v1',
  match_basis text NOT NULL,
  match_pattern text,
  review_status text NOT NULL DEFAULT 'approved' CHECK (review_status IN ('candidate','approved','rejected')),
  relation_type text NOT NULL CHECK (relation_type IN ('direct','common_pathway','related')),
  access_model text NOT NULL CHECK (access_model IN ('higher_education','employment_based_apprenticeship','other')),
  source_checked_at date NOT NULL,
  reviewed_at timestamptz NOT NULL DEFAULT now(),
  reviewer_note text,
  UNIQUE (program_catalog_id, canonical_career_id, rule_version)
);

CREATE TABLE public.program_international_ie_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_catalog_id bigint NOT NULL UNIQUE REFERENCES public.program_catalog_ie_staging(id) ON DELETE CASCADE,
  trusted_ireland_provider_authorised boolean,
  trusted_ireland_source_url text,
  ilep_or_trusted_programme_status text NOT NULL DEFAULT 'not_programme_verified' CHECK (ilep_or_trusted_programme_status IN ('eligible','ineligible','not_programme_verified','not_applicable','unknown')),
  international_students_eligible boolean,
  full_time_daytime_verified boolean,
  international_admission_status text NOT NULL DEFAULT 'eligible_schedule_unknown' CHECK (international_admission_status IN ('open','closed','not_yet_open','restricted','eligible_schedule_unknown','unknown')),
  student_permission_context text,
  stamp1g_context text,
  eligible_programme_source_url text,
  immigration_source_url text,
  verification_status text NOT NULL DEFAULT 'provider_authorised_programme_pending' CHECK (verification_status IN ('provider_authorised_programme_pending','employment_based_not_student_route','verified','review_required','rejected')),
  source_checked_at date NOT NULL,
  verified_at timestamptz,
  reviewer_note text
);

COMMENT ON TABLE public.program_catalog_ie_staging IS 'Server-only Ireland Phase 2 bounded programme collection. Legacy Qualifax rows are discovery/provenance and are not publication-ready by default.';
COMMENT ON TABLE public.program_occupation_ie_staging IS 'Server-only reviewed Ireland programme-to-CampCareer-career staging relations.';
COMMENT ON TABLE public.program_international_ie_staging IS 'Server-only Ireland international-study context. TrustEd/ILEP, exact programme eligibility, study mode, admission timing and immigration context remain separate.';

ALTER TABLE public.program_catalog_ie_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_occupation_ie_staging ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_international_ie_staging ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.program_catalog_ie_staging FROM public, anon, authenticated;
REVOKE ALL ON public.program_occupation_ie_staging FROM public, anon, authenticated;
REVOKE ALL ON public.program_international_ie_staging FROM public, anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_catalog_ie_staging TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_occupation_ie_staging TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.program_international_ie_staging TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
