insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('UK:environmental-scientist','UK','environmental-scientist','Environment professionals — environmental scientist scope','SOC','SOC 2020','2152','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:agronomist','UK','agronomist','Biological scientists — agricultural scientist/agronomist scope','SOC','SOC 2020','2112','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:farm-manager','UK','farm-manager','Managers and proprietors in agriculture and horticulture','SOC','SOC 2020','1211','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:forestry-technician','UK','forestry-technician','Forestry and related workers — forest craftsperson/technical scope','SOC','SOC 2020','9112','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:food-technologist','UK','food-technologist','Engineering professionals n.e.c. — food technologist scope','SOC','SOC 2020','2129','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:sustainability-specialist','UK','sustainability-specialist','Environment professionals — sustainability officer/specialist scope','SOC','SOC 2020','2152','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:horticulturist','UK','horticulturist','Horticultural trades','SOC','SOC 2020','5112','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:animal-science-technician','UK','animal-science-technician','Laboratory technicians — animal technologist/biological laboratory scope','SOC','SOC 2020','3111','GBP',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
