-- Singapore Environment / Agriculture occupation cohort.
-- Classification basis: Singapore Standard Occupational Classification (SSOC) 2024.

insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('SG:environmental-scientist','SG','environmental-scientist','Environment research scientist','SSOC','2024','21332','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:agronomist','SG','agronomist','Agronomist — Farming/Forestry/Fishery adviser n.e.c.','SSOC','2024','21329','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:farm-manager','SG','farm-manager','Production manager in agriculture/fisheries','SSOC','2024','13100','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:forestry-technician','SG','forestry-technician','Forestry technician — silvicultural/life-science technical support umbrella','SSOC','2024',null,'SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:food-technologist','SG','food-technologist','Food/Drink technologist','SSOC','2024','21454','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:sustainability-specialist','SG','sustainability-specialist','Sustainability specialist — environmental protection professional n.e.c.','SSOC','2024','21339','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:horticulturist','SG','horticulturist','Horticulturist/Arborist','SSOC','2024','21321','SGD',false,null,null,'profile_ready','2026-08-11',now()),
('SG:animal-science-technician','SG','animal-science-technician','Farming technician (animal production)','SSOC','2024','31423','SGD',false,null,null,'profile_ready','2026-08-11',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();

insert into public.country_occupation_metric_snapshots (profile_key,as_of_date,shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at) values
('SG:environmental-scientist','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 2024 maps the research-focused canonical role directly to 21332 Environment research scientist.','entry_level_basis','Environmental science and earth-systems study provide relevant preparation; two approved programmes are related pathways.','qualification_note','No universal statutory occupational registration is identified for the broad Environment Research Scientist role.','market_scope','No exact shortage, vacancy, salary or growth series is scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:agronomist','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21329 Farming/Forestry/Fishery adviser n.e.c. explicitly lists Agronomist as an example job; 21323 Agriculturist remains a distinct farm-operations profession.','entry_level_basis','Agronomy commonly requires tertiary agricultural, plant or soil-science preparation, but no approved Singapore programme mapping is currently present.','qualification_note','No universal personal occupational licence is identified for Agronomists; farm and chemical activities may have separate operational controls.','market_scope','No labour-market component is inferred from classification or programme availability.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:farm-manager','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 13100 Production manager in agriculture/fisheries explicitly includes Farm manager and also fishery and plant-nursery managers.','entry_level_basis','Farm management is experience-heavy and commonly combines production knowledge with operational management; no approved programme mapping is currently present.','qualification_note','Commercial farms and animal-breeding operations can require business or premises licences, but those are not treated as a universal personal Farm Manager occupational licence.','market_scope','No exact market series is scored in SG v1 foundation.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:forestry-technician','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','Singapore has no exact five-digit Forestry Technician title. The technical field scope is represented by 31421 Horticultural technician, which explicitly includes Silvicultural technician, with 31419 Life science technician n.e.c. retained for broader biological field/lab support.','entry_level_basis','Technician work is compatible with diploma/technical pathways and field experience; no approved Singapore programme mapping is currently present.','qualification_note','No universal personal occupational registration is identified for this broad forestry technical-support role.','market_scope','Reference codes are not aggregated into a fabricated exact forestry-technician market series.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:food-technologist','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21454 Food/Drink technologist directly covers food and drink process research, product/process development, testing and food-safety research.','entry_level_basis','Two approved Food Science/Food Technology programmes are direct study pathways.','qualification_note','Food businesses and food-safety activities are regulated, but no universal personal Food Technologist occupational licence is identified.','market_scope','Regulatory importance is not converted into demand evidence.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:sustainability-specialist','2026-08-11',0,0,0,0,10,0,0,0,5,15,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21339 Environmental protection and related professional n.e.c. explicitly lists Sustainability specialist. SSOC 24214 Sustainability project development/management professional is retained as a related project-development scope, not substituted for the broader canonical role.','entry_level_basis','Six approved environmental, sustainability, built-environment and sustainability-management programmes are related pathways.','qualification_note','There is no universal personal occupational registration for Sustainability Specialists; project certification schemes and sector compliance remain separate.','market_scope','No shortage, salary, vacancy or growth points are inferred from sustainability policy activity.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:horticulturist','2026-08-11',0,0,0,0,12,0,0,0,5,17,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 21321 Horticulturist/Arborist directly covers professional horticultural crop research, production methods and advisory work; 31421 Horticultural technician remains separate.','entry_level_basis','Professional horticulture commonly combines tertiary plant/agricultural study and applied experience; no approved programme mapping is currently present.','qualification_note','Professional and employer certifications may be valued for arboriculture and landscape work, but no universal statutory personal licence is assigned to the broad Horticulturist role.','market_scope','No exact market component is scored in the foundation phase.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11'),
('SG:animal-science-technician','2026-08-11',0,0,0,0,15,0,0,0,5,20,'career-opportunity-sg-v1','provisional',jsonb_build_object('classification_scope','SSOC 31423 Farming technician (animal production) directly matches the non-clinical animal-production technical scope and explicitly separates Veterinary technician/assistant 32400.','entry_level_basis','Technical animal-production work can be entered through applied agricultural/animal-science training and supervised experience; no approved programme mapping is currently present.','qualification_note','AVS veterinary licensing applies to veterinarians treating animals and birds. The canonical technician role is non-clinical and is not treated as universally requiring a veterinary licence.','market_scope','No demand or salary signal is inferred from animal-sector licensing.','visa_scope','No occupation-specific visa credit is assigned.'),'2026-08-11')
on conflict (profile_key,as_of_date) do update set shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at) values
('SG:environmental-scientist','21332','Environment research scientist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:agronomist','21329','Agronomist — under Farming/Forestry/Fishery adviser n.e.c.',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:farm-manager','13100','Production manager in agriculture/fisheries — includes Farm manager',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:forestry-technician','31421','Horticultural technician — includes Silvicultural technician',null,null,false,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:forestry-technician','31419','Life science technician (excluding medical) n.e.c. — broader biological support reference',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:food-technologist','21454','Food/Drink technologist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:sustainability-specialist','21339','Environmental protection and related professional n.e.c. — includes Sustainability specialist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:sustainability-specialist','24214','Sustainability project development/management professional — related project scope',null,null,false,2,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:horticulturist','21321','Horticulturist/Arborist',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11'),
('SG:animal-science-technician','31423','Farming technician (animal production)',null,null,true,1,'https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','2026-08-11')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'job_search','MyCareersFuture Singapore','https://www.mycareersfuture.gov.sg/','government',10,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('environmental-scientist','agronomist','farm-manager','forestry-technician','food-technologist','sustainability-specialist','horticulturist','animal-science-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at)
select p.profile_key,'source','SingStat SSOC 2024','https://www.singstat.gov.sg/standards/standards-and-classifications/ssoc','government',20,'2026-08-11' from public.country_occupation_profiles p where p.country_code='SG' and p.canonical_career_id in ('environmental-scientist','agronomist','farm-manager','forestry-technician','food-technologist','sustainability-specialist','horticulturist','animal-science-technician')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (profile_key,link_type,label,url,provider_type,sort_order,source_checked_at) values
('SG:animal-science-technician','source','AVS — Veterinary licensing','https://avs.nparks.gov.sg/businesses/veterinarians/veterinary-licensing/','government',30,'2026-08-11')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_program_links (profile_key,program_ref,relation_type,source_checked_at)
select 'SG:'||o.canonical_career_id,'sg-program:'||c.id::text,case when o.relation_type='direct' then 'direct' else 'related' end,coalesce(o.source_checked_at,'2026-08-11'::date)
from public.program_occupation_sg_staging o join public.program_catalog_sg_staging c on c.id=o.program_catalog_id
where o.review_status='approved' and o.canonical_career_id in ('environmental-scientist','agronomist','farm-manager','forestry-technician','food-technologist','sustainability-specialist','horticulturist','animal-science-technician')
on conflict (profile_key,program_ref) do update set relation_type=excluded.relation_type,source_checked_at=excluded.source_checked_at;
