insert into public.country_occupation_profiles (profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,official_unit_group_code,currency,registration_required,registration_authority,registration_url,publication_status,source_checked_at,updated_at) values
('UK:truck-driver','UK','truck-driver','Heavy and large goods vehicle drivers','SOC','SOC 2020','8211','GBP',true,'DVLA / DVSA','https://www.gov.uk/become-lorry-bus-driver','profile_ready','2026-08-10',now()),
('UK:logistics-coordinator','UK','logistics-coordinator','Transport and distribution clerks and assistants — transport coordinator scope','SOC','SOC 2020','4134','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:aircraft-maintenance-technician','UK','aircraft-maintenance-technician','Aircraft maintenance and related trades — aircraft maintenance technician scope','SOC','SOC 2020','5234','GBP',true,'UK Civil Aviation Authority','https://www.caa.co.uk/commercial-industry/aircraft/airworthiness/engineer-licences/uk-part-66/','profile_ready','2026-08-10',now()),
('UK:commercial-pilot','UK','commercial-pilot','Aircraft pilots and air traffic controllers — commercial pilot scope','SOC','SOC 2020','3511','GBP',true,'UK Civil Aviation Authority','https://www.caa.co.uk/commercial-industry/pilot-licences/aeroplanes/commercial-pilot-licence-for-aeroplanes-guidance/','profile_ready','2026-08-10',now()),
('UK:marine-engineer','UK','marine-engineer','Ship and hovercraft officers — marine engineer scope','SOC','SOC 2020','3512','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:deck-officer','UK','deck-officer','Ship and hovercraft officers — deck officer scope','SOC','SOC 2020','3512','GBP',true,'Maritime and Coastguard Agency','https://www.gov.uk/guidance/apply-for-a-uk-seafarer-coc-deck-and-engineer-officers','profile_ready','2026-08-10',now()),
('UK:warehouse-manager','UK','warehouse-manager','Managers in storage and warehousing','SOC','SOC 2020','1242','GBP',false,null,null,'profile_ready','2026-08-10',now()),
('UK:automotive-service-technician','UK','automotive-service-technician','Vehicle technicians, mechanics and electricians — car/light vehicle technician scope','SOC','SOC 2020','5231','GBP',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set official_title=excluded.official_title,official_code_system=excluded.official_code_system,official_code_version=excluded.official_code_version,official_unit_group_code=excluded.official_unit_group_code,currency=excluded.currency,registration_required=excluded.registration_required,registration_authority=excluded.registration_authority,registration_url=excluded.registration_url,publication_status=excluded.publication_status,source_checked_at=excluded.source_checked_at,updated_at=now();
