insert into public.country_occupation_profiles (
  profile_key,country_code,canonical_career_id,official_title,official_code_system,official_code_version,
  official_unit_group_code,currency,registration_required,registration_authority,registration_url,
  publication_status,source_checked_at,updated_at
) values
  ('IE:software-developer','IE','software-developer','Programmers and software development professionals','SOC','SOC 2010','2136','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:data-analyst','IE','data-analyst','Data analyst — cross-SOC analytics scope; verified big-data specialist employment retained separately','SOC','SOC 2010',null,'EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:data-engineer','IE','data-engineer','IT business analysts, architects and systems designers — data engineering / architecture scope','SOC','SOC 2010','2135','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:cybersecurity-analyst','IE','cybersecurity-analyst','Information technology and telecommunications professionals n.e.c. — cyber-security analyst scope','SOC','SOC 2010','2139','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:network-administrator','IE','network-administrator','IT operations technicians — network administration scope','SOC','SOC 2010','3131','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:cloud-engineer','IE','cloud-engineer','Information technology and telecommunications professionals n.e.c. — cloud / DevOps infrastructure engineering scope','SOC','SOC 2010','2139','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:database-administrator','IE','database-administrator','IT operations technicians — database administration scope','SOC','SOC 2010','3131','EUR',false,null,null,'profile_ready','2026-08-10',now()),
  ('IE:ict-support-technician','IE','ict-support-technician','IT user support technicians','SOC','SOC 2010','3132','EUR',false,null,null,'profile_ready','2026-08-10',now())
on conflict (profile_key) do update set
  official_title=excluded.official_title,
  official_code_system=excluded.official_code_system,
  official_code_version=excluded.official_code_version,
  official_unit_group_code=excluded.official_unit_group_code,
  currency=excluded.currency,
  registration_required=excluded.registration_required,
  registration_authority=excluded.registration_authority,
  registration_url=excluded.registration_url,
  publication_status=excluded.publication_status,
  source_checked_at=excluded.source_checked_at,
  updated_at=now();

insert into public.country_occupation_metric_snapshots (
  profile_key,as_of_date,employment_total,median_hourly_earnings,annualised_median_salary,
  shortage_component,vacancy_intensity_component,employer_diversity_component,vacancy_trend_component,
  entry_level_component,salary_component,growth_component,visa_component,entry_burden_component,
  opportunity_score,score_methodology_version,score_status,score_evidence,source_checked_at
) values
  ('IE:software-developer','2026-08-10',null,null,null,20,0,0,0,8,0,0,10,5,43,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2136 Programmers and software development professionals.','shortage_note','SOLAS National Skills Bulletin 2025 directly identifies software developers/engineers as a shortage; 20/20.','visa_basis','SOC 2136 is explicitly on the current Critical Skills Occupations List; 10/10.','growth_boundary','SOLAS reports 9.8% annual average growth for the broad IT occupation group over 2019-2024, but that group rate is not copied into this exact occupation; growth remains 0.','salary_method','No current exact comparable Ireland occupation-level median salary series has been normalised for this cohort; salary remains 0.','entry_basis','Degree and work-based ICT routes exist, but no single entry credential is mandatory across the occupation; 8/15.','entry_burden_basis','No universal statutory professional registration is required; 5/5.'),'2026-08-10'),
  ('IE:data-analyst','2026-08-10',null,null,null,0,0,0,0,8,0,0,8,5,21,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','Canonical Data Analyst spans more than one SOC 2010 context. The current CSEP list explicitly recognises SOC 2423 management consultants/business analysts only when specialising in big-data analytics; the generic title alone is not treated as an exact CSEP match.','shortage_note','SOLAS identifies IT analysts/engineers as a shortage, but generic Data Analyst is broader than that exact group; no direct shortage credit.','visa_basis','Targeted big-data analytics specialist employment under SOC 2423 can qualify for CSEP, so conditional 8/10 rather than universal 10/10.','growth_boundary','Broad IT 9.8% annual average growth is not assigned to this cross-SOC canonical occupation.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree, conversion and analytics pathways exist but no single mandatory entry route; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:data-engineer','2026-08-10',null,null,null,15,0,0,0,8,0,0,10,5,38,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2135 IT business analysts, architects and systems designers, constrained to data engineering/data architecture work.','shortage_note','SOLAS directly identifies IT analysts/engineers as a shortage. Data Engineer receives strong but not maximum 15/20 because the published shortage label is broader than this exact title.','visa_basis','SOC 2135 is explicitly on the current Critical Skills Occupations List; 10/10.','growth_boundary','Broad IT 9.8% annual average growth is disclosed but not reused as an exact occupation rate.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Typically degree-level or equivalent technical experience; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:cybersecurity-analyst','2026-08-10',null,null,null,15,0,0,0,8,0,0,10,5,38,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2139 Information technology and telecommunications professionals n.e.c., cyber-security analyst scope. ONS SOC 2020 later split cyber-security professionals from this SOC 2010 group.','shortage_note','SOLAS IT analysts/engineers shortage supports strong but non-maximal 15/20 for professional cyber analysis; no separate exact cyber shortage count is asserted.','visa_basis','SOC 2139 is explicitly on the current Critical Skills Occupations List; 10/10.','growth_boundary','Broad IT 9.8% annual average growth is not copied into the exact cyber occupation.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Degree/certification routes and a national Cybersecurity Associate apprenticeship provide structured entry; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:network-administrator','2026-08-10',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3131 IT operations technicians, constrained to network administration. Professional network-engineering roles can fall elsewhere and are not rolled into this technician profile.','shortage_note','The SOLAS shortage summary names software developers/engineers and IT analysts/engineers, not network administrators; 0/20.','visa_basis','SOC 3131 is not on the current Critical Skills list and was not found on the current Ineligible list; ordinary GEP accessibility may apply subject to employer and permit conditions; 6/10.','growth_boundary','Broad IT growth is not treated as an exact network-administrator growth series.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','The national Computer Networking Associate apprenticeship provides a structured work-based route; 12/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:cloud-engineer','2026-08-10',null,null,null,15,0,0,0,8,0,0,10,5,38,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 2139 Information technology and telecommunications professionals n.e.c., constrained to professional cloud/DevOps infrastructure engineering.','shortage_note','SOLAS identifies IT analysts/engineers as a shortage; cloud engineering receives 15/20 because the shortage label is broader than the exact title.','visa_basis','SOC 2139 is explicitly on the current Critical Skills Occupations List; 10/10.','growth_boundary','Broad IT 9.8% annual average growth is not copied into the exact cloud occupation.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Usually degree-level or equivalent systems/cloud experience; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:database-administrator','2026-08-10',null,null,null,0,0,0,0,8,0,0,6,5,19,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3131 IT operations technicians, database administration scope. ONS SOC 2020 created a separate Database administrators group from SOC 2010 IT operations technicians.','shortage_note','No exact database-administrator shortage is named in the SOLAS 2025 ICT summary; 0/20.','visa_basis','SOC 3131 is not on the current Critical Skills list and was not found on the current Ineligible list; ordinary GEP accessibility may apply subject to conditions; 6/10.','growth_boundary','Broad IT growth is not assigned as an exact DBA rate.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Technical/degree routes exist; no single national mandatory pathway; 8/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10'),
  ('IE:ict-support-technician','2026-08-10',null,null,null,0,0,0,0,12,0,0,6,5,23,'career-opportunity-ie-v1','provisional',jsonb_build_object('classification_scope','SOC 2010 3132 IT user support technicians.','shortage_note','No exact IT user-support shortage is named in the SOLAS 2025 ICT summary; 0/20.','visa_basis','SOC 3132 is not on the current Critical Skills list and was not found on the current Ineligible list; ordinary GEP accessibility may apply subject to conditions; 6/10.','growth_boundary','Broad IT growth is not assigned as an exact support-technician growth rate.','salary_method','No exact comparable Irish median salary series normalised; 0.','entry_basis','Support/network apprenticeships and technical education provide accessible work-based routes; 12/15.','entry_burden_basis','No universal statutory registration; 5/5.'),'2026-08-10')
on conflict (profile_key,as_of_date) do update set
  employment_total=excluded.employment_total,median_hourly_earnings=excluded.median_hourly_earnings,annualised_median_salary=excluded.annualised_median_salary,
  shortage_component=excluded.shortage_component,vacancy_intensity_component=excluded.vacancy_intensity_component,employer_diversity_component=excluded.employer_diversity_component,vacancy_trend_component=excluded.vacancy_trend_component,
  entry_level_component=excluded.entry_level_component,salary_component=excluded.salary_component,growth_component=excluded.growth_component,visa_component=excluded.visa_component,entry_burden_component=excluded.entry_burden_component,
  opportunity_score=excluded.opportunity_score,score_methodology_version=excluded.score_methodology_version,score_status=excluded.score_status,score_evidence=excluded.score_evidence,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_specialisations (
  profile_key,official_code,official_title,shortage_rating,visa_eligible,included_in_rollup,sort_order,source_url,source_checked_at
) values
  ('IE:software-developer','2136','Programmers and software development professionals',20,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:data-analyst','2423','Management consultants and business analysts — big-data analytics specialist employment',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:data-engineer','2135','IT business analysts, architects and systems designers — data engineering / architecture scope',15,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:cybersecurity-analyst','2139','IT and telecommunications professionals n.e.c. — cyber-security analyst scope',15,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:network-administrator','3131','IT operations technicians — network administration scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-10'),
  ('IE:cloud-engineer','2139','IT and telecommunications professionals n.e.c. — cloud / DevOps infrastructure engineering scope',15,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','2026-08-10'),
  ('IE:database-administrator','3131','IT operations technicians — database administration scope',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permit-eligibility/classification-of-employments/','2026-08-10'),
  ('IE:ict-support-technician','3132','IT user support technicians',null,true,true,1,'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','2026-08-10')
on conflict (profile_key,official_code) do update set official_title=excluded.official_title,shortage_rating=excluded.shortage_rating,visa_eligible=excluded.visa_eligible,included_in_rollup=excluded.included_in_rollup,sort_order=excluded.sort_order,source_url=excluded.source_url,source_checked_at=excluded.source_checked_at;

insert into public.country_occupation_links (
  profile_key,link_type,label,url,provider_type,region_code,sort_order,source_checked_at
) values
  ('IE:software-developer','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:software-developer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:data-analyst','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:data-analyst','source','DETE — Critical Skills big-data analytics specialist scope','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:data-engineer','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:data-engineer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:cybersecurity-analyst','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:cybersecurity-analyst','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:cybersecurity-analyst','entry_program','Generation Apprenticeship — Cybersecurity Associate L6','https://apprenticeship.ie/career-seekers/get-started/learn-more/ict/Cybersecurity-Associate-L6','government',null,3,'2026-08-10'),
  ('IE:network-administrator','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:network-administrator','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-10'),
  ('IE:network-administrator','entry_program','Generation Apprenticeship — Computer Networking Associate L6','https://apprenticeship.ie/career-seekers/get-started/next-steps/ict/Computer-Networking-Associate-L6','government',null,3,'2026-08-10'),
  ('IE:cloud-engineer','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:cloud-engineer','source','DETE — Critical Skills Occupations List','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/highly-skilled-eligible-occupations-list/','government',null,2,'2026-08-10'),
  ('IE:database-administrator','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:database-administrator','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-10'),
  ('IE:ict-support-technician','source','SOLAS — ICT labour-market evidence','https://www.solas.ie/research-lp/skills-labour-market-research-slmru/career-guidance/ict/','government',null,1,'2026-08-10'),
  ('IE:ict-support-technician','source','DETE — Employment-permit occupation classification','https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/employment-permit-eligibility/classification-of-employments/','government',null,2,'2026-08-10')
on conflict (profile_key,link_type,url) do update set label=excluded.label,provider_type=excluded.provider_type,region_code=excluded.region_code,sort_order=excluded.sort_order,source_checked_at=excluded.source_checked_at;
