-- Applied through the Supabase connector on 2026-08-08.
-- Canonical migration logic is retained in:
--   20260808112000_uk_campus_location_quality.sql
-- This no-op marker keeps the connector-generated remote migration version aligned locally.
