import type { VisaEntry } from "./visa-catalog"

export const BATCH_2_VISA_ENTRIES: readonly VisaEntry[] = [
  {
    country: "Norway",
    countryCode: "NO",
    name: "University and vocational study permit",
    kind: "Study",
    note: "Full-time higher education or approved vocational study with part-time work rights.",
    authority: "Norwegian Directorate of Immigration",
    url: "https://www.udi.no/en/want-to-apply/studies/studietillatelse/",
  },
  {
    country: "Norway",
    countryCode: "NO",
    name: "Post-study job seeker permit",
    kind: "Temporary",
    note: "Up to one year for eligible graduates and researchers to seek skilled employment in Norway.",
    authority: "Norwegian Directorate of Immigration",
    url: "https://www.udi.no/en/want-to-apply/work-immigration/job-seekers/",
  },
  {
    country: "Norway",
    countryCode: "NO",
    name: "Skilled worker with employer",
    kind: "Skilled",
    note: "Employer-backed residence for qualifying higher-education, vocational or specially qualified workers.",
    authority: "Norwegian Directorate of Immigration",
    url: "https://www.udi.no/en/want-to-apply/work-immigration/skilled-workers/",
  },
  {
    country: "Norway",
    countryCode: "NO",
    name: "Seasonal worker",
    kind: "Work",
    note: "Full-time seasonal employment or holiday cover for a limited period.",
    authority: "Norwegian Directorate of Immigration",
    url: "https://www.udi.no/en/want-to-apply/work-immigration/seasonal-workers/",
  },
  {
    country: "Norway",
    countryCode: "NO",
    name: "Trainee permit",
    kind: "Work",
    note: "Curriculum-linked practical training for eligible students enrolled at a foreign higher-education institution.",
    authority: "Norwegian Directorate of Immigration",
    url: "https://www.udi.no/en/want-to-apply/work-immigration/vocational-training-and-research/",
  },
  {
    country: "Norway",
    countryCode: "NO",
    name: "Working holiday for young adults",
    kind: "Working holiday",
    note: "Holiday-first residence with work rights for eligible young citizens of partner countries.",
    authority: "Norwegian Directorate of Immigration",
    url: "https://www.udi.no/en/want-to-apply/work-immigration/exchange-programmes-culture-and-organisational-work/",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    name: "Higher education study permit",
    kind: "Study",
    note: "Full-time first- or second-cycle higher education with limited semester-time work rights.",
    authority: "Swedish Migration Agency",
    url: "https://www.migrationsverket.se/en/you-want-to-apply/study/higher-education.html",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    name: "Post-study job-search permit",
    kind: "Temporary",
    note: "Residence after completed Swedish higher education to seek work or explore starting a business.",
    authority: "Swedish Migration Agency",
    url: "https://www.migrationsverket.se/en/you-want-to-extend/study/look-for-work-after-completing-your-studies-in-sweden.html",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    name: "Employee work permit",
    kind: "Work",
    note: "Employer-led work permit for employment meeting salary, insurance and Swedish labour-condition rules.",
    authority: "Swedish Migration Agency",
    url: "https://www.migrationsverket.se/en/you-want-to-apply/work/employee-or-self-employed/employees.html",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    name: "Highly qualified job-seeker permit",
    kind: "Temporary",
    note: "Up to nine months for eligible second-cycle graduates outside Sweden to seek work or explore a business.",
    authority: "Swedish Migration Agency",
    url: "https://www.migrationsverket.se/en/you-want-to-apply/work/look-for-work/look-for-work-or-start-a-business.html",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    name: "Higher-education traineeship permit",
    kind: "Work",
    note: "Paid internship related to ongoing higher education or a recently completed higher-education qualification.",
    authority: "Swedish Migration Agency",
    url: "https://www.migrationsverket.se/en/you-want-to-apply/work/temporary-work-in-sweden/traineeships-internships/traineeships-internships-within-the-context-of-higher-education.html",
  },
  {
    country: "Sweden",
    countryCode: "SE",
    name: "Working Holiday",
    kind: "Working holiday",
    note: "Up to one year to experience Swedish life and culture with incidental work for eligible young citizens.",
    authority: "Swedish Migration Agency",
    url: "https://www.migrationsverket.se/en/you-want-to-apply/work/temporary-work-in-sweden/working-holiday-visa-for-young-people.html",
  },
  {
    country: "Denmark",
    countryCode: "DK",
    name: "Higher education study permit",
    kind: "Study",
    note: "Full-time higher education with limited monthly work rights and full-time summer work.",
    authority: "Danish Agency for International Recruitment and Integration",
    url: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Study/Higher-education",
  },
  {
    country: "Denmark",
    countryCode: "DK",
    name: "Three-year post-study job-seeking permit",
    kind: "Temporary",
    note: "Up to three years for eligible graduates of state-approved Danish professional bachelor, bachelor, master or PhD programmes.",
    authority: "Danish Agency for International Recruitment and Integration",
    url: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Study/Study---job-seeking/Study---3-years-job-seeking",
  },
  {
    country: "Denmark",
    countryCode: "DK",
    name: "Positive List for People with Higher Education",
    kind: "Skilled",
    note: "Employer-backed permit for a current shortage occupation requiring the listed higher-education level.",
    authority: "Danish Agency for International Recruitment and Integration",
    url: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work/Positive-List-Higher-Education",
  },
  {
    country: "Denmark",
    countryCode: "DK",
    name: "Pay Limit Scheme",
    kind: "Work",
    note: "Employer-backed work permit for a Danish job meeting the annual high-salary threshold.",
    authority: "Danish Agency for International Recruitment and Integration",
    url: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work/Pay-limit-scheme",
  },
  {
    country: "Denmark",
    countryCode: "DK",
    name: "Internship permit",
    kind: "Work",
    note: "Educationally justified internship in an eligible professional field with a qualifying Danish host.",
    authority: "Danish Agency for International Recruitment and Integration",
    url: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Interns",
  },
  {
    country: "Denmark",
    countryCode: "DK",
    name: "Working Holiday",
    kind: "Working holiday",
    note: "Holiday-first youth mobility route with limited salaried work for eligible partner-country citizens.",
    authority: "Danish Agency for International Recruitment and Integration",
    url: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Working-Holiday/Working-Holiday",
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Residence permit for studies",
    kind: "Study",
    note: "Degree, vocational-qualification or exchange study with average weekly work rights.",
    authority: "Finnish Immigration Service",
    url: "https://migri.fi/en/residence-permit-application-for-studies",
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Post-study job-search and business permit",
    kind: "Temporary",
    note: "Up to two years for eligible graduates and researchers to seek work or start a business.",
    authority: "Finnish Immigration Service",
    url: "https://migri.fi/en/application-for-students-and-researchers-residence-permit-to-look-for-work",
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Residence permit for an employed person",
    kind: "Work",
    note: "Employer-backed permit for regular employment, potentially subject to labour-market testing.",
    authority: "Finnish Immigration Service",
    url: "https://migri.fi/en/residence-permit-for-an-employed-person",
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Specialist residence permit",
    kind: "Skilled",
    note: "Fast-track eligible permit for highly skilled expert duties meeting the specialist salary threshold.",
    authority: "Finnish Immigration Service",
    url: "https://migri.fi/en/specialist",
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Internship residence permit",
    kind: "Work",
    note: "Paid education-related internship for eligible students, recent graduates or exchange participants.",
    authority: "Finnish Immigration Service",
    url: "https://migri.fi/en/internship",
  },
  {
    country: "Finland",
    countryCode: "FI",
    name: "Working Holiday",
    kind: "Working holiday",
    note: "Holiday-first residence with work rights for eligible Australian, New Zealand, Japanese and Canadian citizens.",
    authority: "Finnish Immigration Service",
    url: "https://migri.fi/en/working-holiday/en",
  },
]

const REPLACED_COUNTRY_CODES = new Set(
  BATCH_2_VISA_ENTRIES.map((visa) => visa.countryCode),
)

export function applyBatch2VisaCatalog(base: readonly VisaEntry[]): readonly VisaEntry[] {
  return [
    ...base.filter((visa) => !REPLACED_COUNTRY_CODES.has(visa.countryCode)),
    ...BATCH_2_VISA_ENTRIES,
  ]
}
