const INDEXABLE_CH_PROGRAM_SLUGS = [
  "ecole-polytechnique-federale-de-lausanne-epfl-applied-mathematics-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-applied-physics-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-architecture-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-chemical-engineering-and-biotechnology-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-civil-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-computational-science-and-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-computer-science-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-cyber-security-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-data-science-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-digital-humanities-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-electrical-and-electronic-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-energy-science-and-technology-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-environmental-sciences-and-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-financial-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-life-sciences-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-management-technology-and-entrepreneurship-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-materials-science-and-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-mathematics-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-mechanical-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-microengineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-molecular-and-biological-chemistry-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-neuro-x-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-nuclear-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-physics-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-quantum-science-and-engineering-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-robotics-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-statistics-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-sustainable-management-and-technology-master",
  "ecole-polytechnique-federale-de-lausanne-epfl-urban-systems-master",
  "eidgenossische-technische-hochschule-zurich-eth-comparative-and-international-studies-master",
  "eidgenossische-technische-hochschule-zurich-eth-history-and-philosophy-of-knowledge-master",
  "universita-della-svizzera-italiana-usi-data-science-master",
  "universita-della-svizzera-italiana-usi-history-and-theory-of-art-and-architecture-master",
  "universita-della-svizzera-italiana-usi-informatics-master",
  "universita-della-svizzera-italiana-usi-international-tourism-master",
  "universita-della-svizzera-italiana-usi-media-management-master",
  "universita-della-svizzera-italiana-usi-public-management-and-policy-master",
  "universitat-zurich-uzh-quantitative-finance-master",
] as const

const INDEXABLE_CH_PROGRAM_SET = new Set<string>(INDEXABLE_CH_PROGRAM_SLUGS)
export const INDEXABLE_CH_PROGRAM_PATHS = INDEXABLE_CH_PROGRAM_SLUGS.map((slug) => `/programs/ch/${slug}`)
export function isIndexableChProgramSlug(slug: string) { return INDEXABLE_CH_PROGRAM_SET.has(slug) }
export function chProgramDetailPath(slug: string) { return `/programs/ch/${slug}` }
