export function deProgramDetailPath(slug:string){return `/programs/de/${slug}`}

export const INDEXABLE_DE_PROGRAM_SLUGS = [
  "freie-universitaet-berlin-biochemistry-master",
  "freie-universitaet-berlin-bioinformatics-master",
  "freie-universitaet-berlin-cognitive-neuroscience-master",
  "freie-universitaet-berlin-computational-sciences-master",
  "freie-universitaet-berlin-data-science-master",
  "freie-universitaet-berlin-pharmaceutical-research-master",
  "heidelberg-university-american-studies-master",
  "heidelberg-university-english-studies-master",
  "heidelberg-university-international-health-master",
  "heidelberg-university-popular-cultures-master",
  "heidelberg-university-transcultural-studies-master",
  "heidelberg-university-translational-medical-research-master",
  "humboldt-universitaet-zu-berlin-agricultural-economics-master",
  "humboldt-universitaet-zu-berlin-biophysics-master",
  "humboldt-universitaet-zu-berlin-economics-and-governance-of-agriculture-and-food-master",
  "humboldt-universitaet-zu-berlin-fish-biology-fisheries-and-aquaculture-master",
  "humboldt-universitaet-zu-berlin-global-change-geography-master",
  "humboldt-universitaet-zu-berlin-horticultural-and-plant-sciences-master",
  "karlsruhe-institute-of-technology-biomedical-engineering-master",
  "karlsruhe-institute-of-technology-computational-and-data-science-master",
  "karlsruhe-institute-of-technology-mechatronics-and-information-technology-master",
  "ludwig-maximilians-universitaet-munich-astrophysics-master",
  "ludwig-maximilians-universitaet-munich-biochemistry-master",
  "ludwig-maximilians-universitaet-munich-economics-master",
  "ludwig-maximilians-universitaet-munich-epidemiology-master",
  "ludwig-maximilians-universitaet-munich-management-and-digital-technologies-master",
  "ludwig-maximilians-universitaet-munich-statistics-and-data-science-master",
  "rwth-aachen-university-battery-systems-engineering-master",
  "rwth-aachen-university-computer-aided-conception-and-production-in-mechanical-engineering-master",
  "rwth-aachen-university-management-and-engineering-in-computer-aided-mechanical-engineering-master",
  "rwth-aachen-university-management-and-engineering-in-production-systems-master",
  "rwth-aachen-university-resilient-civil-engineering-master",
  "rwth-aachen-university-robotic-systems-engineering-master",
  "technical-university-of-munich-aerospace-master",
  "technical-university-of-munich-automotive-engineering-master",
  "technical-university-of-munich-cartography-master",
  "technical-university-of-munich-computational-mechanics-master",
  "technical-university-of-munich-environmental-engineering-master",
  "technische-universitaet-berlin-automotive-systems-master",
  "technische-universitaet-berlin-computer-engineering-master",
  "technische-universitaet-berlin-computer-science-informatik-master",
  "technische-universitaet-berlin-digital-media-technology-master",
  "technische-universitaet-berlin-electrical-engineering-master",
  "technische-universitaet-berlin-information-systems-management-master",
  "technische-universitaet-dresden-computer-science-master",
  "technische-universitaet-dresden-geoinformatics-master",
  "technische-universitaet-dresden-kreislaufwirtschaft-und-ressourceneffizienz-master",
  "technische-universitaet-dresden-mobility-systems-master",
  "technische-universitaet-dresden-sustainable-electronics-and-photonics-master",
  "technische-universitaet-dresden-transportation-economics-and-data-science-master",
  "university-of-bonn-agricultural-and-food-economics-master",
  "university-of-bonn-agricultural-sciences-and-resource-management-in-the-tropics-and-subtropics-master",
  "university-of-bonn-animal-sciences-master",
  "university-of-bonn-anthropology-of-the-americas-master",
  "university-of-bonn-applied-linguistics-master",
  "university-of-bonn-artificial-intelligence-master",
  "university-of-tuebingen-advanced-quantum-physics-master",
  "university-of-tuebingen-american-studies-master",
  "university-of-tuebingen-applied-environmental-geoscience-aeg-master",
  "university-of-tuebingen-cellular-and-molecular-neuroscience-master",
  "university-of-tuebingen-computational-linguistics-master",
  "university-of-tuebingen-computational-neuroscience-master",
] as const

const INDEXABLE_DE_PROGRAM_SLUG_SET=new Set<string>(INDEXABLE_DE_PROGRAM_SLUGS)
export function isIndexableDeProgramSlug(slug:string){return INDEXABLE_DE_PROGRAM_SLUG_SET.has(slug)}
export const INDEXABLE_DE_PROGRAM_PATHS=INDEXABLE_DE_PROGRAM_SLUGS.map(deProgramDetailPath)
