const INDEXABLE_NO_PROGRAM_SLUGS = `
nord-university-biology-bachelor-of-science
nord-university-biosciences-master-degree
nord-university-cg-art-and-animation-bachelor
nord-university-film-and-tv-production-bachelor
nord-university-games-and-entertainment-technology-bachelor
nord-university-joint-bachelor-degree-in-animal-science
nord-university-master-in-business
nord-university-master-in-sustainable-leadership-and-arctic-perspectives
nord-university-sports-and-physical-education-one-year
nord-university-sustainable-production-and-utilisation-of-marine-bioresources-nordic-master
norwegian-university-of-life-sciences-animal-science
norwegian-university-of-life-sciences-applied-economics-and-sustainability
norwegian-university-of-life-sciences-european-master-in-animal-biodiversity-and-genomics
norwegian-university-of-life-sciences-international-environment-and-development-studies
norwegian-university-of-life-sciences-international-environmental-studies
norwegian-university-of-life-sciences-international-relations
norwegian-university-of-life-sciences-landscape-architecture-for-global-sustainability
norwegian-university-of-life-sciences-nordic-master-in-aquatic-food-production-safety-and-quality
norwegian-university-of-life-sciences-nuclear-and-environmental-sciences
norwegian-university-of-life-sciences-plant-sciences
norwegian-university-of-life-sciences-sustainable-food-systems
norwegian-university-of-science-and-technology-biology-master-s-programme
norwegian-university-of-science-and-technology-biotechnology-master-s-programme
norwegian-university-of-science-and-technology-chemistry-master-s-programme
norwegian-university-of-science-and-technology-childhood-studies-master-s-programme
norwegian-university-of-science-and-technology-creative-music-technology-master-s-programme
norwegian-university-of-science-and-technology-cybersecurity-and-assurance-master-s-programme
norwegian-university-of-science-and-technology-digital-infrastructure-and-cyber-security-master-s-programme
norwegian-university-of-science-and-technology-electric-power-engineering-master-s-programme
norwegian-university-of-science-and-technology-electronic-systems-design-master-s-programme
norwegian-university-of-science-and-technology-english-linguistics-and-language-acquisition-master-s-programme
norwegian-university-of-science-and-technology-environmental-contamination-and-toxicology-one-health-master-s-programme
norwegian-university-of-science-and-technology-fine-art-master-s-programme
norwegian-university-of-science-and-technology-hydropower-development-master-s-programme
norwegian-university-of-science-and-technology-industrial-ecology-master-s-programme
norwegian-university-of-science-and-technology-manufacturing-4-0-by-intelligent-and-sustainable-technologies-master-s-programme
norwegian-university-of-science-and-technology-marine-technology-master-s-programme
norwegian-university-of-science-and-technology-maritime-engineering-nordic-master-s-programme
norwegian-university-of-science-and-technology-materials-science-and-chemical-engineering-master-s-programme
norwegian-university-of-science-and-technology-materials-science-and-engineering-master-s-programme
norwegian-university-of-science-and-technology-mathematical-sciences-master-s-programme
norwegian-university-of-science-and-technology-mechatronics-and-automation-master-s-programme
norwegian-university-of-science-and-technology-music-performance-master-s-programme
norwegian-university-of-science-and-technology-ocean-resources-master-s-programme
norwegian-university-of-science-and-technology-physics-master-s-programme
norwegian-university-of-science-and-technology-project-management-master-s-programme
norwegian-university-of-science-and-technology-reliability-availability-maintainability-and-safety-rams-master-s-programme
norwegian-university-of-science-and-technology-subsea-technology-master-s-programme
oslomet-oslo-metropolitan-university-applied-computer-and-information-technology-msc
oslomet-oslo-metropolitan-university-civil-engineering
oslomet-oslo-metropolitan-university-international-development-education-and-sustainabilities
oslomet-oslo-metropolitan-university-mechanical-engineering
oslomet-oslo-metropolitan-university-nordic-social-policy-and-global-sustainable-development
oslomet-oslo-metropolitan-university-product-design-design-in-complexity
oslomet-oslo-metropolitan-university-public-health-nutrition
oslomet-oslo-metropolitan-university-transport-and-urban-analytics
uit-the-arctic-university-of-norway-aerospace-engineering-master
uit-the-arctic-university-of-norway-applied-computer-science-master
uit-the-arctic-university-of-norway-computational-chemistry-master
uit-the-arctic-university-of-norway-computer-science-master
uit-the-arctic-university-of-norway-contemporary-risk-and-crisis-management-master
uit-the-arctic-university-of-norway-electrical-engineering-master
uit-the-arctic-university-of-norway-engineering-design-master
uit-the-arctic-university-of-norway-english-acquisition-and-multilingualism-master
uit-the-arctic-university-of-norway-english-literature-master
uit-the-arctic-university-of-norway-industrial-engineering-master
uit-the-arctic-university-of-norway-public-health-master
university-of-agder-academic-esports-bachelor-s-programme
university-of-agder-artificial-intelligence-and-the-internet-of-things-master-s-programme
university-of-agder-civil-and-structural-engineering-master-s-programme
university-of-agder-cybersecurity-management-master-s-programme
university-of-agder-master-in-management-and-business-development
university-of-agder-master-s-programme-in-business-administration
university-of-agder-master-s-programme-in-coastal-ecology
university-of-agder-master-s-programme-in-cybersecurity-engineering
university-of-agder-master-s-programme-in-sustainability-management
university-of-bergen-human-geography-and-sustainable-development-master-s
university-of-bergen-master-s-programme-in-biomedical-sciences
university-of-bergen-master-s-programme-in-curatorial-practice
university-of-bergen-master-s-programme-in-design
university-of-bergen-master-s-programme-in-digital-culture
university-of-bergen-master-s-programme-in-fine-art
university-of-bergen-master-s-programme-in-french
university-of-bergen-master-s-programme-in-global-health
university-of-bergen-system-dynamics-master-s
university-of-inland-norway-master-in-applied-biotechnology-and-biomedical-sciences
university-of-inland-norway-master-in-applied-ecology
university-of-inland-norway-master-in-digital-communication-and-culture
university-of-inland-norway-master-of-science-in-business-administration-major-business-analytics
university-of-oslo-chemistry
university-of-oslo-economics
university-of-oslo-electronics-informatics-and-technology
university-of-oslo-entrepreneurship-and-innovation-management
university-of-oslo-european-master-in-health-economics-and-management
university-of-oslo-fluid-mechanics
university-of-oslo-gender-studies
university-of-oslo-human-geography
university-of-oslo-informatics-information-security
university-of-oslo-informatics-language-technology
university-of-oslo-informatics-programming-and-systems-architecture
university-of-oslo-informatics-robotics-and-intelligent-systems
university-of-oslo-information-and-communication-technology-law
university-of-oslo-maritime-law
university-of-oslo-mathematics
university-of-oslo-north-sea-energy-law
university-of-oslo-nuclear-science
university-of-oslo-physics
university-of-oslo-psychology
university-of-oslo-public-international-law
university-of-oslo-quantum-science-and-technology
university-of-oslo-renewable-energy-systems
university-of-oslo-research-in-special-needs-education
university-of-oslo-social-anthropology
university-of-oslo-space-systems
university-of-oslo-stochastic-modelling-statistics-and-risk-analysis
university-of-south-eastern-norway-master-in-computer-science
university-of-south-eastern-norway-master-in-digital-transformation
university-of-south-eastern-norway-master-in-ecology-and-environmental-management
university-of-south-eastern-norway-master-in-electrical-power-engineering
university-of-south-eastern-norway-master-in-innovation-and-technology-management
university-of-south-eastern-norway-master-in-it-and-automation
university-of-south-eastern-norway-master-in-process-energy-and-environmental-technology
university-of-south-eastern-norway-master-in-sensor-systems-and-innovation
university-of-south-eastern-norway-master-of-sustainability-management
university-of-south-eastern-norway-systems-engineering-industry-master
university-of-stavanger-data-science-master
university-of-stavanger-economic-transformation-and-innovation-master
university-of-stavanger-economics-and-business-administration-master
university-of-stavanger-energy-reservoir-and-earth-sciences-master
university-of-stavanger-english-and-literacy-studies-master
university-of-stavanger-environmental-engineering-master
university-of-stavanger-industrial-asset-management-master
university-of-stavanger-mathematics-and-physics-master
university-of-stavanger-performing-arts-master
university-of-stavanger-petroleum-engineering-master-of-science-degree-programme
university-of-stavanger-risk-analysis-master
university-of-stavanger-service-leadership-in-international-business-master
university-of-stavanger-structural-and-mechanical-engineering-master
university-of-stavanger-sustainability-studies-master
`.trim().split("\n")

const INDEXABLE_SET = new Set<string>(INDEXABLE_NO_PROGRAM_SLUGS)

export function noProgramDetailPath(slug: string) { return `/programs/no/${slug}` }
export function isIndexableNoProgramSlug(slug: string) { return INDEXABLE_SET.has(slug) }
export const INDEXABLE_NO_PROGRAM_PATHS = INDEXABLE_NO_PROGRAM_SLUGS.map(noProgramDetailPath)
